import { strict as assert } from "node:assert";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test, type TestContext } from "node:test";
import {
	CorpusService, LiteratureService, ProofRuntime, ResearchEvidenceRecorder, ResearchRetrievalService, ResearchRuntime,
	ResearchStateReducer, ResearchStore, Session, createResearchTools, emptyProject, evaluateRouteReopenPredicate,
	rootSynthesisReadiness, sha256, stableId,
	type ArtifactRef, type AuthorityFaultPoint, type LiteratureProvider, type ProofPlan, type ProofPlanner,
	type ProofResearcher, type ProofVerifier, type ResearchArtifact, type ResearchOutcome, type TacticalProofRequest,
	type TacticalResearchResult, type TrustReceipt,
} from "../src/index.js";

async function fixture(t: TestContext, projectId = "p") {
	const directory = await mkdtemp(join(tmpdir(), "mrr-hardening-")); t.after(async () => rm(directory, { recursive: true, force: true }));
	const store = new ResearchStore(join(directory, "data")); await store.create(projectId, projectId); const runtime = new ResearchRuntime({ store, proofRunner: unresolved }); await runtime.setRootObjective(projectId, "Unconditional root theorem");
	return { directory, store, runtime, projectId, root: (await store.read(projectId)).rootClaimId as string };
}

function receipt(claimId: string, candidate: ArtifactRef, suffix = "v"): TrustReceipt {
	return { receiptId: stableId("receipt", claimId, suffix, candidate.contentHash), claimId, candidate, verifierProfile: suffix, evidenceInspected: [], workerReadEvidence: [], verifierReadEvidence: [], verdict: "CORRECT", independentContext: true, stale: false, createdAt: new Date().toISOString() };
}

test("conditional assumptions survive promotion and block an unconditional root", async (t) => {
	const { store, root } = await fixture(t); const reducer = new ResearchStateReducer(store), lemma = await store.putArtifact("p", { artifactType: "WORKER_CANDIDATE", body: "Under H, lemma L follows.", provenance: "conditional-worker" });
	await reducer.apply({ projectId: "p", cycleId: "c1", logicalJobId: "j1", effectSlot: "lemma", outcome: { type: "NEW_LEMMA", claimId: "L", statement: "Lemma L", candidate: lemma, receipts: [receipt("L", lemma)], dependencies: [], assumptions: ["H"], scope: "conditional", supportsClaimId: root } });
	const reduction = await store.putArtifact("p", { artifactType: "WORKER_CANDIDATE", body: "The root reduces to L.", provenance: "reduction-worker" });
	await reducer.apply({ projectId: "p", cycleId: "c2", logicalJobId: "j2", effectSlot: "reduce", outcome: { type: "REDUCTION", claimId: root, childClaims: [{ claimId: "L", statement: "Lemma L" }], proof: reduction, receipts: [receipt(root, reduction)], assumptions: [], dependencies: [], scope: "entire root domain" } });
	const state = await store.read("p"), readiness = rootSynthesisReadiness(state); assert.deepEqual(state.claims.L?.at(-1)?.assumptions, ["H"]); assert.equal(readiness.ready, false); assert.ok(readiness.blockers.some((item) => item.includes("Root dependency not closed: L"))); assert.ok(state.authorityReceipts && Object.values(state.authorityReceipts).some((item) => item.claimId === "L" && item.assumptions.includes("H")));
});

test("empty, singleton, self, and duplicate decompositions fail before truth or authority mutation", async (t) => {
	const { store, root } = await fixture(t); const reducer = new ResearchStateReducer(store), proof = await store.putArtifact("p", { artifactType: "WORKER_CANDIDATE", body: "verified-looking malformed decomposition", provenance: "adversary" }), structuralReceipt = receipt(root, proof);
	const malformed: ResearchOutcome[] = [
		{ type: "REDUCTION", claimId: root, childClaims: [], proof, receipts: [structuralReceipt], assumptions: [], dependencies: [], scope: "root" },
		{ type: "REDUCTION", claimId: root, childClaims: [{ claimId: root, statement: "self" }], proof, receipts: [structuralReceipt], assumptions: [], dependencies: [], scope: "root" },
		{ type: "CASE_SPLIT", claimId: root, scope: "root", coverageAssertion: "claimed exhaustive", cases: [], proof, receipts: [structuralReceipt], assumptions: [], dependencies: [] },
		{ type: "CASE_SPLIT", claimId: root, scope: "root", coverageAssertion: "claimed exhaustive", cases: [{ claimId: "A", statement: "A" }], proof, receipts: [structuralReceipt], assumptions: [], dependencies: [] },
		{ type: "CASE_SPLIT", claimId: root, scope: "root", coverageAssertion: "claimed exhaustive", cases: [{ claimId: "A", statement: "A" }, { claimId: "A", statement: "A again" }], proof, receipts: [structuralReceipt], assumptions: [], dependencies: [] },
	];
	for (const [index, outcome] of malformed.entries()) await assert.rejects(reducer.apply({ projectId: "p", cycleId: `bad-${index}`, logicalJobId: `bad-${index}`, effectSlot: "bad", outcome }), /INVARIANT_ERROR/);
	const state = await store.read("p"); assert.equal(state.claims[root]?.at(-1)?.status, "OPEN"); assert.equal(Object.keys(state.acceptedEffects).length, 0); assert.equal(Object.keys(state.authorityReceipts).length, 0); assert.equal(Object.values(state.artifacts).filter((item) => item.artifactType === "PROMOTED_PROOF").length, 0); assert.equal(rootSynthesisReadiness(state).ready, false); assert.equal((await new ResearchRetrievalService(store).search("p", { text: "malformed", artifactTypes: ["PROMOTED_PROOF"] })).length, 0);
});

test("Planner contribution scope cannot be escalated to TARGET by a Worker", async (t) => {
	const directory = await mkdtemp(join(tmpdir(), "mrr-scope-escalation-")); t.after(async () => rm(directory, { recursive: true, force: true })); const session = await Session.create({ projectId: "scope", sessionId: "scope", cwd: directory, directory });
	const planner: ProofPlanner = { async plan(): Promise<ProofPlan> { return { actions: [{ action: "spawn", tasks: [{ taskId: "local", summary: "local lemma", description: "prove only a local contribution", scope: "CONTRIBUTION", contributionKind: "LEMMA" }] }] }; } }, researcher: ProofResearcher = { async research() { return { kind: "candidate", candidate: { taskId: "local", content: "I claim the whole target", strategy: "scope escalation", scope: "TARGET", contribution: { kind: "LEMMA", statement: "Local lemma", relationshipToTarget: "support only", assumptions: [], dependencyClaims: [] } } }; } }, verifier: ProofVerifier = { async verify() { return { verdict: "CORRECT", feedback: "would accept if reached" }; } };
	const runtime = new ProofRuntime({ session, obligation: { obligationId: "o", theorem: "T" }, planner, researcher, verifier, runId: "scope", maxSteps: 1, workspaceDirectory: join(directory, "run") }), result = await runtime.run(); assert.equal(result.status, "FAILED"); assert.match(result.reason ?? "", /Worker scope TARGET disagrees with Planner task scope CONTRIBUTION/); assert.equal(runtime.state.targetSubmission, undefined); assert.equal(runtime.state.candidates.length, 0);
});

test("authority transition fault points commit either nothing or the full effect exactly once", async (t) => {
	const directory = await mkdtemp(join(tmpdir(), "mrr-authority-faults-")); t.after(async () => rm(directory, { recursive: true, force: true })); const points: AuthorityFaultPoint[] = ["after_validation", "after_prepare", "after_claim_transition", "after_accepted_effect", "after_authority_receipt", "after_event"];
	for (const point of points) {
		const projectId = point.replaceAll("_", "-"), store = new ResearchStore(join(directory, "data")); await store.create(projectId, projectId); const runtime = new ResearchRuntime({ store, proofRunner: unresolved }); await runtime.setRootObjective(projectId, "Atomic root"); const root = (await store.read(projectId)).rootClaimId as string, candidate = await store.putArtifact(projectId, { artifactType: "WORKER_CANDIDATE", body: `candidate ${point}`, provenance: "fault-test", creationAttemptId: "attempt" }), outcome: ResearchOutcome = { type: "PROVED_CLAIM", claimId: root, statement: "Atomic root", candidate, receipts: [receipt(root, candidate, "primary"), receipt(root, candidate, "secondary")], dependencies: [], assumptions: [], scope: "root" }, request = { projectId, cycleId: "cycle", logicalJobId: "job", effectSlot: "promotion", outcome };
		await assert.rejects(new ResearchStateReducer(store, { faultPoint: point }).apply(request), /Injected authority fault/); let state = await store.read(projectId); assert.equal(state.claims[root]?.at(-1)?.status, "OPEN", point); assert.equal(Object.keys(state.acceptedEffects).length, 0, point); assert.equal(Object.keys(state.authorityReceipts).length, 0, point); assert.equal(state.events.filter((item) => item.type === "research/claim_promoted").length, 0, point); assert.equal(Object.values(state.artifacts).filter((item) => item.artifactType === "PROMOTED_PROOF").length, 0, point);
		const reducer = new ResearchStateReducer(store), accepted = await reducer.apply(request), retry = await reducer.apply(request); state = retry.state; assert.equal(accepted.applied, true); assert.equal(retry.applied, false); assert.equal(state.claims[root]?.at(-1)?.status, "PROVED"); assert.equal(Object.keys(state.acceptedEffects).length, 1); assert.equal(Object.keys(state.authorityReceipts).length, 1); assert.equal(state.events.filter((item) => item.type === "research/claim_promoted").length, 1);
	}
});

test("search, body read, and declared reliance remain distinct evidence classes", async (t) => {
	const { store } = await fixture(t); const artifacts = await Promise.all(["A", "B", "C"].map((label) => store.putArtifact("p", { artifactType: "CORPUS_SOURCE", body: `common searchable theorem ${label}`, provenance: "evidence-fixture" }))), recorder = new ResearchEvidenceRecorder(store, "p", "attempt-evidence");
	for (const artifact of artifacts) await recorder.record({ role: "worker", logicalTaskId: "task", operation: "SEARCH", artifact }); await recorder.record({ role: "worker", logicalTaskId: "task", operation: "READ", artifact: artifacts[0] as ResearchArtifact, ranges: ["lines:0-1"] });
	const discovered = await recorder.refs("worker", "task", "DISCOVERED"), reads = await recorder.refs("worker", "task", "BODY_READ"), reliedOnArtifactIds = [artifacts[0]!.artifactId]; assert.deepEqual(discovered.map((item) => item.artifactId).sort(), artifacts.map((item) => item.artifactId).sort()); assert.deepEqual(reads.map((item) => item.artifactId), reliedOnArtifactIds); assert.ok(reliedOnArtifactIds.every((id) => reads.some((item) => item.artifactId === id))); assert.equal(reads.some((item) => item.artifactId === artifacts[1]!.artifactId), false);
});

test("controlled computation produces a durable, hashed, receipted artifact", async (t) => {
	const { store } = await fixture(t); const corpus = new CorpusService(store), scratch = await store.createScratch("p", "compute-attempt"), recorder = new ResearchEvidenceRecorder(store, "p", "compute-attempt"), tools = Object.fromEntries(createResearchTools({ projectId: "p", store, corpus, scratchDirectory: scratch, evidenceRecorder: recorder, defaultRole: "worker", allowedExecutables: { node: process.execPath }, executionBoundary: "CONTROLLED_COMMAND_RUNNER" }).map((item) => [item.name, item])), compute = tools.controlled_computation; assert.ok(compute);
	const output = await compute.execute(compute.validate({ executable: "node", args: ["-e", "process.stdout.write(String(6*7))"] })) as { artifactId: string; contentHash: string }; const state = await store.read("p"), artifact = state.artifacts[output.artifactId]; assert.ok(artifact); assert.equal(artifact.artifactType, "COMPUTATION_RESULT"); assert.equal(output.contentHash.length, 64); const body = JSON.parse((await store.resolveArtifact("p", artifact)).body) as Record<string, any>; assert.equal(body.boundary, "CONTROLLED_COMMAND_RUNNER"); assert.equal(body.executable, "node"); assert.deepEqual(body.arguments, ["-e", "process.stdout.write(String(6*7))"]); assert.equal(body.stdout, "42"); assert.equal(body.exitCode, 0); assert.equal(body.environment.inheritedCredentials, false); assert.ok(Object.values(state.toolEvidenceReceipts).some((item) => item.operation === "COMPUTE" && item.artifact.artifactId === artifact.artifactId));
});

test("Director reduction and counterexample intents reach tactical execution as structured directives", async (t) => {
	const { store, root } = await fixture(t); const reductionRunner = async (request: TacticalProofRequest): Promise<TacticalResearchResult> => { assert.equal(request.directive.action, "REQUEST_REDUCTION"); assert.equal(request.directive.desiredContributionKind, "REDUCTION"); assert.match(request.directive.reductionIntent ?? "", /decompose/); const candidate = await store.putArtifact("p", { artifactType: "WORKER_CANDIDATE", body: "root iff child", provenance: "directive-worker" }), verification = receipt(root, candidate); return tactical(request, [{ contributionId: "reduction", kind: "REDUCTION", statement: "Root reduces to child", relationshipToTarget: "exact equivalence", targetObligationId: request.obligation.obligationId, targetClaimId: root, assumptions: [], dependencyClaims: [], evidenceArtifacts: [], candidate, producer: { role: "worker", identity: "mock", taskId: "reduce" }, verification, childClaims: [{ claimId: "child", statement: "Child claim" }], targetScope: "root domain" }]); };
	let runtime = new ResearchRuntime({ store, proofRunner: reductionRunner, modelDirector: { async decide(snapshot) { const target = snapshot.frontier.find((item) => item.claimId === root)!; return { action: "REQUEST_REDUCTION", targetObligationId: target.obligationId, targetClaimId: root, reason: "decompose the root into an exact child" }; } } }); let state = await runtime.runCycle("p"); assert.equal(state.claims[root]?.at(-1)?.status, "REDUCED"); assert.equal(Object.values(state.jobs)[0]?.directive?.desiredContributionKind, "REDUCTION");
	const counterRunner = async (request: TacticalProofRequest): Promise<TacticalResearchResult> => { assert.equal(request.directive.action, "REQUEST_COUNTEREXAMPLE"); assert.equal(request.directive.desiredContributionKind, "COUNTEREXAMPLE"); const candidate = await store.putArtifact("p", { artifactType: "WORKER_CANDIDATE", body: "witness x lies in the child domain", provenance: "directive-worker" }), verification = receipt("child", candidate); return tactical(request, [{ contributionId: "counter", kind: "COUNTEREXAMPLE", claimId: "child", statement: "Counterexample to child", relationshipToTarget: "refutes the exact child", targetObligationId: request.obligation.obligationId, targetClaimId: "child", assumptions: [], dependencyClaims: [], evidenceArtifacts: [], candidate, producer: { role: "worker", identity: "mock", taskId: "counter" }, verification, targetScope: "all child-domain inputs", counterexampleScope: "witness x in child domain" }]); };
	runtime = new ResearchRuntime({ store, proofRunner: counterRunner, modelDirector: { async decide(snapshot) { const target = snapshot.frontier.find((item) => item.claimId === "child")!; return { action: "REQUEST_COUNTEREXAMPLE", targetObligationId: target.obligationId, targetClaimId: "child", reason: "seek an in-domain counterexample" }; } } }); state = await runtime.runCycle("p"); assert.equal(state.claims.child?.at(-1)?.status, "REFUTED"); assert.equal(Object.values(state.jobs).at(-1)?.directive?.desiredContributionKind, "COUNTEREXAMPLE");
});

test("a CHANGE_ROUTE TacticalDirective reaches the actual Proof Planner context unchanged", async (t) => {
	const directory = await mkdtemp(join(tmpdir(), "mrr-directive-planner-")); t.after(async () => rm(directory, { recursive: true, force: true })); const session = await Session.create({ projectId: "directive", sessionId: "directive", cwd: directory, directory }), directive = { directorDecisionId: "decision-1", action: "CHANGE_ROUTE", routeFamily: "descent", reason: "replace the failed parity route with descent", relevantFailedRoutes: [{ routeId: "old", mechanism: "parity", failureMechanism: "no decrease" }] }; let observed: unknown;
	const planner: ProofPlanner = { async plan(context) { observed = context.tacticalDirective; return { actions: [{ action: "stop", reason: "directive inspected" }] }; } }, researcher: ProofResearcher = { async research() { return { kind: "blocked", reason: "unused" }; } }, verifier: ProofVerifier = { async verify() { return { verdict: "UNFINISHED", feedback: "unused" }; } };
	await new ProofRuntime({ session, obligation: { obligationId: "o", theorem: "T" }, planner, researcher, verifier, tacticalDirective: directive, maxSteps: 1, workspaceDirectory: join(directory, "run") }).run(); assert.deepEqual(observed, directive);
});

test("STOP_PROJECT persists an intentional terminal turn and does not start another cycle", async (t) => {
	const { store } = await fixture(t); let decisions = 0, tacticalCalls = 0; const runtime = new ResearchRuntime({ store, proofRunner: async (request) => { tacticalCalls += 1; return unresolved(request); }, modelDirector: { async decide() { decisions += 1; return { action: "STOP_PROJECT", reason: "bounded campaign deliberately stopped" }; } } });
	const state = await runtime.run("p", 5); assert.equal(state.status, "PARTIAL"); assert.equal(state.cycle, 1); assert.equal(decisions, 1); assert.equal(tacticalCalls, 0); assert.equal(state.checkpoints.length, 1); assert.ok(state.events.some((item) => item.type === "research/project_stopped" && item.detail.reason === "bounded campaign deliberately stopped"));
});

test("all typed route reopen predicates have deterministic state semantics", async () => {
	const base = emptyProject("p", "p"), now = new Date().toISOString(), artifact = { artifactId: "a", contentHash: "a".repeat(64), artifactType: "LITERATURE_SOURCE" as const, bodyPath: "unused", provenance: "test", authority: "LITERATURE_SOURCE" as const, references: [], metadata: { authorityTier: "FULL_TEXT" }, createdAt: now }, claim = { claimId: "L", revision: 1, statement: "L", role: "LEMMA" as const, status: "PROVED" as const, dependencies: [], evidenceRefs: [], auditRefs: [], assumptions: [], provenance: "test", createdAt: now }, authority = { authorityReceiptId: "ar", effectId: "e", effectKind: "PROVED_CLAIM" as const, claimId: "L", claimRevision: 1, artifact, sourceArtifact: artifact, trustReceiptIds: [], evidenceRefs: [], assumptions: [], dependencies: [], dependencyRevisions: {}, assumptionDischarges: [], createdAt: now }, state = { ...base, claims: { L: [claim], R: [{ ...claim, claimId: "R", status: "REFUTED" as const }] }, artifacts: { a: artifact }, authorityReceipts: { ar: authority, arr: { ...authority, authorityReceiptId: "arr", claimId: "R", effectKind: "REFUTED_CLAIM" as const } }, authorityValidation: { ar: { authorityReceiptId: "ar", status: "ACTIVE" as const, causalAuthorityReceiptIds: [], changedAt: now }, arr: { authorityReceiptId: "arr", status: "ACTIVE" as const, causalAuthorityReceiptIds: [], changedAt: now } }, events: [{ eventId: "domain", type: "research/parameter_domain_reduced", projectId: "p", timestamp: now, detail: { domainId: "D" } }, { eventId: "assumption", type: "research/assumption_changed", projectId: "p", timestamp: now, detail: { assumption: "H", value: "discharged" } }] };
	const route = (predicate: any, updatedAt = "2000-01-01T00:00:00.000Z", artifactRefs: ArtifactRef[] = []) => ({ routeId: `r-${predicate.type}`, targetObligationId: "o", family: "f", mechanism: "m", strategyDescription: "s", assumptions: [], dependencySnapshot: [], artifactRefs, status: "FAILED" as const, attemptIds: [], reopenPredicate: predicate, createdAt: updatedAt, updatedAt });
	for (const predicate of [{ type: "CLAIM_PROVED", claimId: "L" }, { type: "CLAIM_REFUTED", claimId: "R" }, { type: "PARAMETER_DOMAIN_REDUCED", domainId: "D" }, { type: "LITERATURE_AVAILABLE", sourceClass: "FULL_TEXT" }, { type: "ASSUMPTION_CHANGED", assumption: "H", value: "discharged" }]) assert.equal(evaluateRouteReopenPredicate(state as any, route(predicate) as any).satisfied, true, predicate.type);
	const manual = route({ type: "MANUAL_REOPEN" }); assert.equal(evaluateRouteReopenPredicate(state as any, manual as any).satisfied, false); assert.equal(evaluateRouteReopenPredicate(state as any, manual as any, "MODEL_DIRECTOR").satisfied, false); assert.equal(evaluateRouteReopenPredicate(state as any, manual as any, "OPERATOR").satisfied, true);
	const evidenceState = { ...state, claims: { ...state.claims, E: [{ ...claim, claimId: "E", evidenceRefs: [artifact] }] } }; assert.equal(evaluateRouteReopenPredicate(evidenceState as any, route({ type: "NEW_EVIDENCE_FOR", claimId: "E" }, "2000-01-01T00:00:00.000Z") as any).satisfied, true); assert.equal(evaluateRouteReopenPredicate(state as any, route({ type: "CLAIM_PROVED", claimId: "missing" }) as any).satisfied, false);
});

test("Director cannot reopen a route whose typed predicate is unsatisfied", async (t) => {
	const { store } = await fixture(t); const before = await store.read("p"), obligation = Object.values(before.obligations)[0]!; await store.transaction("p", (draft) => { (draft as any).routes = { illegal: { routeId: "illegal", targetObligationId: obligation.obligationId, family: "descent", mechanism: "minimal-counterexample", strategyDescription: "retry only after missing lemma", assumptions: [], dependencySnapshot: [], artifactRefs: [], status: "FAILED", attemptIds: [], reopenPredicate: { type: "CLAIM_PROVED", claimId: "not-proved" }, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() } }; });
	const guarded = new ResearchRuntime({ store, proofRunner: unresolved, modelDirector: { async decide() { return { action: "REOPEN_ROUTE", routeId: "illegal", reason: "attempt to bypass the typed predicate" }; } } }), state = await guarded.runCycle("p"); assert.equal(state.routes.illegal?.status, "FAILED"); assert.equal(state.decisions[0]?.direction, "FALLBACK_DIRECTED"); assert.notEqual(state.decisions[0]?.action, "REOPEN_ROUTE"); assert.match(state.decisions[0]?.protocolError ?? "", /reopen predicate is not satisfied/iu);
});

test("large corpus files are analyzed in bounded exact ranges and merged", async (t) => {
	const { directory, store } = await fixture(t); const corpusRoot = join(directory, "corpus"); await mkdir(corpusRoot); const lines = Array.from({ length: 5_000 }, (_, index) => `Lemma L${index}: bounded semantic line ${"x".repeat(20)}`); await writeFile(join(corpusRoot, "large.md"), lines.join("\n")); const corpus = new CorpusService(store); await corpus.attach("p", [corpusRoot]); await corpus.ingest("p"); const calls: { range: { startLine: number; endLine: number }; body: string }[] = [];
	const report = await corpus.bootstrap("p", { async analyzeFile(request) { calls.push({ range: request.range, body: request.body }); return { proposals: [{ entityKey: `chunk-${request.range.startLine}`, kind: "CLAIM", statement: `Chunk lemma ${request.range.startLine}`, dependencyHints: [] }], dependencies: [] }; } }); assert.ok(calls.length > 1); assert.deepEqual(report.analyzedRanges.map(({ startLine, endLine }) => ({ startLine, endLine })), calls.map((item) => item.range)); assert.ok(calls.every((item) => Buffer.byteLength(item.body) <= 64 * 1024)); assert.ok(report.proposals.every((item) => item.sourceRange !== undefined)); assert.equal(report.proposals.length, calls.length);
});

test("literature metadata, abstract, landing page, exact excerpt, and full text retain distinct authority tiers", async (t) => {
	const { store } = await fixture(t); const candidates = [{ sourceId: "metadata", title: "Metadata", authors: [] }, { sourceId: "abstract", title: "Abstract", authors: [], abstract: "Only an abstract" }, { sourceId: "landing", title: "Landing", authors: [] }, { sourceId: "excerpt", title: "Excerpt", authors: [] }, { sourceId: "full", title: "Full", authors: [] }], provider: LiteratureProvider = { async search() { return candidates; }, async acquire(candidate) { if (candidate.sourceId === "landing") return { body: "<html>publisher landing page</html>", authorityTier: "LANDING_PAGE", mediaType: "text/html" }; if (candidate.sourceId === "excerpt") return { body: "Exact theorem excerpt", authorityTier: "EXACT_EXCERPT", mediaType: "text/plain" }; if (candidate.sourceId === "full") return { body: "Complete article text", authorityTier: "FULL_TEXT", mediaType: "text/plain" }; return undefined; } }; let assessments = 0;
	const results = await new LiteratureService(store, provider).discover("p", "q", "o", () => { assessments += 1; return { literatureClaim: "usable theorem", assumptions: [], applicable: true, reason: "exact", scopeLimitations: [] }; }); assert.deepEqual(results.map((item) => item.authorityTier), ["DISCOVERED_METADATA", "ABSTRACT_ONLY", "LANDING_PAGE", "EXACT_EXCERPT", "FULL_TEXT"]); assert.deepEqual(results.map((item) => item.authority), ["SOURCE_DISCOVERED_AUTHORITY_INSUFFICIENT", "SOURCE_DISCOVERED_AUTHORITY_INSUFFICIENT", "SOURCE_DISCOVERED_AUTHORITY_INSUFFICIENT", "EXACT_SOURCE", "EXACT_SOURCE"]); assert.equal(assessments, 2); assert.notEqual(results[2]?.authorityTier, "FULL_TEXT");
});

test("MRR v1 state migration preserves history and reopens unsafe authority for revalidation", async (t) => {
	const directory = await mkdtemp(join(tmpdir(), "mrr-v1-migration-")); t.after(async () => rm(directory, { recursive: true, force: true })); const store = new ResearchStore(directory), projectId = "legacy", projectDirectory = store.projectDirectory(projectId), artifactDirectory = join(projectDirectory, "artifacts"); await mkdir(artifactDirectory, { recursive: true }); await mkdir(join(projectDirectory, "scratch"), { recursive: true }); const body = "legacy proof body", contentHash = sha256(body), artifactId = "legacy-artifact", bodyPath = join(artifactDirectory, `${artifactId}.body`), now = new Date().toISOString(); await writeFile(bodyPath, body);
	const artifact: ResearchArtifact = { artifactId, contentHash, artifactType: "PROMOTED_PROOF", bodyPath, provenance: "legacy", references: [], createdAt: now }, legacy = { ...emptyProject(projectId, "legacy", now), schemaVersion: 1, status: "PROVED", rootObjective: "Legacy theorem", rootClaimId: "root", artifacts: { [artifactId]: artifact }, claims: { root: [{ claimId: "root", revision: 1, statement: "Legacy theorem", role: "ROOT", status: "PROVED", dependencies: [], evidenceRefs: [artifact], auditRefs: [], assumptions: [], provenance: "legacy", createdAt: now }] }, obligations: {}, events: [{ eventId: "legacy-event", type: "legacy/history", projectId, timestamp: now, detail: { preserved: true } }], migrationReports: [] }; await writeFile(join(projectDirectory, "state.json"), `${JSON.stringify(legacy, null, 2)}\n`);
	const migrated = await store.read(projectId); assert.equal(migrated.schemaVersion, 4); assert.equal(migrated.status, "PARTIAL"); assert.equal(migrated.claims.root?.at(-1)?.status, "NEEDS_REVALIDATION"); assert.ok(migrated.artifacts[artifactId]); assert.ok(migrated.events.some((item) => item.eventId === "legacy-event")); assert.equal((await store.resolveArtifact(projectId, artifact)).body, body); assert.ok(Object.values(migrated.obligations).some((item) => item.claimId === "root" && item.status === "OPEN")); assert.deepEqual(migrated.migrationReports[0]?.downgradedClaimIds, ["root"]); assert.equal(migrated.migrationReports[0]?.preservedArtifactCount, 1); assert.equal(migrated.migrationReports[0]?.preservedEventCount, 1); assert.equal(migrated.rootObjectiveContract?.status, "NEEDS_REVALIDATION"); assert.deepEqual(migrated.rootObjectiveContract?.allowedAssumptions, []);
});

async function unresolved(request: TacticalProofRequest): Promise<TacticalResearchResult> { return tactical(request, []); }
function tactical(request: TacticalProofRequest, contributions: TacticalResearchResult["contributions"]): TacticalResearchResult { const now = new Date().toISOString(); return { obligationId: request.obligation.obligationId, targetClaimId: request.targetClaimId, targetStatus: "TARGET_UNRESOLVED", contributions, routeObservations: [], executionReceipt: { executionReceiptId: stableId("execution", request.attemptId), logicalJobId: request.logicalJobId, attemptId: request.attemptId, taskIds: [], evidenceReceiptIds: [], startedAt: now, completedAt: now }, feedback: contributions.length === 0 ? "unresolved" : "verified contribution" }; }
