import { strict as assert } from "node:assert";
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import { AgentCore, MathAgentConfigService, MockProvider, ProofApiServer, ResearchStateReducer, ResearchStore, Session, createAgentProofRoles, type Agent, type LiteratureProvider, type MathAgentConfig, type MockResponse, type ProofApiRoleFactory, type ProofCandidate, type ProofPlan, type ProofResearchContext, type ProofVerifierContext, type RuntimeTool } from "../src/index.js";

test("real AgentCore lemma contribution cannot prove target, then later agents retrieve the promoted proof with exact receipts", async (t) => {
	const directory = await mkdtemp(join(tmpdir(), "mrr-production-memory-")), data = join(directory, "data"); await mkdir(data); let tacticalRuns = 0, agentOrdinal = 0;
	const makeAgent = async (name: string, responses: readonly MockResponse[], tools?: readonly RuntimeTool[]): Promise<Agent> => { agentOrdinal += 1; const identity = `${name}-${agentOrdinal}`, roleDirectory = join(directory, "agents", identity); const session = await Session.create({ projectId: identity, sessionId: identity, cwd: directory, directory: roleDirectory }); return new AgentCore({ session, model: { provider: "mock", model: name }, provider: new MockProvider(responses), ...(tools === undefined ? {} : { tools }), maxTurns: 8 }); };
	const factory = (async (context) => {
		tacticalRuns += 1; const gate = context.targetGate; assert.ok(gate); const store = new ResearchStore(join(data, "research"));
		if (tacticalRuns === 1) {
			const planner = await makeAgent("planner", [text({ actions: [{ action: "spawn", tasks: [{ taskId: "lemma-task", summary: "Prove a reusable lemma", description: "Prove the exact intermediate memory lemma.", scope: "CONTRIBUTION", contributionKind: "LEMMA", routeKey: "memory-lemma" }] }] }), text({ actions: [{ action: "stop", reason: "Lemma established; target remains open" }] })]);
			const worker = await makeAgent("worker", [text({ kind: "candidate", candidate: { strategy: "direct", scope: "CONTRIBUTION", content: "For every integer n, n+n=2n by the definition of multiplication by 2.", contribution: { kind: "LEMMA", statement: "Memory lemma: for every integer n, n+n=2n.", relationshipToTarget: "Supplies the algebraic identity needed by the root", claimId: "lemma-memory", assumptions: [], dependencyClaims: [] } } })], context.tools);
			const verifier = await makeAgent("verifier", [text({ verdict: "CORRECT", feedback: "The intermediate lemma is correct, but this verdict concerns only that lemma." })], context.tools);
			return createAgentProofRoles({ planner, researcher: worker, verifier });
		}
		const project = (await store.listProjects())[0]; assert.ok(project); const promoted = Object.values(project.artifacts).find((item) => item.artifactType === "PROMOTED_PROOF" && item.metadata === undefined); assert.ok(promoted, "cycle 2 must discover cycle 1's promoted mathematical artifact");
		const planner = await makeAgent("planner", [text({ actions: [{ action: "spawn", tasks: [{ taskId: "target-task", summary: "Prove exact target using memory", description: "Retrieve and use the promoted Memory lemma, then prove the exact target.", scope: "TARGET", targetClaimId: gate!.targetClaimId, routeKey: "reuse-memory" }] }] }), text({ actions: [{ action: "submit_target_proof", candidateId: "target-task-candidate", targetObligationId: gate!.targetObligationId, targetClaimId: gate!.targetClaimId }] })]);
		const worker = await makeAgent("worker", [tool("search-memory", "artifact_search", { query: "Memory lemma", artifactTypes: ["PROMOTED_PROOF"], limit: 1 }), tool("read-memory", "artifact_read", { artifactId: promoted!.artifactId }), text({ kind: "candidate", candidate: { strategy: "reuse verified memory", scope: "TARGET", content: "By the exact promoted Memory lemma, n+n=2n for every integer n, which is precisely the target conclusion." } })], context.tools);
		const verifier = await makeAgent("verifier", [tool("verify-memory", "artifact_read", { artifactId: promoted!.artifactId }), text({ verdict: "CORRECT", feedback: "The promoted lemma body was inspected and the exact target follows." })], context.tools);
		return createAgentProofRoles({ planner, researcher: worker, verifier });
	}) as ProofApiRoleFactory;
	factory.createAgent = async ({ role, tools }) => {
		const project = (await new ResearchStore(join(data, "research")).listProjects())[0], promoted = project === undefined ? undefined : Object.values(project.artifacts).find((item) => item.artifactType === "PROMOTED_PROOF");
		if (role === "secondary_auditor" && promoted !== undefined) return makeAgent(role, [tool("secondary-read", "artifact_read", { artifactId: promoted.artifactId }), text({ verdict: "CORRECT", feedback: "Fresh audit inspected the dependency and accepts the root proof." })], tools);
		if (role === "research_director") return makeAgent(role, [text({ action: "ATTACK_OBLIGATION", reason: "Use deterministic target validation" })], tools);
		return makeAgent(role, [text({ verdict: "CORRECT", feedback: "correct" })], tools);
	};
	const server = new ProofApiServer({ rootDirectory: data, createRoles: factory, defaultMaxWorkers: 1, defaultMaxSteps: 3 }); t.after(async () => { await server.stop(); await rm(directory, { recursive: true, force: true }); }); const base = await server.start();
	await request(base, "/v1/research/projects", "POST", { projectId: "memory", name: "memory" }); await request(base, "/v1/research/projects/memory/root", "POST", { objective: "For every integer n, n+n=2n." });
	await request(base, "/v1/research/projects/memory/start", "POST", { maxCycles: 1 }); let state = await waitProject(base, "memory"); const rootId = state.rootClaimId as string; assert.equal(state.claims[rootId].at(-1).status, "OPEN", "a correct lemma must not prove its parent target"); assert.ok(state.claims["lemma-memory"], JSON.stringify({ lastError: state.lastError, events: state.events })); assert.equal(state.claims["lemma-memory"].at(-1).status, "PROVED"); assert.ok(state.supportEdges.some((edge: any) => edge.fromClaimId === "lemma-memory" && edge.toClaimId === rootId));
	await request(base, "/v1/research/projects/memory/resume", "POST", { maxCycles: 1 }); state = await waitProject(base, "memory"); assert.equal(state.status, "PROVED"); const receipts = Object.values(state.toolEvidenceReceipts) as any[]; assert.ok(receipts.some((item) => item.role === "worker" && item.operation === "READ" && item.artifact.artifactType === "PROMOTED_PROOF")); assert.ok(receipts.some((item) => item.role === "verifier" && item.operation === "READ" && item.artifact.artifactType === "PROMOTED_PROOF")); assert.ok(receipts.some((item) => item.role === "secondary_auditor" && item.operation === "READ"));
});

test("malformed TARGET_PROVED without exact target submission fails closed", async (t) => {
	const directory = await mkdtemp(join(tmpdir(), "mrr-truth-gate-")); t.after(async () => rm(directory, { recursive: true, force: true })); const store = new ResearchStore(directory); await store.create("p", "p"); const now = new Date().toISOString(), reducer = new ResearchStateReducer(store);
	await assert.rejects(reducer.applyTactical({ projectId: "p", cycleId: "c", logicalJobId: "j", obligationId: "o", targetClaimId: "t", result: { obligationId: "o", targetClaimId: "t", targetStatus: "TARGET_PROVED", contributions: [], routeObservations: [], executionReceipt: { executionReceiptId: "e", logicalJobId: "j", attemptId: "a", taskIds: [], evidenceReceiptIds: [], startedAt: now, completedAt: now }, feedback: "a worker lemma was correct" } }), /exact verified target submission/);
});

test("real AgentCore reduction and case-split contributions create dependency and coverage state", async (t) => {
	const directory = await mkdtemp(join(tmpdir(), "mrr-production-structures-")), data = join(directory, "data"); let ordinal = 0;
	const make = async (name: string, responses: readonly MockResponse[], tools?: readonly RuntimeTool[]): Promise<Agent> => { ordinal += 1; const identity = `${name}-${ordinal}`, session = await Session.create({ projectId: identity, sessionId: identity, cwd: directory, directory: join(directory, "agents", identity) }); return new AgentCore({ session, model: { provider: "mock", model: name }, provider: new MockProvider(responses), ...(tools === undefined ? {} : { tools }) }); };
	const factory = (async (context) => { const isCases = context.obligation.theorem.includes("case root"), kind = isCases ? "CASE_SPLIT" : "REDUCTION", taskId = isCases ? "case-split-task" : "reduction-task", children = isCases ? [{ claimId: "case-a", statement: "Case A" }, { claimId: "case-b", statement: "Case B" }] : [{ claimId: "lemma-one", statement: "Lemma One" }, { claimId: "lemma-two", statement: "Lemma Two" }]; const planner = await make("planner", [text({ actions: [{ action: "spawn", tasks: [{ taskId, summary: `Produce ${kind}`, description: `Give a verified ${kind} contribution`, scope: "CONTRIBUTION", contributionKind: kind }] }] }), text({ actions: [{ action: "stop", reason: "structural contribution complete" }] })]); const worker = await make("worker", [text({ kind: "candidate", candidate: { strategy: "decomposition", scope: "CONTRIBUTION", content: `Verified ${kind} proof body`, contribution: { kind, statement: `The target admits ${kind}`, relationshipToTarget: "Exact structural decomposition", assumptions: [], dependencyClaims: [], childClaims: children, ...(isCases ? { coverageScope: "all admissible inputs", coverageAssertion: "The listed cases are exhaustive and mutually exclusive" } : {}) } } })], context.tools); const verifier = await make("verifier", [text({ verdict: "CORRECT", feedback: "The stated structural contribution is valid." })], context.tools); return createAgentProofRoles({ planner, researcher: worker, verifier }); }) as ProofApiRoleFactory;
	const server = new ProofApiServer({ rootDirectory: data, createRoles: factory, defaultMaxWorkers: 1, defaultMaxSteps: 3 }); t.after(async () => { await server.stop(); await rm(directory, { recursive: true, force: true }); }); const base = await server.start();
	for (const [projectId, objective] of [["reduction", "A reduction root"], ["cases", "A case root"]] as const) { await request(base, "/v1/research/projects", "POST", { projectId }); await request(base, `/v1/research/projects/${projectId}/root`, "POST", { objective }); await request(base, `/v1/research/projects/${projectId}/start`, "POST", { maxCycles: 1 }); const state = await waitProject(base, projectId), root = state.rootClaimId as string; assert.equal(state.claims[root].at(-1).status, "REDUCED", state.lastError ?? JSON.stringify(state.events)); if (projectId === "reduction") { assert.deepEqual(state.claims[root].at(-1).dependencies.sort(), ["lemma-one", "lemma-two"]); assert.ok(Object.values(state.obligations).some((item: any) => item.claimId === "lemma-one" && item.status === "OPEN")); } else { const coverage = Object.values(state.coverage)[0] as any; assert.deepEqual(coverage.childClaimIds.sort(), ["case-a", "case-b"]); assert.equal(coverage.disposition, "OPEN"); } }
});

test("HTTP root synthesis uses configured roles and a failed fresh audit reopens research", async (t) => {
	const directory = await mkdtemp(join(tmpdir(), "mrr-http-synthesis-")), data = join(directory, "data"); let ordinal = 0;
	const make = async (name: string, responses: readonly MockResponse[], tools?: readonly RuntimeTool[]): Promise<Agent> => { ordinal += 1; const identity = `${name}-${ordinal}`, session = await Session.create({ projectId: identity, sessionId: identity, cwd: directory, directory: join(directory, "agents", identity) }); return new AgentCore({ session, model: { provider: "mock", model: name }, provider: new MockProvider(responses), ...(tools === undefined ? {} : { tools }) }); };
	const factory = (async (context) => { const gate = context.targetGate!; if (context.obligation.theorem.includes("Composite root")) { const planner = await make("planner", [text({ actions: [{ action: "spawn", tasks: [{ taskId: `reduce-${gate.targetClaimId}`, summary: "Reduce root", description: "Prove the root reduction", scope: "CONTRIBUTION", contributionKind: "REDUCTION" }] }] }), text({ actions: [{ action: "stop", reason: "reduction complete" }] })]); const worker = await make("worker", [text({ kind: "candidate", candidate: { scope: "CONTRIBUTION", strategy: "two lemmas", content: "The root follows from Child One and Child Two.", contribution: { kind: "REDUCTION", statement: "The root reduces to two child lemmas", relationshipToTarget: "Exact implication", assumptions: [], dependencyClaims: [], childClaims: [{ claimId: `${gate.targetClaimId}-one`, statement: "Child One" }, { claimId: `${gate.targetClaimId}-two`, statement: "Child Two" }] } } })], context.tools); return createAgentProofRoles({ planner, researcher: worker, verifier: await make("verifier", [text({ verdict: "CORRECT", feedback: "valid reduction" })], context.tools) }); }
		const candidateId = `target-${gate.targetClaimId}-candidate`, taskId = `target-${gate.targetClaimId}`, planner = await make("planner", [text({ actions: [{ action: "spawn", tasks: [{ taskId, summary: "Prove child", description: "Prove this exact child target", scope: "TARGET", targetClaimId: gate.targetClaimId }] }] }), text({ actions: [{ action: "submit_target_proof", candidateId, targetObligationId: gate.targetObligationId, targetClaimId: gate.targetClaimId }] })]); const worker = await make("worker", [text({ kind: "candidate", candidate: { candidateId, scope: "TARGET", strategy: "direct", content: `Complete proof of ${context.obligation.theorem}` } })], context.tools); return createAgentProofRoles({ planner, researcher: worker, verifier: await make("verifier", [text({ verdict: "CORRECT", feedback: "child proof correct" })], context.tools) }); }) as ProofApiRoleFactory;
	factory.createAgent = async ({ role, sessionId, tools }) => { if (role === "research_director") return make(role, [text({ action: "ATTACK_OBLIGATION", reason: "use validated fallback target" })], tools); if (role === "synthesizer") return make(role, [text({ proof: "Fresh synthesized proof combining both child lemmas.", usedArtifactIds: [] })], tools); if (role === "secondary_auditor" && sessionId === "gap") return make(role, [text({ verdict: "CRITICALLY_FLAWED", feedback: "A boundary case is missing." })], tools); return make(role, [text({ verdict: "CORRECT", feedback: "Fresh independent audit accepts the synthesis." })], tools); };
	const server = new ProofApiServer({ rootDirectory: data, createRoles: factory, defaultMaxWorkers: 1, defaultMaxSteps: 3 }); t.after(async () => { await server.stop(); await rm(directory, { recursive: true, force: true }); }); const base = await server.start();
	for (const projectId of ["closed", "gap"]) { await request(base, "/v1/research/projects", "POST", { projectId }); await request(base, `/v1/research/projects/${projectId}/root`, "POST", { objective: `Composite root ${projectId}` }); await request(base, `/v1/research/projects/${projectId}/start`, "POST", { maxCycles: 3 }); let state = await waitProject(base, projectId); assert.equal(state.claims[state.rootClaimId].at(-1).status, "REDUCED"); const readiness = await request(base, `/v1/research/projects/${projectId}/root-readiness`); assert.equal(readiness.ready, true, JSON.stringify(readiness)); const synthesis = await request(base, `/v1/research/projects/${projectId}/synthesis`, "POST", {}); state = synthesis.state; if (projectId === "closed") { assert.equal(state.status, "PROVED"); assert.equal(state.artifacts[state.finalProofArtifact.artifactId].artifactType, "FINAL_PROOF"); } else { assert.notEqual(state.status, "PROVED"); assert.ok(Object.values(state.obligations).some((item: any) => item.causalReason === "Fresh final audit rejected synthesis" && item.status === "OPEN")); } }
});

test("production semantic bootstrap role reconstructs authority, dependencies, failed routes, coverage, and frontier", async (t) => {
	const directory = await mkdtemp(join(tmpdir(), "mrr-semantic-bootstrap-")), data = join(directory, "data"), corpus = join(directory, "corpus"); await mkdir(corpus); await writeFile(join(corpus, "research-map.md"), ["Lemma Established (historically marked proved).", "Lemma Provisional remains unchecked.", "Open problem Main remains unresolved.", "Historical reduction Main follows from Established.", "Case split Main: even and odd.", "Failed route descent for Main because the descent measure is unavailable."].join("\n")); let ordinal = 0;
	const make = async (name: string, responses: readonly MockResponse[]): Promise<Agent> => { ordinal += 1; const identity = `${name}-${ordinal}`, session = await Session.create({ projectId: identity, sessionId: identity, cwd: directory, directory: join(directory, "agents", identity) }); return new AgentCore({ session, model: { provider: "mock", model: name }, provider: new MockProvider(responses) }); };
	const factory = (async () => { throw new Error("Tactical proof roles are not used during bootstrap"); }) as ProofApiRoleFactory;
	factory.createAgent = async ({ role, runId }) => { assert.equal(role, "corpus_bootstrapper"); if (runId === "consistency-review") return make(role, [text({ frontierEntityKeys: ["open-main"], warnings: [] })]); return make(role, [text(canonicalBootstrapResponse({ proposals: [{ entityKey: "proved-lemma", kind: "CLAIM", statement: "Established lemma from the historical corpus", dependencyHints: [] }, { entityKey: "provisional-lemma", kind: "CLAIM", statement: "Provisional lemma requiring current validation", dependencyHints: [] }, { entityKey: "open-main", kind: "OPEN_PROBLEM", statement: "Main open problem", dependencyHints: [] }, { entityKey: "historical-reduction", kind: "REDUCTION", statement: "Main reduces to the Established lemma", dependencyHints: ["proved-lemma"], targetHint: "open-main" }, { entityKey: "main-cases", kind: "CASE_SPLIT", statement: "Main is exhausted by the even and odd cases", dependencyHints: [], targetHint: "open-main", cases: ["even case", "odd case"] }, { entityKey: "failed-descent", kind: "FAILED_ROUTE", statement: "Descent failed for Main", dependencyHints: [], targetHint: "open-main", routeFamily: "descent", mechanism: "minimal-counterexample", failureMechanism: "descent measure unavailable" }], dependencies: [{ fromEntity: "historical-reduction", toEntity: "proved-lemma", confidence: "EXPLICIT" }], warnings: [] }))]); };
	const server = new ProofApiServer({ rootDirectory: data, createRoles: factory }); t.after(async () => { await server.stop(); await rm(directory, { recursive: true, force: true }); }); const base = await server.start();
	await request(base, "/v1/research/projects", "POST", { projectId: "bootstrap" }); await request(base, "/v1/research/projects/bootstrap/root", "POST", { objective: "Resolve the imported Main problem" }); await request(base, "/v1/research/projects/bootstrap/corpus", "POST", { roots: [corpus] }); await request(base, "/v1/research/projects/bootstrap/corpus/ingest", "POST", {}); const response = await request(base, "/v1/research/projects/bootstrap/bootstrap", "POST", {}), state = response.state;
	assert.equal(response.report.modelDirected, true); assert.deepEqual(response.report.stages, ["MANIFEST_INDEX", "PER_FILE_SEMANTIC_ANALYSIS", "ENTITY_MERGE", "DEPENDENCY_RECONSTRUCTION", "FAILED_ROUTE_RECONSTRUCTION", "FRONTIER_PROPOSAL", "CONSISTENCY_REVIEW", "PROVISIONAL_IMPORT"]); assert.equal(response.report.proposals.length, 6); assert.ok(response.report.proposals.every((item: any) => item.authority !== "VERIFIED_CURRENT"));
	const established = Object.values(state.claims).map((items: any) => items.at(-1)).find((item: any) => item.statement.includes("Established lemma")), mainObligation = (Object.values(state.obligations) as any[]).find((item: any) => item.statement === "Main open problem"), main = state.claims[mainObligation.claimId].at(-1); assert.ok(main.dependencies.includes(established.claimId)); assert.ok(response.report.reconstructedReductions.some((item: any) => item.parentClaimId === main.claimId && item.childClaimIds.includes(established.claimId))); assert.ok(Object.values(state.routes).some((route: any) => route.family === "descent" && route.status === "FAILED" && route.failureMechanism === "descent measure unavailable")); assert.ok(Object.values(state.coverage).some((item: any) => item.childClaimIds.length === 2 && item.disposition === "OPEN")); assert.ok(response.report.frontierObligationIds.includes(mainObligation.obligationId));
});

test("public literature path acquires exact source and records Worker, Verifier, and auditor use", async (t) => {
	const directory = await mkdtemp(join(tmpdir(), "mrr-literature-production-")), data = join(directory, "data"); let ordinal = 0;
	const make = async (name: string, responses: readonly MockResponse[], tools?: readonly RuntimeTool[]): Promise<Agent> => { ordinal += 1; const identity = `${name}-${ordinal}`, session = await Session.create({ projectId: identity, sessionId: identity, cwd: directory, directory: join(directory, "agents", identity) }); return new AgentCore({ session, model: { provider: "mock", model: name }, provider: new MockProvider(responses), ...(tools === undefined ? {} : { tools }) }); };
	const provider: LiteratureProvider = { async search(query) { assert.match(query, /finite-sum/); return [{ sourceId: "doi:fixture", title: "Finite-sum identity", authors: ["Ada Example"], acquisitionUrl: "https://fixture.invalid/fulltext" }]; }, async acquire() { return "Theorem (finite-sum identity). For every positive integer n, the sum of the first n odd integers equals n squared. Proof by induction: the successor step adds 2n+1."; } };
	const factory = (async (context) => { const state = (await new ResearchStore(join(data, "research")).listProjects())[0], source = state === undefined ? undefined : Object.values(state.artifacts).find((item) => item.artifactType === "LITERATURE_SOURCE"); assert.ok(source, "literature must be acquired before tactical Worker construction"); const gate = context.targetGate!, candidateId = "literature-target-candidate", planner = await make("planner", [text({ actions: [{ action: "spawn", tasks: [{ taskId: "literature-target", summary: "Apply acquired theorem", description: "Retrieve and apply the exact acquired literature theorem.", scope: "TARGET", targetClaimId: gate.targetClaimId }] }] }), text({ actions: [{ action: "submit_target_proof", candidateId, targetObligationId: gate.targetObligationId, targetClaimId: gate.targetClaimId }] })]); const worker = await make("worker", [tool("lit-search", "artifact_search", { query: "finite-sum identity", artifactTypes: ["LITERATURE_SOURCE"], limit: 1 }), tool("lit-read", "artifact_read", { artifactId: source!.artifactId }), text({ kind: "candidate", candidate: { candidateId, scope: "TARGET", strategy: "apply exact acquired theorem", content: "The acquired theorem is exactly the target, with matching positive-integer scope." } })], context.tools); const verifier = await make("verifier", [tool("lit-verify-read", "artifact_read", { artifactId: source!.artifactId }), text({ verdict: "CORRECT", feedback: "The exact source establishes the exact target and the scope matches." })], context.tools); return createAgentProofRoles({ planner, researcher: worker, verifier }); }) as ProofApiRoleFactory;
	factory.createAgent = async ({ role, tools }) => { const state = (await new ResearchStore(join(data, "research")).listProjects())[0]; if (role === "research_director") { const target = Object.values(state!.obligations).find((item) => item.status === "OPEN")!; return make(role, [text({ action: "REQUEST_LITERATURE", targetObligationId: target.obligationId, targetClaimId: target.claimId, literatureQuery: "finite-sum identity", reason: "Acquire the exact theorem before attempting the target" })], tools); } if (role === "literature_researcher") return make(role, [text({ literatureClaim: "The sum of the first n odd integers is n squared", assumptions: ["n is a positive integer"], applicable: true, reason: "The theorem exactly matches the target", scopeLimitations: [] })], tools); const source = Object.values(state!.artifacts).find((item) => item.artifactType === "LITERATURE_SOURCE"); if (role === "secondary_auditor" && source !== undefined) return make(role, [tool("lit-audit-read", "artifact_read", { artifactId: source.artifactId }), text({ verdict: "CORRECT", feedback: "Fresh audit inspected the exact acquired source." })], tools); return make(role, [text({ verdict: "CORRECT", feedback: "correct" })], tools); };
	const server = new ProofApiServer({ rootDirectory: data, createRoles: factory, literatureProvider: provider, defaultMaxWorkers: 1, defaultMaxSteps: 3 }); t.after(async () => { await server.stop(); await rm(directory, { recursive: true, force: true }); }); const base = await server.start(); await request(base, "/v1/research/projects", "POST", { projectId: "literature" }); await request(base, "/v1/research/projects/literature/root", "POST", { objective: "For every positive integer n, the sum of the first n odd integers equals n squared." }); await request(base, "/v1/research/projects/literature/start", "POST", { maxCycles: 1 }); const state = await waitProject(base, "literature"), source = Object.values(state.artifacts).find((item: any) => item.artifactType === "LITERATURE_SOURCE") as any; assert.equal(state.status, "PROVED", state.lastError ?? JSON.stringify(state.events)); assert.ok(source); assert.equal(state.artifacts[source.artifactId].authority, "LITERATURE_SOURCE"); assert.ok(state.events.some((item: any) => item.type === "research/literature_completed")); const receipts = Object.values(state.toolEvidenceReceipts) as any[]; for (const role of ["worker", "verifier", "secondary_auditor"]) assert.ok(receipts.some((item) => item.role === role && item.operation === "READ" && item.artifact.artifactId === source.artifactId), `missing exact source read for ${role}`);
});

test("non-default production configuration controls cycle cap, checkpoint cadence, stall turn, concurrency, and role mapping", async (t) => {
	const directory = await mkdtemp(join(tmpdir(), "mrr-config-production-")), data = join(directory, "data"), config = new MathAgentConfigService(join(directory, "math-agent.toml")); await config.load(); await config.update({ research: { maxCycles: 3, checkpointInterval: 2, stallThreshold: 2, structuralProbeBudget: 0, maxActiveObligations: 3 }, proof: { maxWorkers: 1, maxSteps: 2 }, models: { alternate: { provider: "mock", model: "alternate-worker" } }, roles: { worker: { model: "alternate" } } }); let ordinal = 0, captured: MathAgentConfig | undefined;
	const make = async (name: string, responses: readonly MockResponse[], tools?: readonly RuntimeTool[]): Promise<Agent> => { ordinal += 1; const identity = `${name}-${ordinal}`, session = await Session.create({ projectId: identity, sessionId: identity, cwd: directory, directory: join(directory, "agents", identity) }); return new AgentCore({ session, model: { provider: "mock", model: name }, provider: new MockProvider(responses), ...(tools === undefined ? {} : { tools }) }); };
	const factory = (async (context) => { captured = context.config; const planner = await make("planner", [text({ actions: [{ action: "spawn", tasks: [{ taskId: `observation-${ordinal}`, summary: "Bounded attempt", description: "Report an observation without claiming target proof.", scope: "CONTRIBUTION", contributionKind: "STRUCTURAL_OBSERVATION" }] }] }), text({ actions: [{ action: "stop", reason: "no proof" }] })]); const worker = await make(context.config!.models[context.config!.roles.worker.model]!.model, [text({ kind: "observation", content: "No structural mathematical effect was verified.", suggestedNext: "change route" })], context.tools); return createAgentProofRoles({ planner, researcher: worker, verifier: await make("verifier", [text({ verdict: "UNFINISHED", feedback: "no candidate" })], context.tools) }); }) as ProofApiRoleFactory;
	factory.createAgent = async ({ role, config: snapshot, tools }) => { captured = snapshot; assert.equal(role, "research_director"); return make(role, [text({ action: "ATTACK_OBLIGATION", reason: "invalid without target so deterministic fallback selects from configured frontier" })], tools); };
	let server = new ProofApiServer({ rootDirectory: data, createRoles: factory, configService: config }); t.after(async () => { await server.stop(); await rm(directory, { recursive: true, force: true }); }); let base = await server.start(); await request(base, "/v1/research/projects", "POST", { projectId: "configured" }); await request(base, "/v1/research/projects/configured/root", "POST", { objective: "A deliberately unresolved configured target" }); await request(base, "/v1/research/projects/configured/start", "POST", { maxCycles: 20 }); const state = await waitProject(base, "configured");
	assert.equal(state.cycle, 3, "configured maxCycles must cap an HTTP request"); assert.equal(state.checkpoints.length, 1, "checkpointInterval=2 must avoid a cycle-1 checkpoint"); assert.equal(state.decisions[2].action, "CHANGE_ROUTE", "stallThreshold=2 must force a concrete strategic turn on cycle 3"); assert.ok(Object.values(state.routes).some((item: any) => item.status === "ACTIVE")); assert.equal(state.effectiveConfig.research.maxCycles, 3); assert.equal(state.effectiveConfig.proof.maxWorkers, 1); assert.equal(captured!.roles.worker.model, "alternate"); assert.equal(captured!.models.alternate!.model, "alternate-worker"); assert.ok(state.budget.plannerCalls >= 3); assert.ok(Object.values(state.executionTasks).filter((item: any) => item.kind === "PLANNER").every((item: any) => item.status === "COMPLETED"));
	const beforeRestart = { claims: JSON.stringify(state.claims), frontier: (await request(base, "/v1/research/projects/configured/frontier")).frontier, routes: JSON.stringify(state.routes), executionTasks: JSON.stringify(state.executionTasks), budget: JSON.stringify(state.budget), stall: state.cyclesSinceStructuralProgress }; await config.update({ research: { maxCycles: 5 }, proof: { maxWorkers: 2 } }); const newLiveProject = (await request(base, "/v1/research/projects", "POST", { projectId: "configured-c2" })).state; assert.equal(newLiveProject.effectiveConfig.research.maxCycles, 5); assert.equal(newLiveProject.effectiveConfig.proof.maxWorkers, 2); await server.stop(); const reloadedConfig = new MathAgentConfigService(join(directory, "math-agent.toml")); await reloadedConfig.load(); server = new ProofApiServer({ rootDirectory: data, createRoles: factory, configService: reloadedConfig }); base = await server.start(); let restarted = (await request(base, "/v1/research/projects/configured")).state; assert.equal(restarted.effectiveConfig.research.maxCycles, 3, "existing project must retain C1"); assert.equal(restarted.effectiveConfig.proof.maxWorkers, 1, "existing project must retain C1 role/runtime policy"); assert.equal(JSON.stringify(restarted.claims), beforeRestart.claims); assert.deepEqual((await request(base, "/v1/research/projects/configured/frontier")).frontier, beforeRestart.frontier); assert.equal(JSON.stringify(restarted.routes), beforeRestart.routes); assert.equal(JSON.stringify(restarted.executionTasks), beforeRestart.executionTasks); assert.equal(JSON.stringify(restarted.budget), beforeRestart.budget); assert.equal(restarted.cyclesSinceStructuralProgress, beforeRestart.stall); await request(base, "/v1/research/projects/configured/resume", "POST", { maxCycles: 1 }); restarted = await waitProject(base, "configured"); assert.equal(restarted.cycle, 4); assert.equal(captured!.research.maxCycles, 3); assert.equal(captured!.proof.maxWorkers, 1); assert.ok(restarted.budget.plannerCalls > state.budget.plannerCalls); const c2 = (await request(base, "/v1/research/projects/configured-c2")).state; assert.equal(c2.effectiveConfig.research.maxCycles, 5); assert.equal(c2.effectiveConfig.proof.maxWorkers, 2);
});

test("hardened full production E2E resumes a mid-plan crash before new planning and reaches fresh-audited closure", async (t) => {
	const directory = await mkdtemp(join(tmpdir(), "mrr-full-production-e2e-")), data = join(directory, "data"), corpus = join(directory, "corpus"), configPath = join(directory, "math-agent.toml"); await mkdir(corpus); await writeFile(join(corpus, "history.md"), "Historical Lemma H supplies a normalization identity.\nFailed route: descent for the root because a decreasing measure was unavailable."); let config = new MathAgentConfigService(configPath); await config.load(); await config.update({ research: { maxCycles: 20, checkpointInterval: 2, stallThreshold: 2, structuralProbeBudget: 1, maxActiveObligations: 8 }, proof: { maxWorkers: 1, maxSteps: 3 } }); let ordinal = 0;
	const make = async (name: string, responses: readonly MockResponse[], tools?: readonly RuntimeTool[]): Promise<Agent> => { ordinal += 1; const identity = `${name}-${ordinal}`, session = await Session.create({ projectId: identity, sessionId: identity, cwd: directory, directory: join(directory, "agents", identity) }); return new AgentCore({ session, model: { provider: "mock", model: name }, provider: new MockProvider(responses), ...(tools === undefined ? {} : { tools }), maxTurns: 8 }); };
	const tacticalContribution = async (context: Parameters<ProofApiRoleFactory>[0], kind: "LEMMA" | "REDUCTION" | "CASE_SPLIT", draft: Record<string, unknown>) => { const taskId = `e2e-${kind.toLocaleLowerCase()}-${context.targetGate!.targetClaimId}`, project = (await new ResearchStore(join(data, "research")).listProjects())[0], source = project === undefined ? undefined : Object.values(project.artifacts).find((item) => item.artifactType === "CORPUS_SOURCE"), planner = await make("planner", [text({ actions: [{ action: "spawn", tasks: [{ taskId, summary: `Verified ${kind}`, description: `Produce the exact ${kind} contribution.`, scope: "CONTRIBUTION", contributionKind: kind }] }] }), text({ actions: [{ action: "stop", reason: `${kind} contribution complete; target truth is unchanged` }] })]), reductionPrelude = kind === "REDUCTION" && source !== undefined ? [tool(`e2e-compute-${ordinal}`, "controlled_computation", { executable: "node", args: ["-e", "process.stdout.write(String(3*7))"] }), tool(`e2e-source-read-${ordinal}`, "artifact_read", { artifactId: source.artifactId })] : [], worker = await make("worker", [...reductionPrelude, text({ kind: "candidate", candidate: { scope: "CONTRIBUTION", strategy: kind.toLocaleLowerCase(), content: `Exact proof body for ${kind}`, ...(kind === "REDUCTION" && source !== undefined ? { reliedOnArtifactIds: [source.artifactId] } : {}), contribution: draft } })], context.tools), verifierPrelude = kind === "REDUCTION" && source !== undefined ? [tool(`e2e-source-verify-${ordinal}`, "artifact_read", { artifactId: source.artifactId })] : [], verifier = await make("verifier", [...verifierPrelude, text({ verdict: "CORRECT", feedback: `The ${kind} contribution is correct within its stated scope.` })], context.tools); return createAgentProofRoles({ planner, researcher: worker, verifier }); };
	const rootPlanSteps: number[] = [], rootWorkerCalls = new Map<string, number>();
	const resumableConditionalLemma = () => ({
		planner: { async plan(context: { readonly step: number }): Promise<ProofPlan> { rootPlanSteps.push(context.step); if (context.step > 1) return { actions: [{ action: "stop", reason: "The resumed conditional lemma contribution is complete" }] }; return { actions: [{ action: "spawn", tasks: ["A", "B", "C"].map((suffix) => ({ taskId: `mid-plan-${suffix}`, summary: `Mid-plan task ${suffix}`, description: `Execute stable task ${suffix} without changing its identity.`, scope: "CONTRIBUTION" as const, contributionKind: "LEMMA" as const })) }] }; } },
		researcher: { async research(context: ProofResearchContext) { rootWorkerCalls.set(context.task.taskId, (rootWorkerCalls.get(context.task.taskId) ?? 0) + 1); if (context.task.taskId !== "mid-plan-C") return { kind: "observation" as const, content: `${context.task.taskId} completed and was durably recorded.` }; return { kind: "candidate" as const, candidate: { taskId: context.task.taskId, scope: "CONTRIBUTION" as const, strategy: "resumed-conditional-lemma", content: "Under Normalization premise H, E2E reusable lemma L follows.", contribution: { kind: "LEMMA" as const, statement: "E2E reusable lemma L", relationshipToTarget: "Will close child B", claimId: "e2e-new-lemma", assumptions: ["Normalization premise H"], dependencyClaims: [] } } }; } },
		verifier: { async verify(_candidate: ProofCandidate, _context: ProofVerifierContext) { return { verdict: "CORRECT" as const, feedback: "The resumed conditional lemma is valid under its explicit premise." }; } },
	});
	const tacticalTarget = async (context: Parameters<ProofApiRoleFactory>[0], useArtifactId?: string) => { const gate = context.targetGate!, taskId = `e2e-target-${gate.targetClaimId}`, candidateId = `${taskId}-candidate`, planner = await make("planner", [text({ actions: [{ action: "spawn", tasks: [{ taskId, summary: "Close exact target", description: "Prove this exact target and retrieve every relied-on artifact.", scope: "TARGET", targetClaimId: gate.targetClaimId }] }] }), text({ actions: [{ action: "submit_target_proof", candidateId, targetObligationId: gate.targetObligationId, targetClaimId: gate.targetClaimId }] })]), reads = useArtifactId === undefined ? [] : [tool(`worker-search-${ordinal}`, "artifact_search", { query: "E2E reusable lemma", artifactTypes: ["PROMOTED_PROOF"], limit: 1 }), tool(`worker-read-${ordinal}`, "artifact_read", { artifactId: useArtifactId })], worker = await make("worker", [...reads, text({ kind: "candidate", candidate: { candidateId, scope: "TARGET", strategy: useArtifactId === undefined ? "direct" : "reuse promoted E2E lemma", content: `Complete exact proof of ${context.obligation.theorem}` } })], context.tools), verifierReads = useArtifactId === undefined ? [] : [tool(`verifier-read-${ordinal}`, "artifact_read", { artifactId: useArtifactId })], verifier = await make("verifier", [...verifierReads, text({ verdict: "CORRECT", feedback: "The exact target proof and every used artifact were inspected." })], context.tools); return createAgentProofRoles({ planner, researcher: worker, verifier }); };
	const factory = (async (context) => { const state = (await new ResearchStore(join(data, "research")).listProjects())[0]!, theorem = context.obligation.theorem; if (theorem === "Full E2E root theorem") { if (state.claims["e2e-new-lemma"] === undefined) return resumableConditionalLemma(); if (state.claims["Normalization premise H"] === undefined) return tacticalContribution(context, "LEMMA", { kind: "LEMMA", statement: "Normalization premise H", relationshipToTarget: "Discharges the condition on E2E reusable lemma L", claimId: "Normalization premise H", assumptions: [], dependencyClaims: [] }); return tacticalContribution(context, "REDUCTION", { kind: "REDUCTION", statement: "Root reduces to child A and child B", relationshipToTarget: "Exact iff reduction", assumptions: [], dependencyClaims: ["e2e-new-lemma"], childClaims: [{ claimId: "e2e-child-a", statement: "E2E child A" }, { claimId: "e2e-child-b", statement: "E2E child B" }] }); } if (theorem === "E2E child A") return tacticalContribution(context, "CASE_SPLIT", { kind: "CASE_SPLIT", statement: "Child A splits exhaustively", relationshipToTarget: "Exhaustive parity split", assumptions: [], dependencyClaims: [], childClaims: [{ claimId: "e2e-case-even", statement: "E2E even case" }, { claimId: "e2e-case-odd", statement: "E2E odd case" }], coverageScope: "all admissible inputs", coverageAssertion: "Every admissible input is exactly even or odd" }); if (theorem === "E2E child B") { const lemma = Object.values(state.authorityReceipts).find((item) => item.claimId === "e2e-new-lemma")?.artifact; assert.ok(lemma); return tacticalTarget(context, lemma.artifactId); } if (theorem === "E2E even case") { const hasAlternative = Object.values(state.routes).some((route) => route.targetObligationId === context.targetGate!.targetObligationId && route.status === "ACTIVE" && route.family.includes("alternative")); if (hasAlternative) return tacticalTarget(context); const planner = await make("planner", [text({ actions: [{ action: "spawn", tasks: [{ taskId: `stalled-${state.cycle}`, summary: "Test stalled route", description: "Attempt the route without overclaiming.", scope: "CONTRIBUTION", contributionKind: "STRUCTURAL_OBSERVATION" }] }] }), text({ actions: [{ action: "stop", reason: "route remains unresolved" }] })]); return createAgentProofRoles({ planner, researcher: await make("worker", [text({ kind: "observation", content: "This route does not yet close the case.", suggestedNext: "change route family" })], context.tools), verifier: await make("verifier", [text({ verdict: "UNFINISHED", feedback: "no proof candidate" })], context.tools) }); } return tacticalTarget(context); }) as ProofApiRoleFactory;
	factory.createAgent = async ({ role, runId, tools }) => {
		const state = (await new ResearchStore(join(data, "research")).listProjects())[0]!;
		if (role === "corpus_bootstrapper") { if (runId === "consistency-review") return make(role, [text({ frontierEntityKeys: [], warnings: [] })]); return make(role, [text(canonicalBootstrapResponse({ proposals: [{ entityKey: "historical-h", kind: "CLAIM", statement: "Historical Lemma H supplies a normalization identity", dependencyHints: [] }, { entityKey: "historical-failed-descent", kind: "FAILED_ROUTE", statement: "Descent failed for the root", dependencyHints: [], routeFamily: "descent", mechanism: "minimal-counterexample", failureMechanism: "decreasing measure unavailable" }], dependencies: [], warnings: [] }))]); }
		if (role === "research_director") { const open = Object.values(state.obligations).filter((item) => item.status === "OPEN"), order = [state.rootClaimId, "e2e-child-a", "e2e-child-b", "e2e-case-even", "e2e-case-odd"], target = order.flatMap((claimId) => open.filter((item) => item.claimId === claimId))[0] ?? open[0]; if (target === undefined) return make(role, [text({ action: "TRIGGER_SYNTHESIS", reason: "All dependency and coverage blockers are closed" })]); const stalled = target.claimId === "e2e-case-even" && state.cyclesSinceStructuralProgress >= 2; return make(role, [text({ action: stalled ? "CHANGE_ROUTE" : "ATTACK_OBLIGATION", targetObligationId: target.obligationId, targetClaimId: target.claimId, ...(stalled ? { routeFamily: "e2e-alternative-invariant" } : {}), reason: stalled ? "Two unchanged failures require a distinct invariant route" : "Attack the next dependency in the durable research map" })], tools); }
		const source = Object.values(state.artifacts).find((item) => item.artifactType === "CORPUS_SOURCE"), witness = Object.values(state.authorityReceipts).find((item) => item.claimId === "Normalization premise H")?.artifact, required = [source, witness].filter((item): item is NonNullable<typeof item> => item !== undefined);
		if (role === "synthesizer") return make(role, [text({ proof: "The two child obligations and the proved normalization premise close every assumption and case, so the reduction proves the Full E2E root theorem.", usedArtifactIds: required.map((item) => item.artifactId) })], tools);
		if ((role === "verifier" || role === "secondary_auditor") && source !== undefined && witness !== undefined) return make(role, [...required.map((item) => tool(`final-${role}-${item.artifactId}-read`, "artifact_read", { artifactId: item.artifactId })), text({ verdict: "CORRECT", feedback: "Fresh final audit read the exact source and the discharge-witness proof." })], tools);
		throw new Error(`Unexpected E2E role ${role}`);
	};
	let server = new ProofApiServer({ rootDirectory: data, createRoles: factory, configService: config, defaultMaxWorkers: 1, defaultMaxSteps: 3, researchProofFaultAfterWorkerResults: 2 }); t.after(async () => { await server.stop(); await rm(directory, { recursive: true, force: true }); }); let base = await server.start(); await request(base, "/v1/research/projects", "POST", { projectId: "full-e2e" }); await request(base, "/v1/research/projects/full-e2e/root", "POST", { objective: "Full E2E root theorem" }); await request(base, "/v1/research/projects/full-e2e/corpus", "POST", { roots: [corpus] }); await request(base, "/v1/research/projects/full-e2e/corpus/ingest", "POST", {}); await request(base, "/v1/research/projects/full-e2e/bootstrap", "POST", {}); await request(base, "/v1/research/projects/full-e2e/start", "POST", { maxCycles: 4 }); let state = await waitProject(base, "full-e2e"); assert.equal(state.status, "BLOCKED"); assert.equal(state.cycle, 1); assert.deepEqual(rootPlanSteps, [1]); assert.deepEqual(Object.fromEntries(rootWorkerCalls), { "mid-plan-A": 1, "mid-plan-B": 1 }); const runningPlan = Object.values(state.executionPlans).find((item: any) => item.status === "RUNNING") as any; assert.ok(runningPlan); assert.deepEqual(runningPlan.taskIds, ["mid-plan-A", "mid-plan-B", "mid-plan-C"]); assert.equal(Object.values(state.executionTasks).filter((item: any) => item.kind === "WORKER" && item.status === "COMPLETED").length, 2); assert.ok(Object.values(state.executionTasks).some((item: any) => item.kind === "WORKER" && item.logicalTaskId === "mid-plan-C" && item.status === "INTERRUPTED"));
	await server.stop(); config = new MathAgentConfigService(configPath); await config.load(); server = new ProofApiServer({ rootDirectory: data, createRoles: factory, configService: config, defaultMaxWorkers: 1, defaultMaxSteps: 3 }); base = await server.start(); state = (await request(base, "/v1/research/projects/full-e2e")).state; assert.equal(state.cycle, 1); assert.ok(Object.values(state.executionPlans).some((item: any) => item.status === "RUNNING")); await request(base, "/v1/research/projects/full-e2e/resume", "POST", { maxCycles: 1 }); state = await waitProject(base, "full-e2e"); assert.notEqual(state.status, "PROVED"); assert.equal(state.claims[state.rootClaimId].at(-1).status, "OPEN"); assert.equal(state.rootObjectiveContract.statement, "Full E2E root theorem"); assert.deepEqual(state.rootObjectiveContract.allowedAssumptions, []); assert.equal(state.claims["e2e-new-lemma"].at(-1).status, "PROVED"); assert.deepEqual(state.claims["e2e-new-lemma"].at(-1).assumptions, ["Normalization premise H"]); const conditionalReadiness = await request(base, "/v1/research/projects/full-e2e/root-readiness"); assert.equal(conditionalReadiness.ready, false); assert.ok(conditionalReadiness.currentResearchRequiredAssumptions.some((item: any) => item.assumption === "Normalization premise H" && item.status === "UNRESOLVED")); await request(base, "/v1/research/projects/full-e2e/resume", "POST", { maxCycles: 20 }); state = await waitProject(base, "full-e2e");
	assert.equal(state.status, "PROVED", state.lastError ?? JSON.stringify(state.events)); assert.deepEqual(rootPlanSteps.slice(0, 2), [1, 2], "resume must finish the persisted step before the next Planner call"); assert.deepEqual(Object.fromEntries(rootWorkerCalls), { "mid-plan-A": 1, "mid-plan-B": 1, "mid-plan-C": 1 }); assert.ok(Object.values(state.executionPlans).every((item: any) => item.status === "COMPLETED")); assert.equal(state.claims["e2e-new-lemma"].at(-1).status, "PROVED"); assert.deepEqual(state.claims["e2e-new-lemma"].at(-1).assumptions, ["Normalization premise H"]); assert.equal(state.claims["Normalization premise H"].at(-1).status, "PROVED"); assert.ok(Object.values(state.artifacts).some((item: any) => item.artifactType === "COMPUTATION_RESULT")); assert.ok(state.decisions.some((item: any) => item.action === "CHANGE_ROUTE" && item.routeFamily === "e2e-alternative-invariant")); assert.ok(Object.values(state.routes).some((route: any) => route.family === "e2e-alternative-invariant")); assert.ok(Object.values(state.routes).some((route: any) => route.family === "descent" && route.status === "FAILED")); assert.ok(state.finalProofArtifact); assert.equal(state.artifacts[state.finalProofArtifact.artifactId].artifactType, "FINAL_PROOF"); const lemma = (Object.values(state.authorityReceipts) as any[]).find((item: any) => item.claimId === "e2e-new-lemma")!.artifact, witness = (Object.values(state.authorityReceipts) as any[]).find((item: any) => item.claimId === "Normalization premise H")!.artifact, source = Object.values(state.artifacts).find((item: any) => item.artifactType === "CORPUS_SOURCE") as any, receipts = Object.values(state.toolEvidenceReceipts) as any[]; assert.ok(receipts.some((item) => item.role === "worker" && item.operation === "READ" && item.artifact.artifactId === lemma.artifactId)); assert.ok(receipts.some((item) => item.role === "verifier" && item.operation === "READ" && item.artifact.artifactId === lemma.artifactId)); assert.ok(receipts.some((item) => item.role === "verifier" && item.operation === "READ" && item.artifact.artifactId === source.artifactId)); assert.ok(receipts.some((item) => item.role === "secondary_auditor" && item.operation === "READ" && item.artifact.artifactId === source.artifactId)); assert.ok(receipts.some((item) => item.role === "secondary_auditor" && item.operation === "READ" && item.artifact.artifactId === witness.artifactId)); assert.deepEqual(state.artifacts[state.finalProofArtifact.artifactId].metadata.usedArtifactIds, [source.artifactId, witness.artifactId]); assert.ok(state.bootstrapReports[0].createdRouteIds.length === 1); assert.ok(Object.values(state.coverage).every((item: any) => item.disposition === "CLOSED"));
	const historicalFinal = state.finalProofArtifact, historicalBody = (await new ResearchStore(join(data, "research")).resolveArtifact("full-e2e", historicalFinal)).body, cycleBeforeRevocation = state.cycle;
	state = (await request(base, "/v1/research/projects/full-e2e/invalidate", "POST", { claimId: "Normalization premise H", reason: "production revocation test" })).state; assert.notEqual(state.status, "PROVED"); assert.equal(state.claims["Normalization premise H"].at(-1).status, "INVALIDATED"); assert.equal(state.claims[state.rootClaimId].at(-1).status, "NEEDS_REVALIDATION"); assert.equal(state.currentFinalProofAuthority.status, "STALE"); assert.equal((await new ResearchStore(join(data, "research")).resolveArtifact("full-e2e", historicalFinal)).body, historicalBody); assert.ok(Object.values(state.obligations).some((item: any) => item.claimId === state.rootClaimId && item.status === "OPEN")); const staleReadiness = await request(base, "/v1/research/projects/full-e2e/root-readiness"); assert.equal(staleReadiness.ready, false); assert.ok(staleReadiness.diagnostics.some((item: any) => item.code === "ASSUMPTION_DISCHARGE_STALE")); const resultAfterRevocation = await request(base, "/v1/research/projects/full-e2e/result"); assert.notEqual(resultAfterRevocation.status, "PROVED"); assert.equal(resultAfterRevocation.finalProofArtifact, undefined); assert.equal(resultAfterRevocation.historicalFinalProof.status, "STALE");
	await server.stop(); config = new MathAgentConfigService(configPath); await config.load(); server = new ProofApiServer({ rootDirectory: data, createRoles: factory, configService: config, defaultMaxWorkers: 1, defaultMaxSteps: 3 }); base = await server.start(); state = (await request(base, "/v1/research/projects/full-e2e")).state; assert.notEqual(state.status, "PROVED"); assert.equal(state.currentFinalProofAuthority.status, "STALE"); assert.ok(Object.values(state.obligations).some((item: any) => item.claimId === state.rootClaimId && item.status === "OPEN")); await request(base, "/v1/research/projects/full-e2e/resume", "POST", { maxCycles: 1 }); state = await waitProject(base, "full-e2e"); assert.ok(state.cycle > cycleBeforeRevocation, "revoked production project must resume research");
});

test("research formalization constructs configured role but cannot pass without the authoritative process gate", async (t) => {
	const directory = await mkdtemp(join(tmpdir(), "mrr-formal-production-")), data = join(directory, "data"), config = new MathAgentConfigService(join(directory, "math-agent.toml")); await config.load(); await config.update({ formalization: { enabled: true, command: "definitely-missing-lean" }, roles: { formalizer: { model: "mock", enabled: true }, synthesizer: { model: "mock", enabled: true } } }); let ordinal = 0, formalizerInvoked = false;
	const make = async (name: string, responses: readonly MockResponse[], tools?: readonly RuntimeTool[]): Promise<Agent> => { ordinal += 1; const identity = `${name}-${ordinal}`, session = await Session.create({ projectId: identity, sessionId: identity, cwd: directory, directory: join(directory, "agents", identity) }); return new AgentCore({ session, model: { provider: "mock", model: name }, provider: new MockProvider(responses), ...(tools === undefined ? {} : { tools }) }); };
	const factory = (async (context) => { const gate = context.targetGate!, taskId = "formal-target", candidateId = `${taskId}-candidate`, planner = await make("planner", [text({ actions: [{ action: "spawn", tasks: [{ taskId, summary: "Informal exact target proof", description: "Prove the exact target.", scope: "TARGET", targetClaimId: gate.targetClaimId }] }] }), text({ actions: [{ action: "submit_target_proof", candidateId, targetObligationId: gate.targetObligationId, targetClaimId: gate.targetClaimId }] })]); return createAgentProofRoles({ planner, researcher: await make("worker", [text({ kind: "candidate", candidate: { candidateId, scope: "TARGET", strategy: "direct", content: "True has constructor True.intro." } })], context.tools), verifier: await make("verifier", [text({ verdict: "CORRECT", feedback: "The informal target proof is valid." })], context.tools) }); }) as ProofApiRoleFactory;
	factory.createAgent = async ({ role, tools }) => { if (role === "research_director") return make(role, [text({ action: "ATTACK_OBLIGATION", reason: "deterministic fallback fills exact target" })], tools); if (role === "synthesizer") return make(role, [text({ proof: "True follows by its constructor.", usedArtifactIds: [] })], tools); if (role === "formalizer") { formalizerInvoked = true; return make(role, [text({ lean: "theorem e2e_formal : True := by\n  trivial", notes: "Untrusted draft for process verification" })], tools); } return make(role, [text({ verdict: "CORRECT", feedback: "Fresh audit accepts." })], tools); };
	const server = new ProofApiServer({ rootDirectory: data, createRoles: factory, configService: config, defaultMaxWorkers: 1, defaultMaxSteps: 3 }); t.after(async () => { await server.stop(); await rm(directory, { recursive: true, force: true }); }); const base = await server.start(); await request(base, "/v1/research/projects", "POST", { projectId: "formal" }); await request(base, "/v1/research/projects/formal/root", "POST", { objective: "theorem e2e_formal : True := by\n  sorry" }); await request(base, "/v1/research/projects/formal/start", "POST", { maxCycles: 1 }); let state = await waitProject(base, "formal"); assert.equal(state.status, "PROVED"); state = (await request(base, "/v1/research/projects/formal/synthesis", "POST", {})).state; assert.ok(state.finalProofArtifact); const formal = await request(base, "/v1/research/projects/formal/formalization", "POST", { mode: "formalize_existing" }); assert.equal(formal.status, "BLOCKED_FORMAL"); assert.equal(formalizerInvoked, true); assert.match(formal.feedback, /definitely-missing-lean|ENOENT|not recognized|spawn/iu); assert.ok(Object.values(formal.state.artifacts).some((item: any) => item.artifactType === "LEAN_SOURCE")); assert.ok(Object.values(formal.state.artifacts).some((item: any) => item.artifactType === "LEAN_CERTIFICATE")); assert.ok(!Object.values(formal.state.artifacts).some((item: any) => item.artifactType === "FORMAL_PROOF"));
});

function text(value: unknown): MockResponse { return { events: [{ type: "text_delta", text: typeof value === "string" ? value : JSON.stringify(value) }, { type: "complete", stopReason: "end_turn" }] }; }
function canonicalBootstrapResponse(value: { proposals: readonly Record<string, unknown>[]; dependencies: readonly Record<string, unknown>[]; warnings: readonly string[] }): unknown { return { ...value, proposals: value.proposals.map((proposal) => ({ targetHint: "", routeFamily: "", mechanism: "", failureMechanism: "", cases: [], ...proposal })), dependencies: value.dependencies.map((dependency) => ({ ...dependency, confidenceScore: null })) }; }
function tool(callId: string, name: string, args: Record<string, unknown>): MockResponse { return { events: [{ type: "tool_call_delta", callId, name, argumentsDelta: JSON.stringify(args) }, { type: "complete", stopReason: "tool_calls" }] }; }
async function request(base: string, path: string, method = "GET", body?: unknown): Promise<any> { const response = await fetch(`${base}${path}`, { method, headers: { "content-type": "application/json" }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) }); const value = await response.json(); assert.ok(response.ok, JSON.stringify(value)); return value; }
async function waitProject(base: string, projectId: string): Promise<any> { for (let index = 0; index < 1_000; index += 1) { const value = await request(base, `/v1/research/projects/${projectId}`); if (!value.active) return value.state; await new Promise((resolve) => setTimeout(resolve, 10)); } throw new Error("research run did not finish"); }
