import { strict as assert } from "node:assert";
import { mkdtemp, mkdir, rm, unlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test, type TestContext } from "node:test";
import {
	activeAuthorityForClaim, assessAssumption, CorpusService, inspectResearchState, ResearchRuntime, ResearchStateReducer, ResearchStore,
	ProofApiServer, RootClosureService, rootSynthesisReadiness, stableId,
	type ArtifactRef, type AuthorityReceipt, type FinalAuditor, type ResearchProjectState, type TrustReceipt,
} from "../src/index.js";

async function fixture(t: TestContext, rootStatement = "T") {
	const directory = await mkdtemp(join(tmpdir(), "mrr-authority-revocation-")); t.after(async () => rm(directory, { recursive: true, force: true }));
	const store = new ResearchStore(join(directory, "data")); await store.create("p", "p"); const runtime = new ResearchRuntime({ store, proofRunner: async (request) => { const now = new Date().toISOString(); return { obligationId: request.obligation.obligationId, targetClaimId: request.targetClaimId, targetStatus: "TARGET_UNRESOLVED", contributions: [], routeObservations: [], executionReceipt: { executionReceiptId: stableId("execution", request.logicalJobId), logicalJobId: request.logicalJobId, attemptId: request.attemptId, taskIds: [], evidenceReceiptIds: [], startedAt: now, completedAt: now }, feedback: "revalidation remains open" }; } }); await runtime.setRootObjective("p", rootStatement, []);
	const state = await store.read("p"); return { directory, store, runtime, reducer: new ResearchStateReducer(store), root: state.rootClaimId as string };
}

function receipt(claimId: string, candidate: ArtifactRef, profile: string, evidenceInspected: readonly ArtifactRef[] = []): TrustReceipt { return { receiptId: stableId("receipt", claimId, candidate.artifactId, profile), claimId, candidate, verifierProfile: profile, evidenceInspected, verifierReadEvidence: evidenceInspected, verdict: "CORRECT", independentContext: true, stale: false, createdAt: new Date().toISOString() }; }

async function prove(store: ResearchStore, reducer: ResearchStateReducer, claimId: string, statement: string, request: { readonly assumptions?: readonly string[]; readonly dependencies?: readonly string[]; readonly evidence?: readonly ArtifactRef[]; readonly root?: boolean; readonly slot?: string } = {}): Promise<{ readonly state: ResearchProjectState; readonly authority: AuthorityReceipt; readonly source: ArtifactRef }> {
	const source = await store.putArtifact("p", { artifactType: "WORKER_CANDIDATE", body: `Proof of ${statement} (${request.slot ?? claimId})`, provenance: "authority-revocation-test", references: request.evidence ?? [] }), receipts = [receipt(claimId, source, `${request.slot ?? claimId}-primary`, request.evidence), ...(request.root ? [receipt(claimId, source, `${request.slot ?? claimId}-secondary`, request.evidence)] : [])];
	const state = (await reducer.apply({ projectId: "p", cycleId: stableId("cycle", request.slot ?? claimId), logicalJobId: stableId("job", request.slot ?? claimId), effectSlot: request.slot ?? claimId, outcome: { type: claimId === "H" ? "NEW_LEMMA" : "PROVED_CLAIM", claimId, statement, candidate: source, receipts, dependencies: request.dependencies ?? [], assumptions: request.assumptions ?? [] } })).state, latest = state.claims[claimId]?.at(-1), authority = latest === undefined ? undefined : activeAuthorityForClaim(state, claimId, latest.revision); assert.ok(authority); return { state, authority, source };
}

function closure(store: ResearchStore, witness?: ArtifactRef, observations?: { manifestSawWitness: boolean; auditSawWitness: boolean }): RootClosureService {
	const primary: FinalAuditor = { async audit() { return { verdict: "CORRECT", feedback: "primary accepted", profile: "primary" }; } }, final: FinalAuditor = { async audit(request) { if (witness !== undefined) { assert.ok(request.dependencyBodies[witness.artifactId]); if (observations !== undefined) observations.auditSawWitness = true; } return { verdict: "CORRECT", feedback: "final inspected exact dependencies", profile: "final", evidenceInspected: witness === undefined ? [] : [witness] }; } };
	return new RootClosureService(store, { async synthesize(manifest, bodies) { if (witness !== undefined) { assert.ok(manifest.assumptionDischarges.some((item) => item.witnessArtifactId === witness.artifactId)); assert.ok(manifest.proofArtifacts.some((item) => item.artifactId === witness.artifactId)); assert.ok(bodies[witness.artifactId]); if (observations !== undefined) observations.manifestSawWitness = true; } return { proof: "Final unconditional proof of T", usedArtifactIds: manifest.proofArtifacts.map((item) => item.artifactId), theoremStatement: manifest.rootObjective, assumptions: manifest.assumptions }; } }, primary, final);
}

test("exact discharge supersession immediately stales the dependent authority", async (t) => {
	const { store, reducer, root } = await fixture(t), h1 = await prove(store, reducer, "H", "H", { slot: "supersession-h-v1" }), target = await prove(store, reducer, root, "T", { assumptions: ["H"], root: true, slot: "supersession-t-v1" });
	assert.equal(target.state.authorityValidation[target.authority.authorityReceiptId]?.status, "ACTIVE");
	const h2 = await prove(store, reducer, "H", "H", { slot: "supersession-h-v2" });
	assert.equal(h2.state.authorityValidation[h1.authority.authorityReceiptId]?.status, "SUPERSEDED");
	assert.equal(h2.state.authorityValidation[h2.authority.authorityReceiptId]?.status, "ACTIVE");
	assert.equal(h2.state.authorityValidation[target.authority.authorityReceiptId]?.status, "STALE");
	assert.equal(h2.state.claims[root]?.at(-1)?.status, "NEEDS_REVALIDATION");
	assert.equal(inspectResearchState(h2.state).valid, true);
	await assert.doesNotReject(store.read("p"));
});

test("ordinary exact dependency supersession requires a new dependent authority for the new revision", async (t) => {
	const { store, reducer, root } = await fixture(t, "Ordinary T"), l1 = await prove(store, reducer, "L", "L", { slot: "ordinary-supersession-l-v1" }), t1 = await prove(store, reducer, root, "Ordinary T", { dependencies: ["L"], root: true, slot: "ordinary-supersession-t-v1" }), historicalReceipt = structuredClone(t1.authority);
	assert.equal(t1.authority.dependencyRevisions.L, l1.authority.claimRevision);
	const l2 = await prove(store, reducer, "L", "L", { slot: "ordinary-supersession-l-v2" }), stale = l2.state;
	assert.equal(stale.authorityValidation[l1.authority.authorityReceiptId]?.status, "SUPERSEDED");
	assert.equal(stale.authorityValidation[l2.authority.authorityReceiptId]?.status, "ACTIVE");
	assert.equal(stale.authorityValidation[t1.authority.authorityReceiptId]?.status, "STALE");
	assert.equal(stale.claims[root]?.at(-1)?.status, "NEEDS_REVALIDATION");
	assert.equal(inspectResearchState(stale).valid, true);
	const t2 = await prove(store, reducer, root, "Ordinary T", { dependencies: ["L"], root: true, slot: "ordinary-supersession-t-v2" });
	assert.equal(t2.authority.dependencyRevisions.L, l2.authority.claimRevision);
	assert.notEqual(t2.authority.authorityReceiptId, t1.authority.authorityReceiptId);
	assert.equal(t2.state.authorityValidation[t1.authority.authorityReceiptId]?.status, "STALE");
	assert.deepEqual(t2.state.authorityReceipts[t1.authority.authorityReceiptId], historicalReceipt);
	assert.equal(inspectResearchState(t2.state).valid, true);
});

test("supersession propagates transitively through discharge and ordinary exact edges to root truth", async (t) => {
	const { store, runtime, reducer, root } = await fixture(t, "Transitive T"), h1 = await prove(store, reducer, "H", "H", { slot: "transitive-h-v1" }), l = await prove(store, reducer, "L", "L", { assumptions: ["H"], slot: "transitive-l" }), r = await prove(store, reducer, "R", "R", { dependencies: ["L"], slot: "transitive-r" }); await prove(store, reducer, root, "Transitive T", { dependencies: ["R"], root: true, slot: "transitive-root" });
	const proved = await closure(store, h1.authority.artifact).synthesizeAndAudit("p"), provedRoot = proved.claims[root]?.at(-1), rootAuthority = provedRoot === undefined ? undefined : activeAuthorityForClaim(proved, root, provedRoot.revision); assert.equal(proved.status, "PROVED"); assert.equal(proved.currentFinalProofAuthority?.status, "ACTIVE"); assert.ok(rootAuthority);
	const h2 = await prove(store, reducer, "H", "H", { slot: "transitive-h-v2" }), stale = h2.state;
	for (const claimId of ["L", "R", root]) assert.equal(stale.claims[claimId]?.at(-1)?.status, "NEEDS_REVALIDATION", `${claimId} must be reopened`);
	for (const authority of [l.authority, r.authority, rootAuthority]) assert.equal(stale.authorityValidation[authority.authorityReceiptId]?.status, "STALE");
	assert.notEqual(stale.status, "PROVED"); assert.equal(stale.currentFinalProofAuthority?.status, "STALE"); assert.equal(rootSynthesisReadiness(stale).ready, false); assert.ok(Object.values(stale.obligations).some((item) => item.claimId === root && item.status === "OPEN")); assert.equal(inspectResearchState(stale).valid, true); await assert.doesNotReject(store.read("p"));
	const supersessionEvent = stale.events.find((item) => item.type === "research/authority_revoked" && item.detail.dependentAuthorityReceiptId === l.authority.authorityReceiptId); assert.deepEqual(supersessionEvent?.detail.supersededAuthorityReceiptIds, [h1.authority.authorityReceiptId]); assert.equal(supersessionEvent?.detail.newAuthorityReceiptId, h2.authority.authorityReceiptId);
	const counts = { revisions: stale.claims[root]?.length, obligations: Object.keys(stale.obligations).length, revocations: stale.events.filter((item) => item.type === "research/authority_revoked").length }, repeated = await prove(store, reducer, "H", "H", { slot: "transitive-h-v2" }); assert.deepEqual({ revisions: repeated.state.claims[root]?.length, obligations: Object.keys(repeated.state.obligations).length, revocations: repeated.state.events.filter((item) => item.type === "research/authority_revoked").length }, counts);
	const resumed = await runtime.run("p", 1); assert.notEqual(resumed.status, "PROVED"); assert.ok(resumed.cycle > stale.cycle || resumed.events.length > stale.events.length);
});

test("structural authority with an exact dependency becomes stale on supersession", async (t) => {
	const { store, reducer } = await fixture(t, "Structural supersession"), h1 = await prove(store, reducer, "H", "H", { slot: "structural-supersession-h-v1" }); await store.transaction("p", (draft) => { const now = new Date().toISOString(); (draft as any).claims.R = [{ claimId: "R", revision: 1, statement: "R", role: "LEMMA", status: "OPEN", dependencies: [], evidenceRefs: [], auditRefs: [], assumptions: [], provenance: "test", createdAt: now }]; });
	const proof = await store.putArtifact("p", { artifactType: "WORKER_CANDIDATE", body: "R reduces to A using exact H", provenance: "structural-supersession" }), reduced = await reducer.apply({ projectId: "p", cycleId: "structural-supersession", logicalJobId: "structural-supersession", effectSlot: "reduction", outcome: { type: "REDUCTION", claimId: "R", childClaims: [{ claimId: "A", statement: "A" }], proof, receipts: [receipt("R", proof, "structural-supersession")], assumptions: [], dependencies: ["H"], scope: "all inputs" } }), authority = activeAuthorityForClaim(reduced.state, "R", reduced.state.claims.R?.at(-1)?.revision); assert.equal(authority?.dependencyRevisions.H, h1.authority.claimRevision);
	const h2 = await prove(store, reducer, "H", "H", { slot: "structural-supersession-h-v2" }); assert.equal(h2.state.authorityValidation[authority!.authorityReceiptId]?.status, "STALE"); assert.equal(h2.state.claims.R?.at(-1)?.status, "NEEDS_REVALIDATION"); assert.ok(Object.values(h2.state.obligations).some((item) => item.claimId === "R" && item.status === "OPEN")); assert.equal(inspectResearchState(h2.state).valid, true);
});

test("supersession-revoked project and stale final proof survive HTTP server restart", async (t) => {
	const directory = await mkdtemp(join(tmpdir(), "mrr-supersession-restart-")), data = join(directory, "data"), store = new ResearchStore(join(data, "research")); await store.create("p", "p"); const runtime = new ResearchRuntime({ store, proofRunner: async (request) => { const now = new Date().toISOString(); return { obligationId: request.obligation.obligationId, targetClaimId: request.targetClaimId, targetStatus: "TARGET_UNRESOLVED", contributions: [], routeObservations: [], executionReceipt: { executionReceiptId: stableId("execution", request.logicalJobId), logicalJobId: request.logicalJobId, attemptId: request.attemptId, taskIds: [], evidenceReceiptIds: [], startedAt: now, completedAt: now }, feedback: "still open" }; } }); await runtime.setRootObjective("p", "Restart T", []); const root = (await store.read("p")).rootClaimId as string, reducer = new ResearchStateReducer(store), h1 = await prove(store, reducer, "H", "H", { slot: "restart-h-v1" }); await prove(store, reducer, root, "Restart T", { assumptions: ["H"], root: true, slot: "restart-root" }); await closure(store, h1.authority.artifact).synthesizeAndAudit("p");
	let server = new ProofApiServer({ rootDirectory: data, createRoles: async () => { throw new Error("unused in restart read test"); } }); t.after(async () => { await server.stop(); await rm(directory, { recursive: true, force: true }); }); let base = await server.start(); await prove(store, reducer, "H", "H", { slot: "restart-h-v2" }); let result = await fetch(`${base}/v1/research/projects/p/result`).then((response) => response.json()) as any; assert.notEqual(result.status, "PROVED"); assert.equal(result.currentFinalProofAuthority.status, "STALE"); assert.equal(result.finalProofArtifact, undefined); assert.ok(result.frontier.length > 0);
	await server.stop(); server = new ProofApiServer({ rootDirectory: data, createRoles: async () => { throw new Error("unused in restart read test"); } }); base = await server.start(); result = await fetch(`${base}/v1/research/projects/p/result`).then((response) => response.json()) as any; assert.notEqual(result.status, "PROVED"); assert.equal(result.currentFinalProofAuthority.status, "STALE"); assert.equal(result.finalProofArtifact, undefined); assert.ok(result.frontier.length > 0); const audit = await fetch(`${base}/v1/research/projects/p/audit`).then((response) => response.json()) as any; assert.equal(audit.invariants.valid, true); assert.equal(audit.rootReadiness.ready, false);
});

test("discharge provenance reaches synthesis/final audit and reverse revocation preserves stale final history", async (t) => {
	const { store, runtime, reducer, root } = await fixture(t), h = await prove(store, reducer, "H", "H", { slot: "h-v1" }), target = await prove(store, reducer, root, "T", { assumptions: ["H"], root: true, slot: "t-v1" });
	assert.deepEqual(target.state.rootObjectiveContract?.allowedAssumptions, []); const rootReceipt = target.authority, edge = rootReceipt.assumptionDischarges.find((item) => item.assumption === "H"); assert.ok(edge); assert.equal(edge.witnessClaimId, "H"); assert.equal(edge.witnessClaimRevision, h.authority.claimRevision); assert.equal(edge.witnessAuthorityReceiptId, h.authority.authorityReceiptId); assert.equal(edge.witnessArtifactId, h.authority.artifact.artifactId); assert.equal(edge.acceptedEffectId, h.authority.effectId);
	const assessment = assessAssumption(target.state, " H "); assert.equal(assessment.status, "DISCHARGED"); if (assessment.status === "DISCHARGED") assert.equal(assessment.witnesses[0]?.authorityReceiptId, h.authority.authorityReceiptId); const ready = rootSynthesisReadiness(target.state); assert.equal(ready.ready, true); assert.ok(ready.closureRequiredAssumptions.some((item) => item.assumption === "H" && item.witnesses[0]?.proofArtifactId === h.authority.artifact.artifactId));
	const observations = { manifestSawWitness: false, auditSawWitness: false }, proved = await closure(store, h.authority.artifact, observations).synthesizeAndAudit("p"); assert.equal(observations.manifestSawWitness, true); assert.equal(observations.auditSawWitness, true); assert.equal(proved.status, "PROVED"); assert.equal(proved.currentFinalProofAuthority?.status, "ACTIVE"); const historical = proved.finalProofArtifact as ArtifactRef, historicalBody = (await store.resolveArtifact("p", historical)).body, oldWitnessRevision = h.authority.claimRevision;
	const invalidated = await reducer.invalidate("p", "H", "fresh audit found a gap in H"); assert.equal(invalidated.claims.H?.at(-1)?.status, "INVALIDATED"); assert.equal(invalidated.claims[root]?.at(-1)?.status, "NEEDS_REVALIDATION"); assert.notEqual(invalidated.status, "PROVED"); assert.equal(invalidated.currentFinalProofAuthority?.status, "STALE"); assert.equal((await store.resolveArtifact("p", historical)).body, historicalBody); assert.ok(invalidated.finalProofHistory.some((item) => item.artifact.artifactId === historical.artifactId && item.status === "STALE")); assert.ok(rootSynthesisReadiness(invalidated).diagnostics.some((item) => item.code === "ASSUMPTION_DISCHARGE_STALE" && item.previousWitness?.includes(`H@${oldWitnessRevision}`))); assert.ok(Object.values(invalidated.obligations).some((item) => item.claimId === root && item.status === "OPEN")); assert.ok(invalidated.events.some((item) => item.type === "research/assumption_discharge_invalidated"));
	const counts = { revisions: invalidated.claims.H?.length, obligations: Object.keys(invalidated.obligations).length, revocations: invalidated.events.filter((item) => item.type === "research/authority_revoked").length }, repeated = await reducer.invalidate("p", "H", "fresh audit found a gap in H"); assert.deepEqual({ revisions: repeated.claims.H?.length, obligations: Object.keys(repeated.obligations).length, revocations: repeated.events.filter((item) => item.type === "research/authority_revoked").length }, counts);
	const resumed = await runtime.run("p", 1); assert.notEqual(resumed.status, "PROVED"); assert.ok(resumed.cycle > invalidated.cycle || resumed.events.length > invalidated.events.length, "revoked project must be runnable");
	const h2 = await prove(store, reducer, "H", "H", { slot: "h-v2" }), afterH2 = h2.state; assert.notEqual(afterH2.claims[root]?.at(-1)?.status, "PROVED", "new H authority must not silently revive historical T authority"); const t2 = await prove(store, reducer, root, "T", { assumptions: ["H"], root: true, slot: "t-v2" }), t2Edge = t2.authority.assumptionDischarges.find((item) => item.assumption === "H"); assert.equal(t2Edge?.witnessClaimRevision, h2.authority.claimRevision); assert.notEqual(t2Edge?.witnessClaimRevision, oldWitnessRevision); assert.equal(inspectResearchState(t2.state).valid, true);
});

test("exact normalized statement matching rejects an unrelated claim whose id resembles the assumption", async (t) => {
	const { store, reducer, root } = await fixture(t); await prove(store, reducer, "H", "Unrelated proposition K", { slot: "unrelated" }); const candidate = await store.putArtifact("p", { artifactType: "WORKER_CANDIDATE", body: "H implies T", provenance: "mismatch" });
	assert.equal(assessAssumption(await store.read("p"), "H").status, "UNRESOLVED"); await assert.rejects(reducer.apply({ projectId: "p", cycleId: "mismatch", logicalJobId: "mismatch", effectSlot: "root", outcome: { type: "PROVED_CLAIM", claimId: root, statement: "T", candidate, receipts: [receipt(root, candidate, "primary"), receipt(root, candidate, "secondary")], dependencies: [], assumptions: ["H"] } }), /ROOT_ASSUMPTION_ESCALATION/);
});

test("synthesizer and final auditor fail closed when proof(H) is omitted", async (t) => {
	const { store, reducer, root } = await fixture(t), h = await prove(store, reducer, "H", "H", { slot: "h" }); await prove(store, reducer, root, "T", { assumptions: ["H"], root: true, slot: "t" }); const auditor: FinalAuditor = { async audit() { return { verdict: "CORRECT", feedback: "opaque acceptance", profile: "opaque" }; } };
	const missingSynthesis = new RootClosureService(store, { async synthesize(manifest) { return { proof: "T", usedArtifactIds: manifest.proofArtifacts.filter((item) => item.artifactId !== h.authority.artifact.artifactId).map((item) => item.artifactId) }; } }, auditor, auditor); await assert.rejects(missingSynthesis.synthesizeAndAudit("p"), /SYNTHESIS_DISCHARGE_EVIDENCE_MISSING/);
	const missingAudit = new RootClosureService(store, { async synthesize(manifest) { return { proof: "T", usedArtifactIds: manifest.proofArtifacts.map((item) => item.artifactId) }; } }, auditor, auditor), state = await missingAudit.synthesizeAndAudit("p"); assert.notEqual(state.status, "PROVED"); assert.equal(state.currentFinalProofAuthority, undefined); assert.ok(Object.values(state.obligations).some((item) => item.causalReason?.includes("audit")));
});

test("ordinary and structural authorities both propagate downstream invalidation", async (t) => {
	const ordinary = await fixture(t, "Ordinary T"), l = await prove(ordinary.store, ordinary.reducer, "L", "L", { slot: "l" }); await prove(ordinary.store, ordinary.reducer, ordinary.root, "Ordinary T", { dependencies: ["L"], root: true, slot: "ordinary-root" }); const proved = await closure(ordinary.store).synthesizeAndAudit("p"); assert.equal(proved.currentFinalProofAuthority?.status, "ACTIVE"); const invalid = await ordinary.reducer.invalidate("p", "L", "L proof failed re-audit"); assert.equal(invalid.claims[ordinary.root]?.at(-1)?.status, "NEEDS_REVALIDATION"); assert.notEqual(invalid.status, "PROVED"); assert.equal(invalid.currentFinalProofAuthority?.status, "STALE"); assert.equal(invalid.authorityValidation[l.authority.authorityReceiptId]?.status, "INVALIDATED");

	const structural = await fixture(t, "Structural T"), h = await prove(structural.store, structural.reducer, "H", "H", { slot: "structural-h" }); await structural.store.transaction("p", (draft) => { const now = new Date().toISOString(); (draft as any).claims.R = [{ claimId: "R", revision: 1, statement: "R", role: "LEMMA", status: "OPEN", dependencies: [], evidenceRefs: [], auditRefs: [], assumptions: [], provenance: "test", createdAt: now }]; }); const proof = await structural.store.putArtifact("p", { artifactType: "WORKER_CANDIDATE", body: "Under H, R reduces to A", provenance: "structural" }), result = await structural.reducer.apply({ projectId: "p", cycleId: "structural", logicalJobId: "structural", effectSlot: "reduction", outcome: { type: "REDUCTION", claimId: "R", childClaims: [{ claimId: "A", statement: "A" }], proof, receipts: [receipt("R", proof, "structural")], assumptions: ["H"], dependencies: [], scope: "all inputs" } }), reductionAuthority = activeAuthorityForClaim(result.state, "R", result.state.claims.R?.at(-1)?.revision); assert.ok(reductionAuthority?.assumptionDischarges.some((item) => item.witnessAuthorityReceiptId === h.authority.authorityReceiptId)); const structuralInvalid = await structural.reducer.invalidate("p", "H", "withdraw structural premise"); assert.equal(structuralInvalid.claims.R?.at(-1)?.status, "NEEDS_REVALIDATION"); assert.equal(structuralInvalid.authorityValidation[reductionAuthority!.authorityReceiptId]?.status, "STALE");
});

test("corpus hash invalidation flows through a discharge witness to root and final proof", async (t) => {
	const { directory, store, reducer, root } = await fixture(t), corpusDirectory = join(directory, "corpus"); await mkdir(corpusDirectory); const sourcePath = join(corpusDirectory, "source.md"); await writeFile(sourcePath, "authoritative source v1\n"); const corpus = new CorpusService(store); await corpus.attach("p", [corpusDirectory]); const first = await corpus.ingest("p", "VERIFIED_CURRENT"), source = Object.values(first.state.corpus)[0] as ArtifactRef, h = await prove(store, reducer, "H", "H", { slot: "source-h", evidence: [source] }); await prove(store, reducer, root, "T", { assumptions: ["H"], root: true, slot: "source-root" }); await closure(store, h.authority.artifact).synthesizeAndAudit("p"); await writeFile(sourcePath, "authoritative source v2 changed\n"); const changed = await corpus.ingest("p", "VERIFIED_CURRENT"); assert.equal(changed.changed.length, 1); assert.equal(changed.state.claims.H?.at(-1)?.status, "INVALIDATED"); assert.equal(changed.state.claims[root]?.at(-1)?.status, "NEEDS_REVALIDATION"); assert.notEqual(changed.state.status, "PROVED"); assert.equal(changed.state.currentFinalProofAuthority?.status, "STALE");
});

test("missing discharge proof body revokes current authority when readiness detects it", async (t) => {
	const { store, reducer, root } = await fixture(t), h = await prove(store, reducer, "H", "H", { slot: "missing-body-h" }); await prove(store, reducer, root, "T", { assumptions: ["H"], root: true, slot: "missing-body-root" }); await closure(store, h.authority.artifact).synthesizeAndAudit("p"); const metadata = (await store.read("p")).artifacts[h.authority.artifact.artifactId]; assert.ok(metadata); await unlink(metadata.bodyPath); const readiness = await closure(store).readiness("p"), state = await store.read("p"); assert.equal(readiness.ready, false); assert.equal(state.claims.H?.at(-1)?.status, "INVALIDATED"); assert.equal(state.claims[root]?.at(-1)?.status, "NEEDS_REVALIDATION"); assert.notEqual(state.status, "PROVED"); assert.equal(state.currentFinalProofAuthority?.status, "STALE");
});

test("v3 migration never invents missing discharge lineage", async (t) => {
	const { store, reducer, root } = await fixture(t); await prove(store, reducer, "H", "H", { slot: "legacy-h" }); await prove(store, reducer, root, "T", { assumptions: ["H"], root: true, slot: "legacy-root" }); const current = await store.read("p"), legacyReceipts = Object.fromEntries(Object.entries(current.authorityReceipts).map(([id, value]) => { const { assumptionDischarges: _discharges, dependencyRevisions: _revisions, ...legacy } = value; return [id, legacy]; })), legacy = { ...current, schemaVersion: 3, authorityReceipts: legacyReceipts, authorityValidation: undefined, finalProofHistory: undefined, currentFinalProofAuthority: undefined, migrationReports: [] }; await writeFile(join(store.projectDirectory("p"), "state.json"), `${JSON.stringify(legacy, null, 2)}\n`); const migrated = await store.read("p"); assert.equal(migrated.schemaVersion, 4); assert.equal(migrated.claims[root]?.at(-1)?.status, "NEEDS_REVALIDATION"); assert.notEqual(migrated.status, "PROVED"); assert.ok(migrated.migrationReports.some((item) => item.toVersion === 4 && item.downgradedClaimIds.includes(root))); assert.ok(Object.values(migrated.obligations).some((item) => item.claimId === root && item.status === "OPEN"));
});
