import { strict as assert } from "node:assert";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import { LiteratureService, ResearchRuntime, ResearchStateReducer, ResearchStore, RootClosureService, runLeanVerifier, stableId, type FinalAuditor, type LiteratureProvider, type TrustReceipt } from "../src/index.js";

test("literature pipeline stores exact sources and refuses snippet-only theorem authority", async (t) => {
	const directory = await mkdtemp(join(tmpdir(), "mrr-lit-")); t.after(async () => rm(directory, { recursive: true, force: true })); const store = new ResearchStore(directory); await store.create("p", "p");
	const provider: LiteratureProvider = { async search() { return [{ sourceId: "exact", title: "Exact paper", authors: ["A"] }, { sourceId: "snippet", title: "Snippet only", authors: ["B"], snippet: "claimed theorem" }]; }, async acquire(candidate) { return candidate.sourceId === "exact" ? "Full exact theorem body with assumptions." : undefined; } };
	const results = await new LiteratureService(store, provider).discover("p", "query", "obligation", () => ({ literatureClaim: "Applicable lemma", assumptions: ["q > 1"], applicable: true, reason: "Assumptions match", scopeLimitations: [] }));
	assert.equal(results[0]?.authority, "EXACT_SOURCE"); assert.equal(results[1]?.authority, "SOURCE_DISCOVERED_AUTHORITY_INSUFFICIENT"); assert.ok(results[0]?.artifact); assert.ok(results[1]?.artifact, "metadata-only discoveries remain inspectable without becoming theorem authority"); assert.equal((await store.resolveArtifact("p", results[0]!.artifact!)).body, "Full exact theorem body with assumptions."); assert.equal(Object.values((await store.read("p")).artifacts).filter((item) => item.artifactType === "LITERATURE_SOURCE").length, 2);
});

test("root synthesis uses authoritative manifest and fresh audit rejection reopens frontier; success promotes exact final body", async (t) => {
	const directory = await mkdtemp(join(tmpdir(), "mrr-close-")); t.after(async () => rm(directory, { recursive: true, force: true })); const store = new ResearchStore(directory); await store.create("p", "p"); const runtime = new ResearchRuntime({ store, proofRunner: async (request) => { const now = new Date().toISOString(); return { obligationId: request.obligation.obligationId, targetClaimId: request.targetClaimId, targetStatus: "TARGET_UNRESOLVED", contributions: [], routeObservations: [], executionReceipt: { executionReceiptId: `r-${request.attemptId}`, logicalJobId: request.logicalJobId, attemptId: request.attemptId, taskIds: [], evidenceReceiptIds: [], startedAt: now, completedAt: now }, feedback: "unused" }; } }); await runtime.setRootObjective("p", "Root"); const state = await store.read("p"), root = state.rootClaimId as string; const reducer = new ResearchStateReducer(store); const reduction = await store.putArtifact("p", { artifactType: "CANDIDATE_PROOF", body: "Root reduces to L", provenance: "test" }); const reductionReceipt: TrustReceipt = { receiptId: "r-reduction", claimId: root, candidate: reduction, verifierProfile: "v", evidenceInspected: [], verdict: "CORRECT", independentContext: true, stale: false, createdAt: new Date().toISOString() }; await reducer.apply({ projectId: "p", cycleId: "c1", logicalJobId: "j1", effectSlot: "reduce", outcome: { type: "REDUCTION", claimId: root, childClaims: [{ claimId: "L", statement: "Lemma L" }], proof: reduction, receipts: [reductionReceipt], assumptions: [], dependencies: [], scope: "root theorem" } });
	const lemma = await store.putArtifact("p", { artifactType: "PROMOTED_PROOF", body: "Proof of L", provenance: "test" }); const receipt: TrustReceipt = { receiptId: "rL", claimId: "L", candidate: lemma, verifierProfile: "v", evidenceInspected: [], verdict: "CORRECT", independentContext: true, stale: false, createdAt: new Date().toISOString() }; await reducer.apply({ projectId: "p", cycleId: "c2", logicalJobId: "j2", effectSlot: "L", outcome: { type: "PROVED_CLAIM", claimId: "L", statement: "Lemma L", candidate: lemma, receipts: [receipt], dependencies: [] } });
	const synthesizer = { async synthesize(manifest: any, bodies: Readonly<Record<string, string>>) { assert.equal(manifest.root.claimId, root); assert.deepEqual([...new Set(Object.values(bodies))].sort(), ["Proof of L", "Root reduces to L"].sort()); return { proof: "Final exact proof", usedArtifactIds: [lemma.artifactId, reduction.artifactId] }; } }; const correct: FinalAuditor = { async audit() { return { verdict: "CORRECT", feedback: "correct", profile: "auditor-a" }; } }; const reject: FinalAuditor = { async audit() { return { verdict: "CRITICALLY_FLAWED", feedback: "missing boundary", profile: "fresh-b" }; } };
	await assert.rejects(new RootClosureService(store, { async synthesize() { return { proof: "invalid", usedArtifactIds: ["not-in-manifest"] }; } }, correct, correct).synthesizeAndAudit("p"), /unknown\/out-of-manifest artifacts/);
	let closure = new RootClosureService(store, synthesizer, correct, reject); assert.equal((await closure.readiness("p")).ready, true); let after = await closure.synthesizeAndAudit("p"); assert.notEqual(after.status, "PROVED"); assert.ok(Object.values(after.obligations).some((item) => item.causalReason?.includes("audit")));
	closure = new RootClosureService(store, synthesizer, correct, { async audit() { return { verdict: "CORRECT", feedback: "fresh correct", profile: "fresh-c" }; } }); after = await closure.synthesizeAndAudit("p"); assert.equal(after.status, "PROVED"); const latest = after.claims[root]?.at(-1); assert.equal(latest?.status, "PROVED"); assert.equal((await store.resolveArtifact("p", latest!.evidenceRefs[0]!)).body, "Final exact proof"); assert.deepEqual(after.artifacts[after.finalProofArtifact!.artifactId]?.metadata?.usedArtifactIds, [lemma.artifactId, reduction.artifactId]); assert.equal(Object.keys(after.acceptedEffects).length, 3);
});

test("formal verifier reports real process success and failure instead of model certificates", async () => {
	const ok = await runLeanVerifier({ executable: process.execPath, args: ["-e", "process.exit(0)"], cwd: process.cwd() }); const fail = await runLeanVerifier({ executable: process.execPath, args: ["-e", "process.exit(7)"], cwd: process.cwd() }); assert.equal(ok.success, true); assert.equal(fail.success, false); assert.equal(fail.exitCode, 7);
});
