import { strict as assert } from "node:assert";
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import { MathAgentConfigService, ProofApiServer, createConfiguredProofRoleFactory } from "../src/index.js";

async function json(base: string, path: string, init?: RequestInit): Promise<{ status: number; body: any }> {
	let failure: unknown; for (let attempt = 0; attempt < 5; attempt += 1) try { const response = await fetch(`${base}${path}`, { ...init, headers: { "content-type": "application/json", ...(init?.headers ?? {}) } }); return { status: response.status, body: await response.json() }; } catch (error) { failure = error; await new Promise((resolve) => setTimeout(resolve, 25 * (attempt + 1))); } throw failure;
}

test("public HTTP API drives corpus -> bootstrap -> ProofRuntime -> reducer -> checkpoint and survives server restart", async (t) => {
	const directory = await mkdtemp(join(tmpdir(), "mrr-api-")); const data = join(directory, "data"), corpus = join(directory, "critical-layer-fixture"); await mkdir(corpus); await writeFile(join(corpus, "critical.md"), "# Lemma Critical\nLemma Critical: the remaining expression is a square.\n\nOpen problem: connect this lemma to the root objective."); await writeFile(join(corpus, "calculation.txt"), "Computation note: values 1,4,9 pass the test.");
	const configPath = join(directory, "math-agent.toml"); let config = new MathAgentConfigService(configPath); await config.load(); await config.update({ research: { checkpointInterval: 1 } }); let server = new ProofApiServer({ rootDirectory: data, configService: config, createRoles: createConfiguredProofRoleFactory({ config, rootDirectory: data }), defaultMaxWorkers: 2, defaultMaxSteps: 3 }); t.after(async () => { await server.stop(); await rm(directory, { recursive: true, force: true }); }); let base = await server.start();
	assert.equal((await json(base, "/v1/research/projects", { method: "POST", body: JSON.stringify({ projectId: "critical", name: "critical-layer-test" }) })).status, 201);
	const archiveStatus = await json(base, "/v1/research/projects/critical/corpus-archive"); assert.equal(archiveStatus.status, 200); assert.equal(archiveStatus.body.enabled, false); assert.equal(archiveStatus.body.status, "NOT_ACTIVATED");
	assert.equal((await json(base, "/v1/research/projects/critical/corpus", { method: "POST", body: JSON.stringify({ roots: [corpus] }) })).status, 200);
	assert.equal((await json(base, "/v1/research/projects/critical/root", { method: "POST", body: JSON.stringify({ objective: "Continue unresolved Critical Layer research" }) })).status, 200);
	const ingestion = await json(base, "/v1/research/projects/critical/corpus/ingest", { method: "POST", body: "{}" }); assert.equal(ingestion.body.imported, 2);
	const bootstrap = await json(base, "/v1/research/projects/critical/bootstrap", { method: "POST", body: "{}" }); assert.ok(bootstrap.body.report.createdClaimIds.length > 0);
	const start = await json(base, "/v1/research/projects/critical/start", { method: "POST", body: JSON.stringify({ maxCycles: 1 }) }); assert.equal(start.status, 202);
	let view: any; for (let index = 0; index < 100; index += 1) { view = (await json(base, "/v1/research/projects/critical")).body; if (!view.active) break; await new Promise((resolve) => setTimeout(resolve, 20)); }
	assert.equal(view.active, false); assert.equal(view.state.status, "PROVED", view.state.lastError ?? JSON.stringify(view.state)); assert.equal(view.state.effectiveConfig.proof.workflowMode, "dynamic"); assert.equal(Object.keys(view.state.acceptedEffects).length, 1); assert.equal(view.state.checkpoints.length, 1); const controllerPlans = Object.values(view.state.executionPlans) as any[]; assert.ok(controllerPlans.length > 0); assert.ok(controllerPlans.flatMap((plan) => plan.actionExecutions).every((action: any) => action.status === "COMPLETED"));
	assert.equal((await json(base, "/v1/research/projects/critical/corpus-archive")).body.intents.length, 0);
	assert.ok((await json(base, "/v1/research/projects/critical/frontier")).body.frontier); assert.ok((await json(base, "/v1/research/projects/critical/claims")).body.claims); assert.ok((await json(base, "/v1/research/projects/critical/routes")).body.routes); assert.ok((await json(base, "/v1/research/projects/critical/events")).body.events.length > 0); assert.equal((await json(base, "/v1/research/projects/critical/result")).body.status, "PROVED"); const readiness = (await json(base, "/v1/research/projects/critical/root-readiness")).body; assert.equal(readiness.rootObjectiveContract.statement, "Continue unresolved Critical Layer research"); assert.deepEqual(readiness.allowedAssumptions, []); assert.ok(Array.isArray(readiness.currentResearchRequiredAssumptions)); const audit = (await json(base, "/v1/research/projects/critical/audit")).body; assert.equal(audit.configRevision, view.state.configRevision); assert.equal(audit.rootObjectiveContract.contractId, readiness.rootObjectiveContract.contractId); assert.ok(audit.effectiveConfig); assert.ok(audit.executionPlans); assert.ok(audit.executionTasks); assert.ok(audit.evidenceReceipts); assert.ok(audit.authorityReceipts); assert.ok(audit.bootstrapReports); assert.equal(audit.invariants.valid, true); assert.equal(audit.rootReadiness.ready, true);
	await server.stop(); config = new MathAgentConfigService(configPath); await config.load(); server = new ProofApiServer({ rootDirectory: data, configService: config, createRoles: createConfiguredProofRoleFactory({ config, rootDirectory: data }), defaultMaxWorkers: 2, defaultMaxSteps: 3 }); base = await server.start(); const rediscovered = await json(base, "/v1/research/projects"); assert.ok(rediscovered.body.projects.some((project: any) => project.projectId === "critical" && project.status === "PROVED")); const after = await json(base, "/v1/research/projects/critical"); assert.equal(after.body.state.acceptedEffects.length ?? Object.keys(after.body.state.acceptedEffects).length, 1); assert.equal((await json(base, "/v1/research/projects/critical/corpus-archive")).body.intents.length, 0); await server.stop();
});
