import { strict as assert } from "node:assert";
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test, type TestContext } from "node:test";
import {
	emptyProject, inspectResearchState, ResearchRuntime, ResearchStateReducer, ResearchStore, RootClosureService, rootSynthesisReadiness, stableId,
	type ArtifactRef, type FinalAuditor, type TacticalResearchResult, type TrustReceipt, type VerifiedResearchContribution,
} from "../src/index.js";

async function fixture(t: TestContext, allowedAssumptions: readonly string[] = []) {
	const directory = await mkdtemp(join(tmpdir(), "mrr-root-contract-")); t.after(async () => rm(directory, { recursive: true, force: true }));
	const store = new ResearchStore(join(directory, "data")); await store.create("p", "p"); const runtime = new ResearchRuntime({ store, proofRunner: unresolved }); await runtime.setRootObjective("p", "T", allowedAssumptions);
	const state = await store.read("p"), root = state.rootClaimId as string, obligation = Object.values(state.obligations).find((item) => item.claimId === root)!;
	return { directory, store, runtime, root, obligation };
}

function receipt(claimId: string, candidate: ArtifactRef, profile: string): TrustReceipt { return { receiptId: stableId("receipt", candidate.artifactId, profile), claimId, candidate, verifierProfile: profile, evidenceInspected: [], verdict: "CORRECT", independentContext: true, stale: false, createdAt: new Date().toISOString() }; }
function execution(): TacticalResearchResult["executionReceipt"] { const now = new Date().toISOString(); return { executionReceiptId: "execution", logicalJobId: "job", attemptId: "attempt", taskIds: [], evidenceReceiptIds: [], startedAt: now, completedAt: now }; }

test("unconditional root rejects a verified H => T target proof and preserves it as conditional support", async (t) => {
	const { store, root, obligation } = await fixture(t), candidate = await store.putArtifact("p", { artifactType: "WORKER_CANDIDATE", body: "Assuming H, prove T", provenance: "adversarial-target" }), primary = receipt(root, candidate, "primary"), secondary = receipt(root, candidate, "secondary");
	await new ResearchStateReducer(store).applyTactical({ projectId: "p", cycleId: "cycle", logicalJobId: "job", obligationId: obligation.obligationId, targetClaimId: root, result: { obligationId: obligation.obligationId, targetClaimId: root, targetStatus: "TARGET_PROVED", targetSubmission: { submissionId: "submission", targetObligationId: obligation.obligationId, targetClaimId: root, scope: "TARGET", statement: "T", candidate, assumptions: [" H "], dependencies: [], evidenceArtifacts: [], primaryReceipt: primary, secondaryReceipt: secondary }, contributions: [], routeObservations: [], executionReceipt: execution(), feedback: "verified conditional target" } });
	const state = await store.read("p"), latestRoot = state.claims[root]?.at(-1), conditional = Object.values(state.claims).map((items) => items.at(-1)).find((claim) => claim?.claimId !== root && claim?.assumptions.includes("H"));
	assert.equal(latestRoot?.status, "OPEN"); assert.deepEqual(latestRoot?.assumptions, []); assert.deepEqual(state.rootObjectiveContract?.allowedAssumptions, []); assert.equal(state.rootObjectiveContract?.statement, "T"); assert.equal(conditional?.status, "PROVED"); assert.ok(state.supportEdges.some((edge) => edge.fromClaimId === conditional?.claimId && edge.toClaimId === root));
	const readiness = rootSynthesisReadiness(state); assert.equal(readiness.ready, false); assert.ok(readiness.currentResearchRequiredAssumptions.some((item) => item.normalizedAssumption === "H" && item.status === "UNRESOLVED")); assert.ok(state.events.some((event) => event.type === "research/root_contract_blocked" && event.detail.code === "ROOT_ASSUMPTION_ESCALATION"));
});

test("ordinary research APIs cannot mutate an existing root objective contract", async (t) => {
	const { store, runtime } = await fixture(t); const before = (await store.read("p")).rootObjectiveContract; await runtime.setRootObjective("p", " T ", []); await assert.rejects(runtime.setRootObjective("p", "T", ["H"]), /versioned contract revision/); await assert.rejects(runtime.setRootObjective("p", "Different T", []), /root meaning|versioned contract revision/); assert.deepEqual((await store.read("p")).rootObjectiveContract, before);
});

for (const kind of ["REDUCTION", "CASE_SPLIT"] as const) test(`conditional root ${kind.toLocaleLowerCase()} cannot mutate unconditional root authority`, async (t) => {
	const { store, root, obligation } = await fixture(t), candidate = await store.putArtifact("p", { artifactType: "WORKER_CANDIDATE", body: `${kind} under H`, provenance: "adversarial-structure" }), verification = receipt(root, candidate, kind), common = { contributionId: kind, kind, statement: kind === "REDUCTION" ? "Under H, T reduces to L" : "Under H, A/B exhaust T", relationshipToTarget: "conditional structural support", targetObligationId: obligation.obligationId, targetClaimId: root, assumptions: ["H"], dependencyClaims: [], evidenceArtifacts: [], candidate, producer: { role: "worker" as const, identity: "test" }, verification }, contribution: VerifiedResearchContribution = kind === "REDUCTION" ? { ...common, childClaims: [{ claimId: "L", statement: "L" }], targetScope: "domain of T" } : { ...common, childClaims: [{ claimId: "A", statement: "A" }, { claimId: "B", statement: "B" }], coverageScope: "domain of T", coverageAssertion: "A or B" };
	await new ResearchStateReducer(store).applyTactical({ projectId: "p", cycleId: `cycle-${kind}`, logicalJobId: `job-${kind}`, obligationId: obligation.obligationId, targetClaimId: root, result: { obligationId: obligation.obligationId, targetClaimId: root, targetStatus: "TARGET_UNRESOLVED", contributions: [contribution], routeObservations: [], executionReceipt: execution(), feedback: "conditional structure" } });
	const state = await store.read("p"); assert.equal(state.claims[root]?.at(-1)?.status, "OPEN"); assert.equal(state.claims[root]?.at(-1)?.dependencies.length, 0); assert.equal(Object.keys(state.coverage).length, 0); assert.equal(state.claims.L, undefined); assert.equal(state.claims.A, undefined); assert.ok(Object.values(state.claims).some((revisions) => revisions.at(-1)?.provenance === "verified-research-outcome" && revisions.at(-1)?.assumptions.includes("H"))); assert.equal(rootSynthesisReadiness(state).ready, false);
});

test("conditional root counterexample does not refute the unconditional objective", async (t) => {
	const { store, root, obligation } = await fixture(t), candidate = await store.putArtifact("p", { artifactType: "COUNTEREXAMPLE", body: "counterexample only under H", provenance: "adversarial-refutation" }), contribution: VerifiedResearchContribution = { contributionId: "counter", kind: "COUNTEREXAMPLE", statement: "Under H, a witness refutes T", relationshipToTarget: "conditional refutation", targetObligationId: obligation.obligationId, targetClaimId: root, claimId: root, assumptions: ["H"], dependencyClaims: [], evidenceArtifacts: [], candidate, producer: { role: "worker", identity: "test" }, verification: receipt(root, candidate, "counter"), targetScope: "all T inputs", counterexampleScope: "H inputs" };
	await new ResearchStateReducer(store).applyTactical({ projectId: "p", cycleId: "counter-cycle", logicalJobId: "counter-job", obligationId: obligation.obligationId, targetClaimId: root, result: { obligationId: obligation.obligationId, targetClaimId: root, targetStatus: "TARGET_REFUTED", contributions: [contribution], routeObservations: [], executionReceipt: execution(), feedback: "conditional counterexample" } });
	const state = await store.read("p"); assert.equal(state.claims[root]?.at(-1)?.status, "OPEN"); assert.ok(Object.values(state.claims).some((revisions) => revisions.at(-1)?.claimId !== root && revisions.at(-1)?.assumptions.includes("H")));
});

test("explicitly allowed root assumption permits H => T and remains explicit in readiness", async (t) => {
	const { store, root, obligation } = await fixture(t, ["H"]), candidate = await store.putArtifact("p", { artifactType: "WORKER_CANDIDATE", body: "H implies T", provenance: "allowed-target" });
	await new ResearchStateReducer(store).applyTactical({ projectId: "p", cycleId: "allowed-cycle", logicalJobId: "allowed-job", obligationId: obligation.obligationId, targetClaimId: root, result: { obligationId: obligation.obligationId, targetClaimId: root, targetStatus: "TARGET_PROVED", targetSubmission: { submissionId: "allowed", targetObligationId: obligation.obligationId, targetClaimId: root, scope: "TARGET", statement: "T", candidate, assumptions: ["H"], dependencies: [], evidenceArtifacts: [], primaryReceipt: receipt(root, candidate, "primary"), secondaryReceipt: receipt(root, candidate, "secondary") }, contributions: [], routeObservations: [], executionReceipt: execution(), feedback: "authorized" } });
	const state = await store.read("p"), readiness = rootSynthesisReadiness(state); assert.equal(state.claims[root]?.at(-1)?.status, "PROVED"); assert.equal(readiness.ready, true); assert.deepEqual(readiness.allowedAssumptions, ["H"]); assert.ok(readiness.closureRequiredAssumptions.some((item) => item.normalizedAssumption === "H" && item.status === "ALLOWED"));
});

test("an independently proved assumption discharges a conditional target without changing the root contract", async (t) => {
	const { store, root, obligation } = await fixture(t), reducer = new ResearchStateReducer(store), hCandidate = await store.putArtifact("p", { artifactType: "WORKER_CANDIDATE", body: "Proof of H", provenance: "discharge" }); await reducer.apply({ projectId: "p", cycleId: "h-cycle", logicalJobId: "h-job", effectSlot: "prove-h", outcome: { type: "NEW_LEMMA", claimId: "H", statement: "H", candidate: hCandidate, receipts: [receipt("H", hCandidate, "h")], dependencies: [], assumptions: [] } });
	const candidate = await store.putArtifact("p", { artifactType: "WORKER_CANDIDATE", body: "H implies T", provenance: "discharged-target" }); await reducer.applyTactical({ projectId: "p", cycleId: "target-cycle", logicalJobId: "target-job", obligationId: obligation.obligationId, targetClaimId: root, result: { obligationId: obligation.obligationId, targetClaimId: root, targetStatus: "TARGET_PROVED", targetSubmission: { submissionId: "discharged", targetObligationId: obligation.obligationId, targetClaimId: root, scope: "TARGET", statement: "T", candidate, assumptions: ["H"], dependencies: [], evidenceArtifacts: [], primaryReceipt: receipt(root, candidate, "primary"), secondaryReceipt: receipt(root, candidate, "secondary") }, contributions: [], routeObservations: [], executionReceipt: execution(), feedback: "discharged" } });
	const state = await store.read("p"), readiness = rootSynthesisReadiness(state); assert.deepEqual(state.rootObjectiveContract?.allowedAssumptions, []); assert.equal(state.claims[root]?.at(-1)?.status, "PROVED"); assert.equal(readiness.ready, true); assert.ok(readiness.closureRequiredAssumptions.some((item) => item.assumption === "H" && item.status === "DISCHARGED"));
});

test("synthesis manifest carries the root contract and deterministic pre-audit rejects statement or assumption drift", async (t) => {
	const { store, root, obligation } = await fixture(t, ["H"]), candidate = await store.putArtifact("p", { artifactType: "WORKER_CANDIDATE", body: "H implies T", provenance: "synthesis-contract" }), reducer = new ResearchStateReducer(store); await reducer.applyTactical({ projectId: "p", cycleId: "synthesis-target", logicalJobId: "synthesis-target", obligationId: obligation.obligationId, targetClaimId: root, result: { obligationId: obligation.obligationId, targetClaimId: root, targetStatus: "TARGET_PROVED", targetSubmission: { submissionId: "synthesis-target", targetObligationId: obligation.obligationId, targetClaimId: root, scope: "TARGET", statement: "T", candidate, assumptions: ["H"], dependencies: [], evidenceArtifacts: [], primaryReceipt: receipt(root, candidate, "primary"), secondaryReceipt: receipt(root, candidate, "secondary") }, contributions: [], routeObservations: [], executionReceipt: execution(), feedback: "authorized" } });
	const auditor: FinalAuditor = { async audit() { return { verdict: "CORRECT", feedback: "contract preserved", profile: "fresh-auditor" }; } }, invalidStatement = new RootClosureService(store, { async synthesize(manifest) { assert.equal(manifest.rootObjective, "T"); assert.deepEqual(manifest.allowedAssumptions, ["H"]); assert.ok(manifest.assumptionStatus.some((item) => item.assumption === "H" && item.status === "ALLOWED")); return { proof: "wrong theorem", usedArtifactIds: manifest.proofArtifacts.map((item) => item.artifactId), theoremStatement: "T or K", assumptions: ["H"] }; } }, auditor, auditor); await assert.rejects(invalidStatement.synthesizeAndAudit("p"), /ROOT_STATEMENT_MISMATCH/);
	const invalidAssumption = new RootClosureService(store, { async synthesize(manifest) { return { proof: "extra assumption", usedArtifactIds: manifest.proofArtifacts.map((item) => item.artifactId), theoremStatement: "T", assumptions: ["H", "K"] }; } }, auditor, auditor); await assert.rejects(invalidAssumption.synthesizeAndAudit("p"), /ROOT_ASSUMPTION_ESCALATION/);
	const closure = new RootClosureService(store, { async synthesize(manifest) { return { proof: "final proof of T under H", usedArtifactIds: manifest.proofArtifacts.map((item) => item.artifactId), theoremStatement: "T", assumptions: ["H"] }; } }, auditor, auditor), state = await closure.synthesizeAndAudit("p"); assert.equal(state.status, "PROVED"); assert.deepEqual(state.claims[root]?.at(-1)?.assumptions, ["H"]); assert.equal(state.artifacts[state.finalProofArtifact!.artifactId]?.metadata?.theoremStatement, "T"); assert.deepEqual(state.artifacts[state.finalProofArtifact!.artifactId]?.metadata?.assumptions, ["H"]);
});

test("v2 migration never converts research-added root assumptions into permission", async (t) => {
	const directory = await mkdtemp(join(tmpdir(), "mrr-v2-root-migration-")); t.after(async () => rm(directory, { recursive: true, force: true })); const store = new ResearchStore(directory), projectId = "legacy-v2", projectDirectory = store.projectDirectory(projectId), now = new Date().toISOString(); await mkdir(join(projectDirectory, "artifacts"), { recursive: true }); await mkdir(join(projectDirectory, "scratch"), { recursive: true });
	const base = emptyProject(projectId, "legacy", now), rootOpen = { claimId: "root", revision: 1, statement: "T", role: "ROOT" as const, status: "OPEN" as const, dependencies: [], evidenceRefs: [], auditRefs: [], assumptions: [], provenance: "user-objective", createdAt: now }, rootEscalated = { ...rootOpen, revision: 2, status: "PROVED" as const, assumptions: ["H"], provenance: "verified-research-outcome" }, legacy = { ...base, schemaVersion: 2, status: "PROVED", rootObjective: "T", rootClaimId: "root", claims: { root: [rootOpen, rootEscalated] }, migrationReports: [] }; await writeFile(join(projectDirectory, "state.json"), `${JSON.stringify(legacy, null, 2)}\n`);
	const migrated = await store.read(projectId); assert.equal(migrated.schemaVersion, 4); assert.equal(migrated.rootObjectiveContract?.status, "VALID"); assert.deepEqual(migrated.rootObjectiveContract?.allowedAssumptions, []); assert.equal(migrated.claims.root?.at(-1)?.status, "NEEDS_REVALIDATION"); assert.notEqual(migrated.status, "PROVED"); assert.ok(migrated.migrationReports.some((report) => report.toVersion === 3 && report.downgradedClaimIds.includes("root")));
});

test("authority consistency checker detects claim/receipt assumption mismatch", async (t) => {
	const { store, root } = await fixture(t), candidate = await store.putArtifact("p", { artifactType: "WORKER_CANDIDATE", body: "proof T", provenance: "authority-test" }), reducer = new ResearchStateReducer(store); await reducer.apply({ projectId: "p", cycleId: "authority-cycle", logicalJobId: "authority-job", effectSlot: "root", outcome: { type: "PROVED_CLAIM", claimId: root, statement: "T", candidate, receipts: [receipt(root, candidate, "primary"), receipt(root, candidate, "secondary")], dependencies: [], assumptions: [] } });
	const state = await store.read("p"), authorityId = Object.keys(state.authorityReceipts)[0]!, corrupt = { ...state, authorityReceipts: { ...state.authorityReceipts, [authorityId]: { ...state.authorityReceipts[authorityId]!, assumptions: ["H"] } } }, checked = inspectResearchState(corrupt); assert.equal(checked.valid, false); assert.ok(checked.violations.some((item) => item.code === "AUTHORITY_ASSUMPTION_MISMATCH"));
});

test("MANUAL_REOPEN is operator-only and the explicit operator action records its actor", async (t) => {
	const { store, runtime, obligation } = await fixture(t); await store.transaction("p", (draft) => { (draft as any).routes = { manual: { routeId: "manual", targetObligationId: obligation.obligationId, family: "manual", mechanism: "manual", strategyDescription: "operator decision", assumptions: [], dependencySnapshot: [], artifactRefs: [], status: "FAILED", attemptIds: [], reopenPredicate: { type: "MANUAL_REOPEN" }, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() } }; });
	const state = await runtime.reopenRouteAsOperator("p", "manual", "new external information"); assert.equal(state.routes.manual?.status, "ACTIVE"); assert.ok(state.events.some((event) => event.type === "research/route_reopened" && event.detail.actor === "OPERATOR"));
});

async function unresolved(request: import("../src/index.js").TacticalProofRequest): Promise<TacticalResearchResult> { return { obligationId: request.obligation.obligationId, targetClaimId: request.targetClaimId, targetStatus: "TARGET_UNRESOLVED", contributions: [], routeObservations: [], executionReceipt: execution(), feedback: "unused" }; }
