import assert from "node:assert/strict";
import { cp, readFile, readdir, rm, writeFile, mkdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { mkdtemp } from "node:fs/promises";
import test from "node:test";
import { AgentCore } from "../src/agent/agent.js";
import { BOOTSTRAP_ANALYSIS_SCHEMA, BOOTSTRAP_SCHEMA_VERSION, BootstrapSchemaValidationError, BootstrapStructuredOutputParseError, parseBootstrapAnalysis, parseBootstrapAnalysisText } from "../src/research/bootstrap-schema.js";
import { CodexCliProvider, codexCliArguments } from "../src/providers/codex.js";
import { CorpusService } from "../src/research/corpus.js";
import { AgentCorpusBootstrapper } from "../src/research/agent-role.js";
import { ResearchRuntime } from "../src/research/runtime.js";
import { ResearchStore } from "../src/research/store.js";
import { stableId } from "../src/research/ids.js";
import { Session } from "../src/session/session.js";
import type { ModelProvider, ProviderRequest } from "../src/providers/types.js";
import type { BootstrapProposal, DecisionBasis, ResearchProjectState, TacticalResearchResult } from "../src/research/types.js";

test("canonical bootstrap schema and parser agree on dependencies and structural kinds", () => {
	const response = {
		proposals: [
			fullProposal({ entityKey: "base", kind: "CLAIM", statement: "Base lemma", dependencyHints: [] }),
			fullProposal({ entityKey: "reduction", kind: "REDUCTION", statement: "Root reduces to base", dependencyHints: ["base"], targetHint: "root" }),
			fullProposal({ entityKey: "cases", kind: "CASE_SPLIT", statement: "Root has two cases", dependencyHints: [], targetHint: "root", cases: ["even", "odd"] }),
			fullProposal({ entityKey: "dead", kind: "FAILED_ROUTE", statement: "Descent fails", dependencyHints: [], targetHint: "root", routeFamily: "descent", mechanism: "minimal-counterexample", failureMechanism: "measure is not decreasing" }),
		],
		dependencies: [{ fromEntity: "reduction", toEntity: "base", confidence: "EXPLICIT", confidenceScore: 0.99 }], warnings: [],
	};
	const parsed = parseBootstrapAnalysis(response);
	assert.equal(parsed.proposals.length, 4);
	assert.equal(parsed.dependencies[0]?.confidence, "EXPLICIT");
	const proposalSchema = ((BOOTSTRAP_ANALYSIS_SCHEMA.properties as Record<string, any>).proposals.items as Record<string, any>);
	assert.ok(proposalSchema.required.includes("dependencyHints"));
	assert.deepEqual(((BOOTSTRAP_ANALYSIS_SCHEMA.properties as Record<string, any>).dependencies.items.properties.confidence.enum), ["EXPLICIT", "INFERRED"]);
	assert.equal(proposalSchema.allOf, undefined, "provider-compatible schema must avoid unsupported conditionals");
	assert.ok(["targetHint", "routeFamily", "mechanism", "failureMechanism", "cases"].every((key) => proposalSchema.required.includes(key)));
});

test("real Luna numeric-confidence fixture fails clearly while its canonical correction parses", async () => {
	const fixture = JSON.parse(await readFile(fixturePath("luna-bootstrap-numeric-confidence.json"), "utf8")) as { response: Record<string, any> };
	assert.throws(() => parseBootstrapAnalysis(fixture.response), (error) => error instanceof BootstrapSchemaValidationError && /confidence must be EXPLICIT or INFERRED/u.test(error.message));
	const corrected = structuredClone(fixture.response); corrected.proposals = corrected.proposals.map(fullProposal); corrected.dependencies[0].confidenceScore = corrected.dependencies[0].confidence; corrected.dependencies[0].confidence = "EXPLICIT";
	assert.equal(parseBootstrapAnalysis(corrected).dependencies[0]?.confidenceScore, 1);
	const missing = structuredClone(corrected); delete missing.proposals[0].dependencyHints;
	assert.throws(() => parseBootstrapAnalysis(missing), /dependencyHints is required and must be string\[\]/u);
});

test("malformed structured output remains fail-closed and durably preserves exact model evidence", async (t) => {
	const raw = '{"proposals":[],"dependencies":[],"warnings":[]} trailing'; assert.throws(() => parseBootstrapAnalysisText(raw), (error) => error instanceof BootstrapStructuredOutputParseError && error.rawResponse === raw);
	const directory = await mkdtemp(join(tmpdir(), "mrr-bootstrap-raw-failure-")), corpusDirectory = join(directory, "corpus"), data = join(directory, "data"); await mkdir(corpusDirectory); await writeFile(join(corpusDirectory, "source.md"), "Lemma Durable: statement"); t.after(() => rm(directory, { recursive: true, force: true }));
	const store = new ResearchStore(data), runtime = new ResearchRuntime({ store, proofRunner: async () => { throw new Error("unused"); } }); await runtime.createProject("p", "p"); await runtime.setRootObjective("p", "Root theorem"); const corpus = new CorpusService(store); await corpus.attach("p", [corpusDirectory]); await corpus.ingest("p");
	await corpus.bootstrap("p", { async analyzeFile() { throw new BootstrapStructuredOutputParseError("malformed", raw).attachModelMetadata({ sessionId: "session-exact", provider: "openai-codex", model: "gpt-5.6-luna" }); } }); const state = await store.read("p"), work = Object.values(Object.values(state.bootstrapRuns)[0]!.rangeWork)[0]!; assert.equal(work.failure?.type, "STRUCTURED_OUTPUT_PARSE_FAILURE"); assert.equal(work.rawResponse, raw); assert.equal(work.modelSessionId, "session-exact"); assert.equal(work.provider, "openai-codex"); assert.equal(work.model, "gpt-5.6-luna");
});

test("Codex long structured input uses stdin and output-schema instead of argv", async () => {
	const fixture = fixturePath("fake-codex-cli.mjs"), provider = new CodexCliProvider({ command: process.execPath, commandArgs: [fixture] });
	const longPrompt = "x".repeat(100_000), events = [];
	for await (const event of provider.stream({ model: { provider: "openai-codex", model: "gpt-test" }, messages: [{ role: "user", id: "u", content: longPrompt, timestamp: Date.now(), responseSchema: BOOTSTRAP_ANALYSIS_SCHEMA }], tools: [], responseSchema: BOOTSTRAP_ANALYSIS_SCHEMA })) events.push(event);
	assert.ok(events.some((event) => event.type === "text_delta"));
	assert.ok(events.some((event) => event.type === "complete"));
	assert.ok(!codexCliArguments("gpt-test", "schema.json").some((argument) => argument.includes(longPrompt)));
	assert.equal(codexCliArguments("gpt-test").at(-1), "-");
	assert.ok(codexCliArguments("gpt-5.6-luna", "schema.json", "max").includes("model_reasoning_effort=\"max\""));
});

test("production AgentCorpusBootstrapper sends mrr-bootstrap-v2 through the normal Agent/provider path", async (t) => {
	const directory = await mkdtemp(join(tmpdir(), "mrr-bootstrap-agent-v2-")), corpusDirectory = join(directory, "corpus"), data = join(directory, "data"); await mkdir(corpusDirectory); await writeFile(join(corpusDirectory, "source.md"), "Lemma V2: statement"); t.after(() => rm(directory, { recursive: true, force: true }));
	const requests: ProviderRequest[] = [], provider: ModelProvider = { id: "mock", async *stream(request) { requests.push(request); const analysisRequest = typeof request.responseSchema?.properties === "object" && request.responseSchema.properties !== null && "proposals" in request.responseSchema.properties, body = analysisRequest ? { proposals: [fullProposal({ entityKey: "v2", kind: "CLAIM", statement: "Lemma V2", dependencyHints: [] })], dependencies: [], warnings: [] } : { frontierEntityKeys: ["v2"], warnings: [] }; yield { type: "text_delta", text: JSON.stringify(body) }; yield { type: "complete", stopReason: "end_turn" }; } };
	const store = new ResearchStore(data), runtime = new ResearchRuntime({ store, proofRunner: async () => { throw new Error("unused"); } }); await runtime.createProject("p", "p"); await runtime.setRootObjective("p", "Root theorem"); const corpus = new CorpusService(store); await corpus.attach("p", [corpusDirectory]); await corpus.ingest("p"); let ordinal = 0;
	const bootstrapper = new AgentCorpusBootstrapper(async (artifactId) => { ordinal += 1; const identity = `${artifactId}-${ordinal}`, session = await Session.create({ projectId: identity, sessionId: identity, cwd: directory, directory: join(directory, "agents", identity) }); return new AgentCore({ session, model: { provider: "mock", model: "bootstrap-test" }, provider }); });
	await corpus.bootstrap("p", bootstrapper); const analysisRequest = requests.find((request) => typeof request.responseSchema?.properties === "object" && request.responseSchema.properties !== null && "proposals" in request.responseSchema.properties); assert.ok(analysisRequest); assert.deepEqual(analysisRequest.responseSchema, BOOTSTRAP_ANALYSIS_SCHEMA); assert.match(JSON.stringify(analysisRequest.messages), new RegExp(BOOTSTRAP_SCHEMA_VERSION)); assert.equal(Object.values((await store.read("p")).bootstrapRuns)[0]?.schemaVersion, BOOTSTRAP_SCHEMA_VERSION);
});

test("incremental bootstrap persists completed ranges, reclaims interruption, and stales changed corpus identity", async (t) => {
	const directory = await mkdtemp(join(tmpdir(), "mrr-bootstrap-resume-")), corpusDirectory = join(directory, "corpus"), data = join(directory, "data"); await mkdir(corpusDirectory); const sourcePath = join(corpusDirectory, "large.md"); await writeFile(sourcePath, Array.from({ length: 2400 }, (_, index) => `Lemma L${index}: statement ${"z".repeat(28)}`).join("\n")); t.after(() => rm(directory, { recursive: true, force: true }));
	const store = new ResearchStore(data), runtime = new ResearchRuntime({ store, proofRunner: async () => { throw new Error("unused"); } }); await runtime.createProject("p", "p"); await runtime.setRootObjective("p", "Root theorem"); const corpus = new CorpusService(store); await corpus.attach("p", [corpusDirectory]); await corpus.ingest("p");
	let firstCalls = 0; const controller = new AbortController();
	await assert.rejects(corpus.bootstrap("p", { async analyzeFile() { firstCalls += 1; if (firstCalls === 2) { controller.abort(); throw new Error("supervisor interruption"); } return analysis(`first-${firstCalls}`); } }, controller.signal), /supervisor interruption/u);
	let state = await store.read("p"), run = Object.values(state.bootstrapRuns)[0]; assert.ok(run); const completedBefore = Object.values(run.rangeWork).filter((item) => item.status === "COMPLETED"); assert.equal(completedBefore.length, 1); const runId = run.bootstrapRunId;
	let resumedCalls = 0; const resumedReport = await new CorpusService(store).bootstrap("p", { async analyzeFile() { resumedCalls += 1; return analysis(`resume-${resumedCalls}`); } }); state = await store.read("p"); run = state.bootstrapRuns[runId]; assert.equal(run?.status, "COMPLETED"); assert.equal(Object.values(run?.rangeWork ?? {}).every((item) => item.status === "COMPLETED"), true); assert.equal(Object.values(run?.rangeWork ?? {}).every((item) => item.failure === undefined), true, "a successful retry must not inherit its orphan/interruption failure"); assert.equal(resumedReport.bootstrapRunId, runId); assert.equal(resumedCalls, Object.keys(run?.rangeWork ?? {}).length - 1, "the completed range must not rerun");
	await writeFile(sourcePath, `${await readFile(sourcePath, "utf8")}\nLemma changed: new statement\n`); await corpus.ingest("p"); await new CorpusService(store).bootstrap("p", { async analyzeFile() { return analysis("changed"); } }); state = await store.read("p"); assert.equal(state.bootstrapRuns[runId]?.status, "STALE"); assert.ok(Object.values(state.bootstrapRuns[runId]?.rangeWork ?? {}).every((item) => item.status === "STALE"));
});

test("concurrent canonical bootstrap invocations join one execution without duplicate provider calls or import/report", async (t) => {
	const directory = await mkdtemp(join(tmpdir(), "mrr-bootstrap-concurrent-")), corpusDirectory = join(directory, "corpus"), data = join(directory, "data"); await mkdir(corpusDirectory); await writeFile(join(corpusDirectory, "large.md"), Array.from({ length: 3_000 }, (_, index) => `Lemma C${index}: ${"q".repeat(32)}`).join("\n")); t.after(() => rm(directory, { recursive: true, force: true }));
	const store = new ResearchStore(data), runtime = new ResearchRuntime({ store, proofRunner: async () => { throw new Error("unused"); } }); await runtime.createProject("p", "p"); await runtime.setRootObjective("p", "Root theorem"); const seed = new CorpusService(store); await seed.attach("p", [corpusDirectory]); await seed.ingest("p");
	let release!: () => void, entered!: () => void; const gate = new Promise<void>((resolve) => { release = resolve; }), firstProviderCall = new Promise<void>((resolve) => { entered = resolve; }), calls = new Map<string, number>(); const bootstrapper = { async analyzeFile(request: Parameters<import("../src/research/corpus.js").CorpusBootstrapper["analyzeFile"]>[0]) { const key = `${request.range.startLine}-${request.range.endLine}`; calls.set(key, (calls.get(key) ?? 0) + 1); if (calls.size === 1) { entered(); await gate; } const base = analysis(`range-${request.range.startLine}`); return request.range.startLine === 1 ? { ...base, proposals: [...base.proposals, { entityKey: "concurrent-reduction", kind: "REDUCTION" as const, statement: "Root reduces to first range", dependencyHints: ["range-1"], targetHint: "root" }, { entityKey: "concurrent-cases", kind: "CASE_SPLIT" as const, statement: "Root has two concurrent cases", dependencyHints: [], targetHint: "root", cases: ["concurrent even", "concurrent odd"] }] } : base; } };
	const first = new CorpusService(store).bootstrap("p", bootstrapper); await firstProviderCall; const second = new CorpusService(store).bootstrap("p", bootstrapper); release(); const [left, right] = await Promise.all([first, second]); const state = await store.read("p");
	assert.equal(left.bootstrapRunId, right.bootstrapRunId); assert.deepEqual(left, right); assert.equal(calls.size, left.analyzedRanges.length); assert.ok([...calls.values()].every((count) => count === 1), "each range must make exactly one provider call"); assert.equal(state.bootstrapReports.filter((report) => report.bootstrapRunId === left.bootstrapRunId).length, 1); assert.equal(Object.values(state.artifacts).filter((artifact) => artifact.artifactType === "BOOTSTRAP_REPORT").length, 1); assert.equal(state.events.filter((event) => event.type === "research/bootstrap_completed").length, 1); assert.ok(left.createdClaimIds.every((claimId) => state.claims[claimId]?.length === 1)); assert.equal(state.claims[state.rootClaimId!]!.length, 3, "joined execution must import its reduction and case split exactly once"); assert.equal(left.reconstructedReductions.length, 1); assert.equal(left.reconstructedCoverage.length, 1);
});

test("restart after provisional import commit does not replay structural imports or claim revisions", async (t) => {
	const directory = await mkdtemp(join(tmpdir(), "mrr-bootstrap-import-crash-")), corpusDirectory = join(directory, "corpus"), data = join(directory, "data"); await mkdir(corpusDirectory); await writeFile(join(corpusDirectory, "source.md"), "Historical structural map"); t.after(() => rm(directory, { recursive: true, force: true }));
	const store = new ResearchStore(data), runtime = new ResearchRuntime({ store, proofRunner: async () => { throw new Error("unused"); } }); await runtime.createProject("p", "p"); let state = await runtime.setRootObjective("p", "Root theorem"); const rootClaimId = state.rootClaimId!; const seed = new CorpusService(store); await seed.attach("p", [corpusDirectory]); await seed.ingest("p"); let providerCalls = 0, injected = 0;
	const structural = { async analyzeFile() { providerCalls += 1; return { proposals: [{ entityKey: "child", kind: "CLAIM" as const, statement: "Imported child", dependencyHints: [] }, { entityKey: "reduction", kind: "REDUCTION" as const, statement: "Root reduces to child", dependencyHints: ["child"], targetHint: "root" }, { entityKey: "cases", kind: "CASE_SPLIT" as const, statement: "Root splits into two cases", dependencyHints: [], targetHint: "root", cases: ["even case", "odd case"] }, { entityKey: "failed", kind: "FAILED_ROUTE" as const, statement: "Historical descent failed", dependencyHints: [], targetHint: "root", routeFamily: "descent", mechanism: "minimal-counterexample", failureMechanism: "no decreasing measure" }], dependencies: [], warnings: [] }; } };
	const crashing = new CorpusService(store, { bootstrapFaultInjector(phase) { assert.equal(phase, "AFTER_PROVISIONAL_IMPORT_COMMIT"); injected += 1; throw new Error("crash:after-provisional-import-commit"); } }); await assert.rejects(crashing.bootstrap("p", structural), /crash:after-provisional-import-commit/u); state = await store.read("p"); const run = Object.values(state.bootstrapRuns)[0]!; assert.equal(injected, 1); assert.equal(run.provisionalImportStatus, "COMPLETED"); assert.ok(run.provisionalImportResult); assert.equal(run.status, "RUNNING"); assert.equal(state.bootstrapReports.length, 0); const rootRevisions = state.claims[rootClaimId]!.length, structuralCounts = { claims: Object.keys(state.claims).length, obligations: Object.keys(state.obligations).length, routes: Object.keys(state.routes).length, coverage: Object.keys(state.coverage).length };
	let resumedProviderCalls = 0; const resumed = await new CorpusService(store).bootstrap("p", { async analyzeFile() { resumedProviderCalls += 1; return analysis("must-not-replay"); } }); const completed = await store.read("p"); assert.equal(resumed.bootstrapRunId, run.bootstrapRunId); assert.equal(resumedProviderCalls, 0, "completed range analysis must not replay"); assert.equal(providerCalls, 1); assert.equal(completed.claims[rootClaimId]!.length, rootRevisions, "reduction/case-split revisions must not append twice"); assert.deepEqual({ claims: Object.keys(completed.claims).length, obligations: Object.keys(completed.obligations).length, routes: Object.keys(completed.routes).length, coverage: Object.keys(completed.coverage).length }, structuralCounts); assert.equal(completed.bootstrapReports.length, 1); assert.equal(Object.values(completed.artifacts).filter((artifact) => artifact.artifactType === "BOOTSTRAP_REPORT").length, 1); assert.equal(completed.events.filter((event) => event.type === "research/bootstrap_completed").length, 1); assert.equal(completed.bootstrapRuns[run.bootstrapRunId]?.status, "COMPLETED");
	await new CorpusService(store).bootstrap("p", structural); const repeated = await store.read("p"); assert.equal(providerCalls, 1); assert.equal(repeated.claims[rootClaimId]!.length, rootRevisions); assert.equal(repeated.bootstrapReports.length, 1);
});

test("state replacement retries transient locks and preserves canonical state on persistent failure", async (t) => {
	const directory = await mkdtemp(join(tmpdir(), "mrr-store-fault-")); t.after(() => rm(directory, { recursive: true, force: true })); let transient = 0;
	const store = new ResearchStore(directory, { stateWriteFaultInjector(phase) { if (phase === "BEFORE_REPLACE" && transient++ < 2) throw errno("EPERM"); } }); await store.create("p", "p"); await store.transaction("p", (draft) => { (draft as MutableState).cycle = 1; }); assert.equal((await store.read("p")).cycle, 1); assert.ok(transient >= 3);
	const persistent = new ResearchStore(directory, { stateWriteFaultInjector(phase) { if (phase === "BEFORE_REPLACE") throw errno("EPERM"); } }); await assert.rejects(persistent.transaction("p", (draft) => { (draft as MutableState).cycle = 2; }), (error: any) => error.code === "EPERM"); assert.equal((await new ResearchStore(directory).read("p")).cycle, 1); const names = await readdir(join(directory, "projects", "p")); assert.ok(names.some((name) => name.endsWith(".tmp")), "failed tmp remains identifiable and non-authoritative");
});

test("state replacement crash points never authorize a tmp file or corrupt canonical JSON", async (t) => {
	const directory = await mkdtemp(join(tmpdir(), "mrr-store-crash-")); t.after(() => rm(directory, { recursive: true, force: true })); const base = new ResearchStore(directory); await base.create("p", "p");
	for (const phase of ["AFTER_TMP_WRITE", "BEFORE_REPLACE"] as const) { const crashing = new ResearchStore(directory, { stateWriteFaultInjector(at) { if (at === phase) throw new Error(`crash:${phase}`); } }); await assert.rejects(crashing.transaction("p", (draft) => { (draft as MutableState).cycle = 10; }), new RegExp(`crash:${phase}`)); assert.equal((await base.read("p")).cycle, 0); }
	const afterReplace = new ResearchStore(directory, { stateWriteFaultInjector(at) { if (at === "AFTER_REPLACE") throw new Error("crash:AFTER_REPLACE"); } }); await assert.rejects(afterReplace.transaction("p", (draft) => { (draft as MutableState).cycle = 11; }), /crash:AFTER_REPLACE/u); assert.equal((await base.read("p")).cycle, 11, "a completed replace remains the sole canonical state even if acknowledgement crashes");
});

test("separate store instances serialize concurrent per-project mutations", async (t) => {
	const directory = await mkdtemp(join(tmpdir(), "mrr-store-serial-")); t.after(() => rm(directory, { recursive: true, force: true })); const left = new ResearchStore(directory), right = new ResearchStore(directory); await left.create("p", "p");
	await Promise.all(Array.from({ length: 100 }, (_, index) => (index % 2 === 0 ? left : right).transaction("p", async (draft) => { const before = draft.cycle; await new Promise((resolve) => setTimeout(resolve, index % 3)); (draft as MutableState).cycle = before + 1; })));
	assert.equal((await left.read("p")).cycle, 100);
});

test("Windows production store stress survives hundreds of sequential writes", { skip: process.platform !== "win32" }, async (t) => {
	const directory = await mkdtemp(join(tmpdir(), "mrr-windows-store-stress-")); t.after(() => rm(directory, { recursive: true, force: true })); const store = new ResearchStore(directory); await store.create("p", "p"); for (let index = 0; index < 200; index += 1) await store.transaction("p", (draft) => { (draft as MutableState).cycle = draft.cycle + 1; }); const state = await store.read("p"); assert.equal(state.cycle, 200); assert.equal(JSON.parse(await readFile(join(directory, "projects", "p", "state.json"), "utf8")).cycle, 200);
});

test("restart reclaims orphan RUNNING work, calls provider path, and never replays COMPLETED tasks", async (t) => {
	const directory = await mkdtemp(join(tmpdir(), "mrr-orphan-")); t.after(() => rm(directory, { recursive: true, force: true })); const store = new ResearchStore(directory), seed = new ResearchRuntime({ store, proofRunner: async () => { throw new Error("unused"); } }); await seed.createProject("p", "p"); let state = await seed.setRootObjective("p", "Root theorem"), rootObligation = Object.values(state.obligations)[0]!; const cycleId = stableId("cycle", "p", "1"), logicalJobId = stableId("job", "p", cycleId, rootObligation.obligationId), attemptId = stableId("attempt", logicalJobId, "1"), scratchPath = await store.createScratch("p", attemptId), now = new Date().toISOString();
	const decision: DecisionBasis = { decisionId: stableId("decision", cycleId), cycleId, action: "ATTACK_OBLIGATION", direction: "MODEL_DIRECTED", targetObligationId: rootObligation.obligationId, targetClaimId: rootObligation.claimId, frontier: [rootObligation.obligationId], relevantClaims: [rootObligation.claimId], failedRoutes: [], reason: "resume", budgetAllocated: 1 };
	await store.transaction("p", (draft) => { const mutable = draft as MutableState; mutable.cycle = 1; mutable.activeCycleId = cycleId; mutable.decisions = [decision]; mutable.jobs = { [logicalJobId]: { logicalJobId, projectId: "p", cycleId, obligationId: rootObligation.obligationId, status: "RUNNING", createdAt: now } }; mutable.attempts = { [attemptId]: { attemptId, logicalJobId, ordinal: 1, scratchPath, status: "RUNNING", artifactRefs: [], startedAt: now, executorInstanceId: "dead-executor", processInstanceId: 999999 } }; mutable.executionTasks = { completed: { executionTaskId: "completed", logicalJobId, attemptId, kind: "WORKER", logicalTaskId: "done", status: "COMPLETED", inputHash: "done", startedAt: now, completedAt: now, executorInstanceId: "dead-executor" }, orphan: { executionTaskId: "orphan", logicalJobId, attemptId, kind: "WORKER", logicalTaskId: "unfinished", status: "RUNNING", inputHash: "unfinished", startedAt: now, executorInstanceId: "dead-executor" } }; });
	let calls = 0; const resumed = new ResearchRuntime({ store, maxCycles: 1, proofRunner: async (request) => { calls += 1; return unresolved(request.obligation.obligationId, request.targetClaimId, request.logicalJobId, request.attemptId); } }); await resumed.run("p", 1); state = await store.read("p"); assert.equal(calls, 1); assert.equal(state.executionTasks.completed?.status, "COMPLETED"); assert.equal(state.executionTasks.orphan?.status, "FAILED_RETRYABLE"); assert.ok(state.events.some((event) => event.type === "research/orphan_execution_reclaimed"));
});

test("copied real broken Gemini cycle-5 state reclaims its one stale RUNNING task", async (t) => {
	const root = process.cwd().endsWith(`${join("", "backend")}`) ? join(process.cwd(), "..") : process.cwd(), original = join(root, "AUDIT_METADATA", "critical-layer-proof-as-test", "20260826-174219-b1dc2cb"), evidence = join(original, "evidence", "75-pre-kill-project.json"), originalProject = join(root, ".math-agent", "research", "projects", "critical-layer-proof-as-test-20260826");
	try { await readFile(evidence); await readdir(originalProject); } catch { t.skip("REAL_BROKEN_STATE_RECOVERY_TEST=NOT_AVAILABLE"); return; }
	const directory = await mkdtemp(join(tmpdir(), "mrr-real-gemini-copy-")), copiedProject = join(directory, "projects", "critical-layer-proof-as-test-20260826"); t.after(() => rm(directory, { recursive: true, force: true })); await mkdir(join(directory, "projects"), { recursive: true }); await cp(originalProject, copiedProject, { recursive: true, force: false });
	const statePath = join(copiedProject, "state.json"), copiedState = JSON.parse(await readFile(statePath, "utf8")) as ResearchProjectState, originalPrefix = originalProject.toLocaleLowerCase(); for (const artifact of Object.values(copiedState.artifacts) as any[]) if (typeof artifact.bodyPath === "string" && artifact.bodyPath.toLocaleLowerCase().startsWith(originalPrefix)) artifact.bodyPath = join(copiedProject, artifact.bodyPath.slice(originalProject.length)); for (const attempt of Object.values(copiedState.attempts) as any[]) if (typeof attempt.scratchPath === "string" && attempt.scratchPath.toLocaleLowerCase().startsWith(originalPrefix)) attempt.scratchPath = join(copiedProject, attempt.scratchPath.slice(originalProject.length)); await writeFile(statePath, `${JSON.stringify(copiedState, null, 2)}\n`);
	const beforeTasks = Object.values(copiedState.executionTasks); assert.deepEqual({ cycle: copiedState.cycle, plans: Object.keys(copiedState.executionPlans).length, tasks: beforeTasks.length, completed: beforeTasks.filter((item) => item.status === "COMPLETED").length, retryable: beforeTasks.filter((item) => item.status === "FAILED_RETRYABLE").length, running: beforeTasks.filter((item) => item.status === "RUNNING").length }, { cycle: 5, plans: 6, tasks: 36, completed: 23, retryable: 12, running: 1 }); const acceptedBefore = Object.keys(copiedState.acceptedEffects);
	let calls = 0; const store = new ResearchStore(directory), runtime = new ResearchRuntime({ store, maxCycles: 1, proofRunner: async (request) => { calls += 1; return unresolved(request.obligation.obligationId, request.targetClaimId, request.logicalJobId, request.attemptId); } }); await runtime.run(copiedState.projectId, 1); const after = await store.read(copiedState.projectId), recoveredStatus = after.executionTasks[beforeTasks.find((item) => item.status === "RUNNING")!.executionTaskId]?.status; assert.equal(calls, 1); assert.equal(Object.values(after.executionTasks).filter((item) => item.status === "COMPLETED").length >= 23, true); assert.notEqual(recoveredStatus, "RUNNING", "the stale task must be reclaimed and then advance or fail normally"); assert.ok(recoveredStatus === "COMPLETED" || recoveredStatus === "FAILED_RETRYABLE" || recoveredStatus === "INTERRUPTED"); assert.ok(acceptedBefore.every((effectId) => after.acceptedEffects[effectId] !== undefined), "all pre-crash canonical effects remain exactly once"); assert.ok(Object.keys(after.acceptedEffects).length <= acceptedBefore.length + 1, "one resumed tactical outcome may add one stable effect but cannot duplicate history"); assert.ok(after.events.some((event) => event.type === "research/orphan_execution_reclaimed"));
});

function analysis(key: string) { return { proposals: [{ entityKey: key, kind: "CLAIM" as const, statement: `Lemma ${key}`, dependencyHints: [] }], dependencies: [], warnings: [] }; }
function fullProposal<T extends Record<string, any>>(value: T): T & { targetHint: string; routeFamily: string; mechanism: string; failureMechanism: string; cases: string[] } { return { targetHint: "", routeFamily: "", mechanism: "", failureMechanism: "", cases: [], ...value }; }
function errno(code: string): NodeJS.ErrnoException { return Object.assign(new Error(code), { code }); }
function unresolved(obligationId: string, targetClaimId: string, logicalJobId: string, attemptId: string): TacticalResearchResult { const now = new Date().toISOString(); return { obligationId, targetClaimId, targetStatus: "TARGET_UNRESOLVED", contributions: [], routeObservations: [], executionReceipt: { executionReceiptId: stableId("receipt", attemptId), logicalJobId, attemptId, taskIds: [], evidenceReceiptIds: [], startedAt: now, completedAt: now }, feedback: "no result" }; }
type MutableState = { -readonly [K in keyof ResearchProjectState]: ResearchProjectState[K] };
function fixturePath(name: string): string { return join(process.cwd(), process.cwd().endsWith(`${join("", "backend")}`) ? "test" : join("backend", "test"), "fixtures", name); }
