import { spawn } from "node:child_process";
import { stableId } from "./ids.js";
import { activeAuthorityForClaim, ResearchInvariantValidator } from "./invariants.js";
import { authoritativeClaimClosure, ResearchStateReducer, rootSynthesisReadiness } from "./reducer.js";
import { ResearchStore } from "./store.js";
import type { ArtifactRef, AssumptionDischargeDependency, ClaimSnapshot, FinalProofAuthority, ResearchProjectState, RootObjectiveContract, TrustReceipt } from "./types.js";
import type { CorpusArchiveSink } from "./corpus-archive-types.js";

export interface SynthesisManifest { readonly manifestId: string; readonly rootObjective: string; readonly rootObjectiveContract: RootObjectiveContract; readonly root: ClaimSnapshot; readonly orderedClaims: readonly ClaimSnapshot[]; readonly proofArtifacts: readonly ArtifactRef[]; readonly sourceArtifacts: readonly ArtifactRef[]; readonly coverageIds: readonly string[]; readonly allowedAssumptions: readonly string[]; readonly assumptionStatus: ReturnType<typeof rootSynthesisReadiness>["closureRequiredAssumptions"]; readonly assumptionDischarges: readonly AssumptionDischargeDependency[]; readonly assumptions: readonly string[]; readonly createdAt: string; }
export interface SynthesisResult { readonly proof: string; readonly usedArtifactIds: readonly string[]; readonly theoremStatement?: string; readonly assumptions?: readonly string[]; }
export interface SynthesisAgent { synthesize(manifest: SynthesisManifest, bodies: Readonly<Record<string, string>>, signal?: AbortSignal): Promise<string | SynthesisResult>; }
export interface FinalAuditor { audit(request: { readonly manifest: SynthesisManifest; readonly candidate: ArtifactRef; readonly body: string; readonly dependencyBodies: Readonly<Record<string, string>> }, signal?: AbortSignal): Promise<{ readonly verdict: TrustReceipt["verdict"]; readonly feedback: string; readonly profile: string; readonly evidenceInspected?: readonly ArtifactRef[]; readonly toolReceiptIds?: readonly string[] }>; }
export type RootReadinessReport = ReturnType<typeof rootSynthesisReadiness> & { readonly rootObjectiveContract?: RootObjectiveContract; readonly dependencyBlockers: readonly string[]; readonly coverageBlockers: readonly string[]; readonly invalidArtifacts: readonly string[]; readonly staleTrustReceipts: readonly string[]; readonly missingFinalAudits: readonly string[]; };

export class RootClosureService {
	private readonly reducer: ResearchStateReducer;
	constructor(private readonly store: ResearchStore, private readonly synthesizer: SynthesisAgent, private readonly primaryAuditor: FinalAuditor, private readonly finalAuditor: FinalAuditor, private readonly archiveSink?: CorpusArchiveSink) { this.reducer = new ResearchStateReducer(store, { ...(archiveSink === undefined ? {} : { archiveSink }) }); }

	async readiness(projectId: string): Promise<RootReadinessReport> {
		const state = await this.store.read(projectId), base = rootSynthesisReadiness(state), invariant = await new ResearchInvariantValidator(this.store).check(projectId), dependencyBlockers = base.blockers.filter((item) => item.includes("dependency") || item.includes("Root claim") || item.includes("ROOT_NOT_CLOSED")), coverageBlockers = base.blockers.filter((item) => item.includes("COVERAGE")), invalidArtifacts: string[] = invariant.violations.map((item) => `${item.code}${item.entityId === undefined ? "" : `(${item.entityId})`}: ${item.message}`);
		const brokenActiveClaims = new Set<string>(); for (const violation of invariant.violations) for (const authority of Object.values(state.authorityReceipts)) { if (state.authorityValidation[authority.authorityReceiptId]?.status !== "ACTIVE") continue; const authorityArtifactIds = new Set([authority.artifact.artifactId, authority.sourceArtifact.artifactId, ...authority.evidenceRefs.map((item) => item.artifactId)]); if (violation.entityId === authority.authorityReceiptId || (violation.entityId !== undefined && authorityArtifactIds.has(violation.entityId))) brokenActiveClaims.add(authority.claimId); } if (brokenActiveClaims.size > 0) { for (const claimId of brokenActiveClaims) await this.reducer.invalidate(projectId, claimId, "Authority artifact missing or hash-invalid"); return this.readiness(projectId); }
		const closure = state.rootClaimId === undefined ? [] : authoritativeClaimClosure(state, state.rootClaimId); for (const claim of closure) for (const ref of claim.evidenceRefs) try { await this.store.resolveArtifact(projectId, ref); } catch (error) { invalidArtifacts.push(String(error)); }
		const activeTrustIds = new Set(closure.flatMap((claim) => activeAuthorityForClaim(state, claim.claimId, claim.revision)?.trustReceiptIds ?? [])), staleTrustReceipts = Object.values(state.trustReceipts).filter((item) => item.stale && activeTrustIds.has(item.receiptId)).map((item) => item.receiptId), missingFinalAudits = state.currentFinalProofAuthority?.status === "ACTIVE" ? [] : ["Fresh final audit has not yet accepted a current synthesis"];
		const blockers = [...base.blockers, ...invalidArtifacts, ...staleTrustReceipts.map((id) => `Stale trust receipt: ${id}`)];
		return { ...base, ready: blockers.length === 0, rootObjectiveContract: state.rootObjectiveContract, dependencyBlockers, coverageBlockers, invalidArtifacts, staleTrustReceipts, missingFinalAudits, blockers };
	}

	async synthesizeAndAudit(projectId: string, signal?: AbortSignal): Promise<ResearchProjectState> {
		const state = await this.store.read(projectId); const readiness = await this.readiness(projectId); if (!readiness.ready) throw new Error(`Root synthesis blocked: ${readiness.blockers.join("; ")}`);
		const rootId = state.rootClaimId as string; const root = state.claims[rootId]?.at(-1), contract = state.rootObjectiveContract; if (root === undefined) throw new Error("Root snapshot missing"); if (contract === undefined || contract.status !== "VALID") throw new Error("ROOT_CONTRACT_NEEDS_REVALIDATION"); if (normalizeMath(root.statement) !== contract.normalizedStatement) throw new Error("ROOT_STATEMENT_MISMATCH: root snapshot differs from immutable contract");
		const claims = authoritativeClaimClosure(state, rootId); const refs = await transitiveArtifactRefs(this.store, projectId, claims.flatMap((claim) => claim.evidenceRefs)); const bodies: Record<string, string> = {}; for (const ref of refs) bodies[ref.artifactId] = (await this.store.resolveArtifact(projectId, ref)).body;
		const remainingAssumptions = readiness.closureRequiredAssumptions.filter((item) => item.status === "ALLOWED").map((item) => item.assumption), assumptionDischarges = manifestDischarges(state, readiness.closureRequiredAssumptions), manifest: SynthesisManifest = { manifestId: stableId("synthesis", projectId, contract.contractId, String(root.revision), ...refs.map((ref) => ref.contentHash)), rootObjective: contract.statement, rootObjectiveContract: contract, root, orderedClaims: claims, proofArtifacts: refs.filter((ref) => state.artifacts[ref.artifactId]?.artifactType === "PROMOTED_PROOF" || state.artifacts[ref.artifactId]?.artifactType === "CANDIDATE_PROOF" || state.artifacts[ref.artifactId]?.artifactType === "WORKER_CANDIDATE"), sourceArtifacts: refs.filter((ref) => state.artifacts[ref.artifactId]?.artifactType === "CORPUS_SOURCE" || state.artifacts[ref.artifactId]?.artifactType === "LITERATURE_SOURCE" || state.artifacts[ref.artifactId]?.artifactType === "COMPUTATION_RESULT"), coverageIds: Object.values(state.coverage).filter((item) => item.disposition === "CLOSED").map((item) => item.coverageId), allowedAssumptions: contract.allowedAssumptions, assumptionStatus: readiness.closureRequiredAssumptions, assumptionDischarges, assumptions: remainingAssumptions, createdAt: new Date().toISOString() };
		await this.store.putArtifact(projectId, { artifactType: "SYNTHESIS_MANIFEST", body: `${JSON.stringify(manifest, null, 2)}\n`, provenance: "RootClosureService", references: refs });
		const synthesized = await this.synthesizer.synthesize(manifest, bodies, signal), normalized: SynthesisResult = typeof synthesized === "string" ? { proof: synthesized, usedArtifactIds: refs.map((ref) => ref.artifactId) } : synthesized, allowed = new Set(refs.map((ref) => ref.artifactId)); if (normalized.usedArtifactIds.some((id) => !allowed.has(id))) throw new Error(`Synthesizer reported unknown/out-of-manifest artifacts: ${normalized.usedArtifactIds.filter((id) => !allowed.has(id)).join(", ")}`); const requiredDischargeArtifacts = [...new Set(assumptionDischarges.map((item) => item.witnessArtifactId))]; if (requiredDischargeArtifacts.some((id) => !normalized.usedArtifactIds.includes(id))) throw new Error(`SYNTHESIS_DISCHARGE_EVIDENCE_MISSING: ${requiredDischargeArtifacts.filter((id) => !normalized.usedArtifactIds.includes(id)).join(", ")}`); if (normalized.theoremStatement !== undefined && normalizeMath(normalized.theoremStatement) !== contract.normalizedStatement) throw new Error("ROOT_STATEMENT_MISMATCH: synthesizer declared a different theorem"); if (normalized.assumptions !== undefined && normalized.assumptions.some((item) => !contract.allowedAssumptions.some((allowedAssumption) => normalizeMath(allowedAssumption) === normalizeMath(item)))) throw new Error("ROOT_ASSUMPTION_ESCALATION: synthesizer declared an unauthorized assumption"); const usedRefs = refs.filter((ref) => normalized.usedArtifactIds.includes(ref.artifactId));
		const body = normalized.proof, candidate = await this.store.putArtifact(projectId, { artifactType: "FINAL_PROOF", body, provenance: "Synthesizer", references: usedRefs, metadata: { usedArtifactIds: normalized.usedArtifactIds, synthesisManifestId: manifest.manifestId, rootContractId: contract.contractId, theoremStatement: contract.statement, assumptions: remainingAssumptions } });
		const primary = await this.primaryAuditor.audit({ manifest, candidate, body, dependencyBodies: bodies }, signal); const final = await this.finalAuditor.audit({ manifest, candidate, body, dependencyBodies: bodies }, signal); const sourceRefs = manifest.sourceArtifacts.filter((ref) => normalized.usedArtifactIds.includes(ref.artifactId)), dischargeRefs = refs.filter((ref) => requiredDischargeArtifacts.includes(ref.artifactId));
		const auditArtifact = await this.store.putArtifact(projectId, { artifactType: "AUDIT_RECEIPT", body: `${JSON.stringify({ primary, final, candidate }, null, 2)}\n`, provenance: "fresh-final-audit", references: [candidate, ...(primary.evidenceInspected ?? []), ...(final.evidenceInspected ?? [])] });
		if (primary.verdict !== "CORRECT" || final.verdict !== "CORRECT" || !covers(sourceRefs, primary.evidenceInspected ?? []) || !covers(uniqueRefs([...sourceRefs, ...dischargeRefs]), final.evidenceInspected ?? [])) {
			const blockerId = stableId("obligation", projectId, rootId, candidate.contentHash, "final-audit-gap");
			return (await this.store.transaction(projectId, (draft) => { const mutable = draft as MutableState, timestamp = new Date().toISOString(); mutable.obligations = { ...draft.obligations, [blockerId]: { obligationId: blockerId, claimId: rootId, kind: "AUDIT", statement: `Repair synthesis candidate ${candidate.artifactId} using audit receipt ${auditArtifact.artifactId}: primary=${primary.feedback}; final=${final.feedback}`, status: "OPEN", priority: 100, createdAt: timestamp, updatedAt: timestamp, causalReason: "Fresh final audit rejected synthesis" } }; mutable.events = [...draft.events, { eventId: stableId("event", projectId, "final-audit-rejected", candidate.contentHash), type: "research/final_audit_rejected", projectId, timestamp, detail: { rootClaimId: rootId, candidateArtifactId: candidate.artifactId, auditReceiptArtifactId: auditArtifact.artifactId, primaryProfile: primary.profile, primaryVerdict: primary.verdict, primaryFeedback: primary.feedback, finalProfile: final.profile, finalVerdict: final.verdict, finalFeedback: final.feedback } }]; mutable.status = "PARTIAL"; })).state;
		}
		const receipts: TrustReceipt[] = [primary, final].map((audit, index) => ({ receiptId: stableId("receipt", candidate.artifactId, index === 0 ? "synthesis-primary" : "fresh-final", audit.profile), claimId: rootId, candidate, verifierProfile: audit.profile, evidenceInspected: audit.evidenceInspected ?? [], verifierReadEvidence: audit.evidenceInspected ?? [], toolReceiptIds: audit.toolReceiptIds ?? [], verdict: audit.verdict, independentContext: true, stale: false, createdAt: new Date().toISOString() }));
		const promoted = (await this.reducer.apply({ projectId, cycleId: stableId("cycle", projectId, "synthesis", manifest.manifestId), logicalJobId: stableId("job", projectId, "synthesis", manifest.manifestId), effectSlot: "final-root-promotion", outcome: { type: "PROVED_CLAIM", claimId: rootId, statement: contract.statement, candidate, receipts, dependencies: root.dependencies, assumptions: remainingAssumptions, assumptionDischarges, scope: "ROOT_SYNTHESIS" } })).state;
		const promotedRoot = promoted.claims[rootId]?.at(-1), rootAuthority = promotedRoot === undefined ? undefined : activeAuthorityForClaim(promoted, rootId, promotedRoot.revision); if (promotedRoot === undefined || rootAuthority === undefined) throw new Error("Final proof promotion did not produce current root authority");
		const closed = (await this.store.transaction(projectId, (draft) => { const mutable = draft as MutableState, now = new Date().toISOString(), authority: FinalProofAuthority = { finalProofAuthorityId: stableId("final-proof-authority", projectId, candidate.artifactId, rootAuthority.authorityReceiptId), artifact: candidate, rootClaimId: rootId, rootClaimRevision: promotedRoot.revision, rootAuthorityReceiptId: rootAuthority.authorityReceiptId, status: "ACTIVE", createdAt: now, changedAt: now }, history = draft.finalProofHistory.map((item) => item.status === "ACTIVE" ? { ...item, status: "STALE" as const, reason: `Superseded by ${authority.finalProofAuthorityId}`, changedAt: now } : item); mutable.finalProofArtifact = candidate; mutable.finalProofHistory = [...history.filter((item) => item.finalProofAuthorityId !== authority.finalProofAuthorityId), authority]; mutable.currentFinalProofAuthority = authority; })).state, finalAuthority = closed.currentFinalProofAuthority;
		if (finalAuthority !== undefined) try { await this.archiveSink?.recordPromotionClosure(closed, finalAuthority); await this.archiveSink?.reconcile(projectId); } catch { /* Final proof authority is already durable; corpus delivery is retryable. */ }
		return closed;
	}
}

export interface FormalVerification { readonly success: boolean; readonly exitCode: number | null; readonly stdout: string; readonly stderr: string; readonly timedOut: boolean; }
export async function runLeanVerifier(request: { readonly executable: string; readonly args: readonly string[]; readonly cwd: string; readonly timeoutMs?: number }): Promise<FormalVerification> {
	const timeoutMs = request.timeoutMs ?? 60_000; return new Promise((resolvePromise, reject) => { const child = spawn(request.executable, [...request.args], { cwd: request.cwd, shell: false, stdio: ["ignore", "pipe", "pipe"], windowsHide: true }); let stdout = "", stderr = "", timedOut = false; child.stdout.on("data", (chunk: Buffer) => { stdout += chunk.toString(); }); child.stderr.on("data", (chunk: Buffer) => { stderr += chunk.toString(); }); const timer = setTimeout(() => { timedOut = true; child.kill(); }, timeoutMs); child.once("error", reject); child.once("close", (exitCode) => { clearTimeout(timer); resolvePromise({ success: exitCode === 0 && !timedOut, exitCode, stdout, stderr, timedOut }); }); });
}

function uniqueRefs(refs: readonly ArtifactRef[]): ArtifactRef[] { const seen = new Set<string>(); return refs.filter((ref) => { const key = `${ref.artifactId}:${ref.contentHash}`; if (seen.has(key)) return false; seen.add(key); return true; }); }
function manifestDischarges(state: ResearchProjectState, assessments: ReturnType<typeof rootSynthesisReadiness>["closureRequiredAssumptions"]): AssumptionDischargeDependency[] { const result: AssumptionDischargeDependency[] = []; for (const assessment of assessments) if (assessment.status === "DISCHARGED") for (const dependentClaimId of assessment.requiredBy) { const dependent = state.claims[dependentClaimId]?.at(-1); if (dependent === undefined) continue; for (const witness of assessment.witnesses) result.push({ assumption: assessment.assumption, normalizedAssumption: assessment.normalizedAssumption, dependentClaimId, dependentClaimRevision: dependent.revision, witnessClaimId: witness.claimId, witnessClaimRevision: witness.claimRevision, witnessAuthorityReceiptId: witness.authorityReceiptId, witnessArtifactId: witness.proofArtifactId, witnessArtifactHash: witness.proofArtifactHash, acceptedEffectId: witness.acceptedEffectId, witnessStatement: witness.statement }); } return result; }
async function transitiveArtifactRefs(store: ResearchStore, projectId: string, roots: readonly ArtifactRef[]): Promise<ArtifactRef[]> { const result: ArtifactRef[] = [], seen = new Set<string>(), visit = async (ref: ArtifactRef): Promise<void> => { const key = `${ref.artifactId}:${ref.contentHash}`; if (seen.has(key)) return; seen.add(key); const resolved = await store.resolveArtifact(projectId, ref); result.push(ref); for (const dependency of resolved.artifact.references) await visit(dependency); }; for (const root of roots) await visit(root); return result; }
function covers(required: readonly ArtifactRef[], inspected: readonly ArtifactRef[]): boolean { const keys = new Set(inspected.map((item) => `${item.artifactId}:${item.contentHash}`)); return required.every((item) => keys.has(`${item.artifactId}:${item.contentHash}`)); }
function normalizeMath(value: string): string { return value.trim().replace(/\s+/gu, " "); }
type MutableState = { -readonly [K in keyof ResearchProjectState]: ResearchProjectState[K] };
