import { readFile, readdir, realpath, stat } from "node:fs/promises";
import { extname, join, relative, resolve, sep } from "node:path";
import { stableId, sha256 } from "./ids.js";
import { invalidateClaimAuthorityInState, reconcileProjectTruthState } from "./reducer.js";
import type { ArtifactRef, BootstrapDependencyProposal, BootstrapProposal, BootstrapReport, ClaimSnapshot, CorpusRecord, CoverageRecord, ImportAuthority, ResearchArtifact, ResearchObligation, ResearchProjectState, ResearchRoute, TrustReceipt } from "./types.js";
import { ResearchStore } from "./store.js";

const SUPPORTED = new Map([[".md", "md"], [".txt", "txt"], [".tex", "tex"], [".lean", "lean"]] as const);
export interface SemanticFileAnalysis { readonly proposals: readonly Omit<BootstrapProposal, "source" | "authority">[]; readonly dependencies: readonly BootstrapDependencyProposal[]; readonly warnings?: readonly string[]; }
export interface CorpusBootstrapper { analyzeFile(request: { readonly projectId: string; readonly record: CorpusRecord; readonly body: string; readonly range: { readonly startLine: number; readonly endLine: number } }, signal?: AbortSignal): Promise<SemanticFileAnalysis>; review?(request: { readonly projectId: string; readonly proposals: readonly BootstrapProposal[]; readonly dependencies: readonly BootstrapDependencyProposal[]; readonly rootObjective: string }, signal?: AbortSignal): Promise<{ readonly frontierEntityKeys?: readonly string[]; readonly warnings?: readonly string[] }>; }

export class CorpusService {
	constructor(private readonly store: ResearchStore) {}
	async state(projectId: string): Promise<ResearchProjectState> { return this.store.read(projectId); }

	async attach(projectId: string, roots: readonly string[]): Promise<ResearchProjectState> { const resolved: string[] = []; for (const root of roots) { const actual = await realpath(resolve(root)); if (!(await stat(actual)).isDirectory()) throw new Error(`Corpus root is not a directory: ${root}`); resolved.push(actual); } return (await this.store.transaction(projectId, (draft) => { (draft as MutableState).corpusRoots = [...new Set([...draft.corpusRoots, ...resolved])]; })).state; }

	async ingest(projectId: string, authority: ImportAuthority = "PROVISIONAL_IMPORTED"): Promise<{ readonly imported: number; readonly changed: readonly CorpusRecord[]; readonly state: ResearchProjectState }> {
		const before = await this.store.read(projectId); const records: Record<string, CorpusRecord> = {}, artifacts: Record<string, ResearchArtifact> = {}; const changed: CorpusRecord[] = [];
		for (const [rootIndex, root] of before.corpusRoots.entries()) for (const path of await walk(root)) { const format = SUPPORTED.get(extname(path).toLowerCase() as ".md"); if (format === undefined) continue; const actual = await realpath(path); if (!inside(root, actual)) throw new Error(`Corpus symlink escapes configured root: ${path}`); const body = await readFile(actual, "utf8"), relativePath = `${rootIndex}:${relative(root, actual).replaceAll("\\", "/")}`, artifactId = stableId("corpus", projectId, relativePath), contentHash = sha256(body), previous = before.corpus[artifactId], info = await stat(actual); const record: CorpusRecord = { artifactId, relativePath, resolvedPath: actual, format, contentHash, size: info.size, provenance: `corpus:${relativePath}`, importedAt: new Date().toISOString(), importVersion: (previous?.importVersion ?? 0) + (previous?.contentHash === contentHash ? 0 : 1), authority, ...(previous !== undefined && previous.contentHash !== contentHash ? { changedFromHash: previous.contentHash } : {}) }; records[artifactId] = record; artifacts[artifactId] = { artifactId, contentHash, artifactType: "CORPUS_SOURCE", bodyPath: actual, provenance: record.provenance, authority, references: [], createdAt: record.importedAt }; if (record.changedFromHash !== undefined) changed.push(record); }
		const state = (await this.store.transaction(projectId, (draft) => { const mutable = draft as MutableState; mutable.corpus = records; mutable.artifacts = { ...draft.artifacts, ...artifacts }; if (changed.length > 0) invalidateChangedCorpus(mutable, changed); })).state; return { imported: Object.keys(records).length, changed, state };
	}

	async list(projectId: string): Promise<readonly CorpusRecord[]> { return Object.values((await this.store.read(projectId)).corpus).sort((a, b) => a.relativePath.localeCompare(b.relativePath)); }
	async read(projectId: string, artifactId: string, offset = 0, limit?: number): Promise<{ readonly record: CorpusRecord; readonly content: string; readonly lineStart: number; readonly lineEnd: number }> { const state = await this.store.read(projectId), record = state.corpus[artifactId]; if (record === undefined) throw new Error(`Corpus artifact not found: ${artifactId}`); const lines = (await this.store.resolveArtifact(projectId, record)).body.split(/\r?\n/u), end = Math.min(lines.length, offset + (limit ?? lines.length)); return { record, content: lines.slice(offset, end).join("\n"), lineStart: offset, lineEnd: end }; }
	async search(projectId: string, query: string, exact = false, limit = 50): Promise<readonly { readonly artifactId: string; readonly relativePath: string; readonly line: number; readonly text: string }[]> { if (query.length === 0) return []; const needle = exact ? query : query.toLocaleLowerCase(), matches: { artifactId: string; relativePath: string; line: number; text: string }[] = []; for (const record of await this.list(projectId)) { const body = (await this.store.resolveArtifact(projectId, record)).body; for (const [index, text] of body.split(/\r?\n/u).entries()) { if ((exact ? text : text.toLocaleLowerCase()).includes(needle)) matches.push({ artifactId: record.artifactId, relativePath: record.relativePath, line: index + 1, text }); if (matches.length >= limit) return matches; } } return matches; }

	async bootstrap(projectId: string, bootstrapper?: CorpusBootstrapper, signal?: AbortSignal): Promise<BootstrapReport> {
		const state = await this.store.read(projectId); if (state.rootObjective === undefined || state.rootClaimId === undefined) throw new Error("Set a root objective before bootstrap"); if (Object.keys(state.corpus).length === 0) throw new Error("Ingest a corpus before bootstrap");
		const stages = ["MANIFEST_INDEX", "PER_FILE_SEMANTIC_ANALYSIS", "ENTITY_MERGE", "DEPENDENCY_RECONSTRUCTION", "FAILED_ROUTE_RECONSTRUCTION", "FRONTIER_PROPOSAL", "CONSISTENCY_REVIEW", "PROVISIONAL_IMPORT"];
		const rawProposals: BootstrapProposal[] = [], rawDependencies: BootstrapDependencyProposal[] = [], warnings: string[] = [], analyzedRanges: { artifactId: string; startLine: number; endLine: number }[] = [];
		for (const record of Object.values(state.corpus).sort((a, b) => a.relativePath.localeCompare(b.relativePath))) {
			const body = (await this.store.resolveArtifact(projectId, record)).body, lines = body.split(/\r?\n/u);
			for (const range of bootstrapRanges(lines)) {
				const boundedBody = lines.slice(range.startLine - 1, range.endLine).join("\n"); analyzedRanges.push({ artifactId: record.artifactId, ...range });
				let analysis: SemanticFileAnalysis;
				try {
					analysis = bootstrapper === undefined ? deterministicAnalysis(boundedBody, record, range.startLine - 1) : await bootstrapper.analyzeFile({ projectId, record, body: boundedBody, range }, signal);
					if (bootstrapper !== undefined && analysis.proposals.length === 0) { const fallback = deterministicAnalysis(boundedBody, record, range.startLine - 1); if (fallback.proposals.length > 0) { warnings.push(`Model bootstrap returned no entities for ${record.relativePath}:${range.startLine}-${range.endLine}; deterministic candidates retained.`); analysis = fallback; } }
				} catch (error) { warnings.push(`Model bootstrap failed for ${record.relativePath}:${range.startLine}-${range.endLine}: ${String(error)}; deterministic fallback used.`); analysis = deterministicAnalysis(boundedBody, record, range.startLine - 1); }
				for (const proposal of analysis.proposals) rawProposals.push({ ...proposal, source: record, sourceRange: range, authority: classifyAuthority(record.authority, proposal.kind) }); rawDependencies.push(...analysis.dependencies); warnings.push(...(analysis.warnings ?? []));
			}
		}
		const proposals = mergeProposals(rawProposals), keys = new Map(proposals.map((proposal) => [normalizeKey(proposal.entityKey), proposal])); const dependencies = mergeDependencies([...rawDependencies, ...proposals.flatMap((proposal) => proposal.dependencyHints.map((hint) => ({ fromEntity: proposal.entityKey, toEntity: hint, confidence: "EXPLICIT" as const })))]).filter((edge) => normalizeKey(edge.fromEntity) !== normalizeKey(edge.toEntity) && keys.has(normalizeKey(edge.fromEntity)) && keys.has(normalizeKey(edge.toEntity)));
		let requestedFrontier: readonly string[] = []; if (bootstrapper?.review !== undefined) try { const review = await bootstrapper.review({ projectId, proposals, dependencies, rootObjective: state.rootObjective }, signal); requestedFrontier = review.frontierEntityKeys ?? []; warnings.push(...(review.warnings ?? [])); } catch (error) { warnings.push(`Bootstrap consistency review failed closed: ${String(error)}`); }
		const now = new Date().toISOString(), createdClaimIds: string[] = [], createdObligationIds: string[] = [], createdRouteIds: string[] = [], reconstructedReductions: { parentClaimId: string; childClaimIds: readonly string[]; provisional: true }[] = [], reconstructedCoverage: { parentClaimId: string; childClaimIds: readonly string[]; coverageId: string; provisional: true }[] = []; const claimByKey = new Map<string, string>([[normalizeKey(state.rootObjective), state.rootClaimId], ["root", state.rootClaimId], ["main theorem", state.rootClaimId]]), obligationByKey = new Map<string, string>();
		await this.store.transaction(projectId, (draft) => { const mutable = draft as MutableState, claims = { ...draft.claims }, obligations = { ...draft.obligations }, routes = { ...draft.routes }, coverage = { ...draft.coverage };
			for (const proposal of proposals) { if (proposal.kind === "FAILED_ROUTE" || proposal.kind === "REDUCTION" || proposal.kind === "CASE_SPLIT") continue; const claimId = stableId("claim", projectId, proposal.entityKey, proposal.statement); claimByKey.set(normalizeKey(proposal.entityKey), claimId); if (claims[claimId] === undefined) { const snapshot: ClaimSnapshot = { claimId, revision: 1, statement: proposal.statement, role: proposal.kind === "DEFINITION" ? "DEFINITION" : proposal.kind === "OPEN_PROBLEM" ? "CONJECTURE" : "LEMMA", status: proposal.authority === "VERIFIED_IMPORTED" ? "PROVISIONAL" : "OPEN", dependencies: [], evidenceRefs: [proposal.source], auditRefs: [], assumptions: [], provenance: `bootstrap:${proposal.authority}`, createdAt: now }; claims[claimId] = [snapshot]; createdClaimIds.push(claimId); } if (proposal.kind !== "DEFINITION" && proposal.kind !== "COMPUTATIONAL_EVIDENCE") { const obligationId = stableId("obligation", projectId, claimId, "bootstrap"); obligationByKey.set(normalizeKey(proposal.entityKey), obligationId); if (obligations[obligationId] === undefined) { obligations[obligationId] = { obligationId, claimId, kind: "PROVE", statement: proposal.statement, status: "OPEN", priority: proposal.kind === "OPEN_PROBLEM" ? 80 : requestedFrontier.some((key) => normalizeKey(key) === normalizeKey(proposal.entityKey)) ? 75 : 30, createdAt: now, updatedAt: now }; createdObligationIds.push(obligationId); } } }
			for (const edge of dependencies) { const from = claimByKey.get(normalizeKey(edge.fromEntity)), to = claimByKey.get(normalizeKey(edge.toEntity)); if (from === undefined || to === undefined || edge.confidence !== "EXPLICIT") continue; const revisions = claims[from], latest = revisions?.at(-1); if (revisions !== undefined && latest !== undefined && !latest.dependencies.includes(to)) claims[from] = [...revisions.slice(0, -1), { ...latest, dependencies: [...latest.dependencies, to] }]; }
			for (const proposal of proposals.filter((item) => item.kind === "REDUCTION")) { const parentClaimId = resolveBootstrapParent(proposal, claimByKey, claims, draft.rootClaimId); if (parentClaimId === undefined) { warnings.push(`Historical reduction has no resolvable target: ${proposal.statement}`); continue; } const childClaimIds = createBootstrapChildren(projectId, proposal, proposal.dependencyHints, "LEMMA", claims, obligations, claimByKey, createdClaimIds, createdObligationIds, now); if (childClaimIds.length === 0) { warnings.push(`Historical reduction has no explicit child claims: ${proposal.statement}`); continue; } const revisions = claims[parentClaimId], parent = revisions?.at(-1); if (revisions !== undefined && parent !== undefined) claims[parentClaimId] = [...revisions, { ...parent, revision: parent.revision + 1, status: "PROVISIONAL", dependencies: [...new Set([...parent.dependencies, ...childClaimIds])], evidenceRefs: [...new Set([...parent.evidenceRefs, proposal.source])], provenance: `bootstrap-proposed-reduction:${proposal.authority}`, createdAt: now }]; reconstructedReductions.push({ parentClaimId, childClaimIds, provisional: true }); }
			for (const proposal of proposals.filter((item) => item.kind === "CASE_SPLIT")) { const parentClaimId = resolveBootstrapParent(proposal, claimByKey, claims, draft.rootClaimId); if (parentClaimId === undefined) { warnings.push(`Historical case split has no resolvable target: ${proposal.statement}`); continue; } const childClaimIds = createBootstrapChildren(projectId, proposal, proposal.cases ?? [], "CASE", claims, obligations, claimByKey, createdClaimIds, createdObligationIds, now); if (childClaimIds.length < 2) { warnings.push(`Historical case split is not exhaustive enough to import: ${proposal.statement}`); continue; } const coverageId = stableId("coverage", projectId, parentClaimId, proposal.entityKey, proposal.source.contentHash), record: CoverageRecord = { coverageId, parentClaimId, scope: proposal.statement, coverageAssertion: `Historical provisional exhaustiveness assertion: ${proposal.statement}`, childClaimIds, disposition: "OPEN", provenanceArtifact: proposal.source }; coverage[coverageId] = coverage[coverageId] ?? record; const revisions = claims[parentClaimId], parent = revisions?.at(-1); if (revisions !== undefined && parent !== undefined) claims[parentClaimId] = [...revisions, { ...parent, revision: parent.revision + 1, status: "PROVISIONAL", dependencies: [...new Set([...parent.dependencies, ...childClaimIds])], evidenceRefs: [...new Set([...parent.evidenceRefs, proposal.source])], provenance: `bootstrap-proposed-case-split:${proposal.authority}`, createdAt: now }]; reconstructedCoverage.push({ parentClaimId, childClaimIds, coverageId, provisional: true }); }
			for (const proposal of proposals.filter((item) => item.kind === "FAILED_ROUTE")) { const targetObligationId = obligationByKey.get(normalizeKey(proposal.targetHint ?? "")) ?? Object.values(obligations).find((obligation) => obligation.claimId === draft.rootClaimId)?.obligationId; if (targetObligationId === undefined) { warnings.push(`Failed route has no resolvable target: ${proposal.statement}`); continue; } const family = proposal.routeFamily ?? "historical", mechanism = proposal.mechanism ?? family, routeId = stableId("route", projectId, targetObligationId, family, proposal.statement); const route: ResearchRoute = { routeId, targetObligationId, family, mechanism, strategyDescription: proposal.statement, assumptions: [], dependencySnapshot: [], artifactRefs: [proposal.source], status: "FAILED", attemptIds: [], failureMechanism: proposal.failureMechanism ?? proposal.statement, createdAt: now, updatedAt: now }; routes[routeId] = routes[routeId] ?? route; createdRouteIds.push(routeId); }
			mutable.claims = claims; mutable.obligations = obligations; mutable.routes = routes; mutable.coverage = coverage; mutable.status = "BOOTSTRAPPED";
		});
		const after = await this.store.read(projectId), frontierObligationIds = Object.values(after.obligations).filter((item) => item.status === "OPEN").sort((a, b) => b.priority - a.priority).map((item) => item.obligationId);
		const report: BootstrapReport = { projectId, stages, inspectedArtifactIds: Object.keys(state.corpus), proposals, dependencies, createdClaimIds: [...new Set(createdClaimIds)], createdObligationIds: [...new Set(createdObligationIds)], createdRouteIds: [...new Set(createdRouteIds)], frontierObligationIds, warnings: [...warnings, "Historical prose remains provisional unless a trusted authority manifest and independent validation promote it."], modelDirected: bootstrapper !== undefined, analyzedRanges, reconstructedReductions, reconstructedCoverage, createdAt: now };
		const artifact = await this.store.putArtifact(projectId, { artifactType: "BOOTSTRAP_REPORT", body: `${JSON.stringify(report, null, 2)}\n`, provenance: bootstrapper === undefined ? "DeterministicCorpusBootstrapper" : "ModelCorpusBootstrapper", references: Object.values(state.corpus) });
		await this.store.transaction(projectId, (draft) => { const mutable = draft as MutableState; mutable.bootstrapReports = [...draft.bootstrapReports, report]; mutable.events = [...draft.events, { eventId: stableId("event", projectId, "bootstrap", artifact.contentHash), type: "research/bootstrap_completed", projectId, timestamp: now, detail: { reportArtifactId: artifact.artifactId, modelDirected: report.modelDirected, claims: createdClaimIds.length, routes: createdRouteIds.length } }]; }); return report;
	}
}

function deterministicAnalysis(body: string, source: CorpusRecord, lineOffset = 0): SemanticFileAnalysis { const proposals: Omit<BootstrapProposal, "source" | "authority">[] = [], dependencies: BootstrapDependencyProposal[] = []; const lines = body.split(/\r?\n/u); for (let index = 0; index < lines.length; index += 1) { const raw = (lines[index] ?? "").trim().replace(/^#+\s*/u, "").replace(/^[-*]\s*/u, ""); if (raw.length < 8 || raw.length > 1000) continue; const label = raw.match(/^(?:definition|def\.|theorem|lemma|proposition|corollary|claim|conjecture|open problem|定义|定理|引理)\s*([A-Za-z0-9_.-]+)?\s*:?/iu), relationTarget = raw.match(/^(.+?)\s+(?:reduces? to|splits? into|has cases?)\b/iu)?.[1]?.trim(), entityKey = label?.[1] ?? relationTarget ?? `${source.relativePath}:line-${lineOffset + index + 1}`; let kind: BootstrapProposal["kind"] | undefined; if (/^(definition|def\.|定义)\b/iu.test(raw)) kind = "DEFINITION"; else if (/\b(failed route|route failed|does not work|dead end|失败路线|不可行)\b/iu.test(raw)) kind = "FAILED_ROUTE"; else if (/\b(open problem|todo|conjecture|remains to prove|unresolved|待证|未解决)\b/iu.test(raw)) kind = "OPEN_PROBLEM"; else if (/\b(reduces? to|follows from|it suffices to prove|归约|化为)\b/iu.test(raw)) kind = "REDUCTION"; else if (/\b(case split|split into cases|splits? into|cases?:)\b/iu.test(raw)) kind = "CASE_SPLIT"; else if (/^(theorem|lemma|proposition|corollary|claim|定理|引理)\b/iu.test(raw)) kind = "CLAIM"; else if (/\b(computation|computed|numerical evidence)\b/iu.test(raw)) kind = "COMPUTATIONAL_EVIDENCE"; if (kind === undefined) continue; const hints = dependencyHints(raw), route = kind === "FAILED_ROUTE" ? parseFailedRoute(raw) : {}, cases = kind === "CASE_SPLIT" ? parseCases(raw) : undefined, targetHint = (kind === "REDUCTION" || kind === "CASE_SPLIT") && relationTarget !== undefined ? { targetHint: relationTarget.replace(/^(?:Theorem|Claim|Lemma)\s+/iu, "") } : {}; proposals.push({ entityKey: kind === "FAILED_ROUTE" ? `${source.relativePath}:failed-route-${lineOffset + index + 1}` : entityKey, kind, statement: raw, dependencyHints: hints, ...route, ...targetHint, ...(cases === undefined ? {} : { cases }) }); for (const hint of hints) dependencies.push({ fromEntity: entityKey, toEntity: hint, confidence: "EXPLICIT" }); } return { proposals, dependencies }; }
function dependencyHints(statement: string): string[] { const named = [...statement.matchAll(/(?:Lemma|Theorem|Proposition|Claim)\s+([A-Za-z0-9_.-]+)/giu)].map((match) => match[1] ?? ""); const follows = statement.match(/(?:follows from|depends on|reduces? to|assuming)\s+(.+)$/iu)?.[1]?.split(/,|\band\b|\+/iu).map((item) => item.trim().replace(/^(?:Lemma|Theorem|Claim)\s+/iu, "").replace(/[.;]$/u, "")) ?? []; return [...new Set([...named, ...follows].filter((item) => item.length > 0))]; }
function parseFailedRoute(statement: string): Partial<BootstrapProposal> { const family = statement.match(/(?:failed route|route failed)\s*:?\s*([A-Za-z0-9_-]+)/iu)?.[1] ?? statement.match(/^([A-Za-z0-9_-]+)\s+(?:alone\s+)?(?:fails|does not work)/iu)?.[1]; const because = statement.match(/\bbecause\b\s+(.+)$/iu)?.[1] ?? statement.match(/\bdue to\b\s+(.+)$/iu)?.[1]; const target = statement.match(/\b(?:for|on|target(?:ing)?)\s+(?:Lemma|Theorem|Claim|Problem)?\s*([A-Za-z0-9_.-]+)/iu)?.[1]; return { ...(family === undefined ? {} : { routeFamily: family.toLocaleLowerCase(), mechanism: family.toLocaleLowerCase() }), ...(because === undefined ? {} : { failureMechanism: because }), ...(target === undefined ? {} : { targetHint: target }) }; }
function parseCases(statement: string): string[] | undefined { const tail = statement.match(/(?:cases?|into)\s*:?\s*(.+)$/iu)?.[1]; if (tail === undefined) return undefined; const values = tail.split(/,|\band\b/iu).map((item) => item.trim()).filter(Boolean); return values.length > 1 ? values : undefined; }
function classifyAuthority(authority: ImportAuthority, kind: BootstrapProposal["kind"]): ImportAuthority { if (kind === "FAILED_ROUTE") return "FAILED_HISTORICAL_ROUTE"; if (kind === "OPEN_PROBLEM") return "OPEN_HISTORICAL_OBLIGATION"; if (kind === "DEFINITION") return "DEFINITION"; if (kind === "COMPUTATIONAL_EVIDENCE") return "COMPUTATIONAL_EVIDENCE"; return authority === "VERIFIED_CURRENT" ? "VERIFIED_IMPORTED" : authority; }
function mergeProposals(items: readonly BootstrapProposal[]): BootstrapProposal[] { const map = new Map<string, BootstrapProposal>(); for (const item of items) { const key = `${normalizeKey(item.entityKey)}:${item.kind}`; const prior = map.get(key); if (prior === undefined || item.statement.length > prior.statement.length) map.set(key, item); } return [...map.values()]; }
function mergeDependencies(items: readonly BootstrapDependencyProposal[]): BootstrapDependencyProposal[] { const map = new Map<string, BootstrapDependencyProposal>(); for (const item of items) { const key = `${normalizeKey(item.fromEntity)}->${normalizeKey(item.toEntity)}`; const prior = map.get(key); if (prior === undefined || item.confidence === "EXPLICIT") map.set(key, item); } return [...map.values()]; }
function normalizeKey(value: string): string { return value.trim().replace(/^(?:Lemma|Theorem|Claim|Proposition)\s+/iu, "").toLocaleLowerCase(); }
function bootstrapRanges(lines: readonly string[], maxBytes = 64 * 1024): { readonly startLine: number; readonly endLine: number }[] { const ranges: { startLine: number; endLine: number }[] = []; let start = 0, bytes = 0; for (let index = 0; index < lines.length; index += 1) { const next = Buffer.byteLength(lines[index] ?? "") + 1; if (index > start && bytes + next > maxBytes) { ranges.push({ startLine: start + 1, endLine: index }); start = index; bytes = 0; } bytes += next; } ranges.push({ startLine: start + 1, endLine: Math.max(start + 1, lines.length) }); return ranges; }
function resolveBootstrapParent(proposal: BootstrapProposal, claimByKey: ReadonlyMap<string, string>, claims: Readonly<Record<string, readonly ClaimSnapshot[]>>, rootClaimId?: string): string | undefined { for (const candidate of [proposal.targetHint, proposal.entityKey]) { if (candidate === undefined) continue; const normalized = normalizeKey(candidate), exact = claimByKey.get(normalized); if (exact !== undefined) return exact; for (const [claimId, revisions] of Object.entries(claims)) { const statement = normalizeKey(revisions.at(-1)?.statement ?? ""); if (statement.length > 0 && (statement === normalized || statement.includes(normalized) || normalized.includes(statement))) return claimId; } if ((normalized === "root" || normalized.includes("main theorem") || normalized === "target") && rootClaimId !== undefined) return rootClaimId; } return undefined; }
function createBootstrapChildren(projectId: string, proposal: BootstrapProposal, statements: readonly string[], role: ClaimSnapshot["role"], claims: Record<string, readonly ClaimSnapshot[]>, obligations: Record<string, ResearchObligation>, claimByKey: Map<string, string>, createdClaimIds: string[], createdObligationIds: string[], now: string): string[] { const result: string[] = []; for (const raw of [...new Set(statements.map((item) => item.trim()).filter(Boolean))]) { const known = claimByKey.get(normalizeKey(raw)), claimId = known ?? stableId("claim", projectId, proposal.entityKey, `bootstrap-${role.toLocaleLowerCase()}`, raw); if (claimId === resolveBootstrapParent(proposal, claimByKey, claims)) continue; result.push(claimId); claimByKey.set(normalizeKey(raw), claimId); if (claims[claimId] === undefined) { claims[claimId] = [{ claimId, revision: 1, statement: raw, role, status: "OPEN", dependencies: [], evidenceRefs: [proposal.source], auditRefs: [], assumptions: [], provenance: `bootstrap-child:${proposal.authority}`, createdAt: now }]; createdClaimIds.push(claimId); } const obligationId = stableId("obligation", projectId, claimId, "bootstrap-child"); if (obligations[obligationId] === undefined) { obligations[obligationId] = { obligationId, claimId, kind: "PROVE", statement: raw, status: "OPEN", priority: 60, createdAt: now, updatedAt: now, causalReason: `Provisional historical ${proposal.kind.toLocaleLowerCase()} attached to ${proposal.targetHint ?? proposal.entityKey}` }; createdObligationIds.push(obligationId); } } return result; }
function invalidateChangedCorpus(state: MutableState, changed: readonly CorpusRecord[]): void {
	const oldHashes = new Set(changed.map((item) => item.changedFromHash).filter((item): item is string => item !== undefined)), seeds = new Set<string>();
	const artifactReliesOnChangedSource = (artifactId: string): boolean => state.artifacts[artifactId]?.references.some((ref) => oldHashes.has(ref.contentHash)) ?? false;
	for (const authority of Object.values(state.authorityReceipts)) {
		const receipts = authority.trustReceiptIds.map((id) => state.trustReceipts[id]).filter((item): item is TrustReceipt => item !== undefined);
		if (authority.evidenceRefs.some((ref) => oldHashes.has(ref.contentHash)) || artifactReliesOnChangedSource(authority.artifact.artifactId) || receipts.some((receipt) => [...receipt.evidenceInspected, ...(receipt.workerReadEvidence ?? []), ...(receipt.workerDeclaredEvidence ?? [])].some((ref) => oldHashes.has(ref.contentHash)))) seeds.add(authority.claimId);
	}
	for (const claimId of seeds) invalidateClaimAuthorityInState(state, claimId, "Corpus source hash changed");
	const receipts: Record<string, TrustReceipt> = { ...state.trustReceipts }; for (const [id, receipt] of Object.entries(receipts)) if ([...receipt.evidenceInspected, ...(receipt.workerReadEvidence ?? []), ...(receipt.workerDeclaredEvidence ?? [])].some((ref) => oldHashes.has(ref.contentHash))) receipts[id] = { ...receipt, stale: true }; state.trustReceipts = receipts;
	reconcileProjectTruthState(state, "Corpus source hash changed");
}
async function walk(root: string): Promise<string[]> { const result: string[] = []; for (const entry of await readdir(root, { withFileTypes: true })) { const path = join(root, entry.name); if (entry.isSymbolicLink()) { const actual = await realpath(path); if (!inside(root, actual)) throw new Error(`Corpus symlink escapes configured root: ${path}`); const info = await stat(actual); if (info.isDirectory()) result.push(...await walk(actual)); else result.push(actual); } else if (entry.isDirectory()) result.push(...await walk(path)); else if (entry.isFile()) result.push(path); } return result.sort(); }
function inside(root: string, candidate: string): boolean { const base = resolve(root), target = resolve(candidate); return target === base || target.startsWith(`${base}${sep}`); }
type MutableState = { -readonly [K in keyof ResearchProjectState]: ResearchProjectState[K] };
