import { randomUUID } from "node:crypto";
import { stableId } from "./ids.js";
import { activeAuthorityForClaim } from "./invariants.js";
import { CorpusService } from "./corpus.js";
import { desiredContributionKind, evaluateRouteReopenPredicate } from "./invariants.js";
import { researchFrontier, ResearchStateReducer, rootSynthesisReadiness } from "./reducer.js";
import { ResearchContextBuilder, ResearchRetrievalService } from "./retrieval.js";
import { ResearchStore } from "./store.js";
import type { ArtifactRef, Attempt, ClaimSnapshot, ContextManifest, DecisionBasis, DirectorAction, ExecutionTask, LogicalJob, ResearchCheckpoint, ResearchObligation, ResearchProjectState, TacticalDirective, TacticalResearchResult, TrustReceipt } from "./types.js";
import type { CorpusArchiveSink } from "./corpus-archive-types.js";

export interface TacticalProofRequest { readonly projectId: string; readonly cycleId: string; readonly logicalJobId: string; readonly attemptId: string; readonly obligation: ResearchObligation; readonly targetClaimId: string; readonly decision: DecisionBasis; readonly directive: TacticalDirective; readonly contextManifest: ContextManifest; readonly scratchDirectory: string; }
export type TacticalProofRunner = (request: TacticalProofRequest, signal?: AbortSignal) => Promise<TacticalResearchResult>;
export type SecondaryAuditor = (request: { readonly projectId: string; readonly claim: ClaimSnapshot; readonly candidate: ArtifactRef; readonly availableEvidence: readonly ArtifactRef[]; readonly workerReadEvidence: readonly ArtifactRef[] }, signal?: AbortSignal) => Promise<{ readonly verdict: TrustReceipt["verdict"]; readonly feedback: string; readonly profile: string; readonly evidenceInspected?: readonly ArtifactRef[]; readonly toolReceiptIds?: readonly string[] }>;
export type FaultPoint = "after_director" | "mid_workers" | "after_verifier" | "after_effect";

export interface DirectorProjectSnapshot { readonly projectId: string; readonly configRevision: string; readonly rootObjective?: string; readonly rootClaimId?: string; readonly frontier: readonly ResearchObligation[]; readonly rootBlockers: readonly string[]; readonly verifiedClaims: readonly { readonly claimId: string; readonly statement: string }[]; readonly recentClaims: readonly { readonly claimId: string; readonly status: string; readonly statement: string }[]; readonly blockedClaims: readonly string[]; readonly routes: readonly { readonly routeId: string; readonly targetObligationId: string; readonly family: string; readonly mechanism: string; readonly status: string; readonly failureMechanism?: string; readonly reopenPredicate?: unknown }[]; readonly coverageGaps: readonly string[]; readonly authorityRevocations: readonly { readonly type: string; readonly detail: Readonly<Record<string, unknown>> }[]; readonly currentFinalProofAuthority?: ResearchProjectState["currentFinalProofAuthority"]; readonly stallCycles: number; readonly budget: ResearchProjectState["budget"]; }
export interface DirectorProposal { readonly action: DirectorAction; readonly targetObligationId?: string; readonly targetClaimId?: string; readonly routeId?: string; readonly routeFamily?: string; readonly auxiliaryStatement?: string; readonly literatureQuery?: string; readonly reason: string; readonly budgetAllocated?: number; }
export interface ModelResearchDirector { decide(snapshot: DirectorProjectSnapshot, signal?: AbortSignal): Promise<DirectorProposal>; }

export interface ResearchRuntimeOptions {
	readonly store: ResearchStore; readonly proofRunner: TacticalProofRunner; readonly modelDirector?: ModelResearchDirector;
	readonly secondaryAuditor?: SecondaryAuditor; readonly synthesisRunner?: (projectId: string, signal?: AbortSignal) => Promise<ResearchProjectState>;
	readonly literatureRunner?: TacticalProofRunner; readonly checkpointInterval?: number; readonly stallThreshold?: number; readonly maxCycles?: number;
	readonly maxActiveObligations?: number; readonly structuralProbeBudget?: number; readonly budgetLimits?: Partial<Record<"plannerCalls" | "workerCalls" | "verifierCalls" | "secondaryAuditorCalls" | "literatureCalls" | "toolCalls" | "wallTimeSeconds", number>>;
	readonly effectiveConfig?: Readonly<Record<string, unknown>>; readonly faultPoint?: FaultPoint;
	readonly archiveSink?: CorpusArchiveSink;
}

export class ResearchDirector {
	constructor(private readonly model?: ModelResearchDirector) {}
	async decide(state: ResearchProjectState, stallThreshold = 3, signal?: AbortSignal): Promise<DecisionBasis> {
		const cycleId = state.activeCycleId ?? stableId("cycle", state.projectId, String(state.cycle + 1)); const existing = state.decisions.find((item) => item.cycleId === cycleId); if (existing !== undefined) return existing;
		const frontier = researchFrontier(state); const failed = Object.values(state.routes).filter((route) => route.status === "FAILED" || route.status === "EXHAUSTED").map((route) => route.routeId);
		if (this.model !== undefined) try { const proposal = await this.model.decide(compactSnapshot(state), signal); const validated = validateDirectorProposal(state, proposal, frontier); return { ...validated, decisionId: stableId("decision", cycleId), cycleId, direction: "MODEL_DIRECTED", frontier: frontier.map((item) => item.obligationId), relevantClaims: validated.targetClaimId === undefined ? [] : [validated.targetClaimId], failedRoutes: failed, budgetAllocated: Math.max(0, proposal.budgetAllocated ?? 1) }; } catch (error) { return fallbackDecision(state, frontier, cycleId, stallThreshold, String(error)); }
		return fallbackDecision(state, frontier, cycleId, stallThreshold);
	}
}

export class ResearchRuntime {
	readonly corpus: CorpusService; readonly reducer: ResearchStateReducer; readonly director: ResearchDirector; readonly retrieval: ResearchRetrievalService; readonly contextBuilder: ResearchContextBuilder;
	private readonly executorInstanceId = stableId("research-executor", String(process.pid), randomUUID());
	private readonly checkpointInterval: number; private readonly stallThreshold: number; private readonly maxCycles: number; private readonly maxActiveObligations: number; private readonly structuralProbeBudget: number;
	constructor(private readonly options: ResearchRuntimeOptions) { this.corpus = new CorpusService(options.store); this.reducer = new ResearchStateReducer(options.store, { ...(options.archiveSink === undefined ? {} : { archiveSink: options.archiveSink }) }); this.director = new ResearchDirector(options.modelDirector); this.retrieval = new ResearchRetrievalService(options.store); this.contextBuilder = new ResearchContextBuilder(this.retrieval); this.checkpointInterval = Math.max(1, options.checkpointInterval ?? 1); this.stallThreshold = Math.max(1, options.stallThreshold ?? 3); this.maxCycles = Math.max(1, options.maxCycles ?? 100); this.maxActiveObligations = Math.max(1, options.maxActiveObligations ?? 8); this.structuralProbeBudget = Math.max(0, options.structuralProbeBudget ?? 2); }

	async createProject(projectId: string, name: string, effectiveConfig: Readonly<Record<string, unknown>> = this.options.effectiveConfig ?? {}): Promise<ResearchProjectState> { return this.options.store.create(projectId, name, effectiveConfig); }
	async setRootObjective(projectId: string, statement: string, allowedAssumptions: readonly string[] = []): Promise<ResearchProjectState> {
		const exactStatement = statement.trim(); if (exactStatement.length === 0) throw new Error("Root objective statement must be nonempty");
		const normalizedStatement = normalizeMath(exactStatement), allowed = canonicalMathStrings(allowedAssumptions), now = new Date().toISOString(), claimId = stableId("claim", projectId, "root", exactStatement), obligationId = stableId("obligation", projectId, claimId, "root"), contractId = stableId("root-contract", projectId, claimId, normalizedStatement, "1"), eventId = stableId("event", projectId, contractId, "created");
		return (await this.options.store.transaction(projectId, (draft) => {
			const mutable = draft as MutableState, existing = draft.rootObjectiveContract;
			if (draft.rootClaimId !== undefined && draft.rootClaimId !== claimId) throw new Error("Changing root meaning requires an explicit root revision workflow");
			if (existing !== undefined && (existing.rootClaimId !== claimId || existing.normalizedStatement !== normalizedStatement || !sameMathSet(existing.allowedAssumptions, allowed))) throw new Error("Changing the root objective contract requires an explicit versioned contract revision workflow");
			mutable.rootObjective = exactStatement; mutable.rootClaimId = claimId;
			if (existing === undefined) {
				mutable.rootObjectiveContract = { contractId, version: 1, rootClaimId: claimId, statement: exactStatement, normalizedStatement, allowedAssumptions: allowed, status: "VALID", provenance: { source: "USER_API", eventId }, createdAt: now };
				mutable.events = [...draft.events, { eventId, type: "research/root_objective_contract_created", projectId, timestamp: now, detail: { contractId, version: 1, rootClaimId: claimId, statement: exactStatement, allowedAssumptions: allowed, provenance: "USER_API" } }];
			}
			if (draft.claims[claimId] === undefined) mutable.claims = { ...draft.claims, [claimId]: [{ claimId, revision: 1, statement: exactStatement, role: "ROOT", status: "OPEN", dependencies: [], evidenceRefs: [], auditRefs: [], assumptions: [], provenance: "user-objective", createdAt: now }] };
			if (draft.obligations[obligationId] === undefined) mutable.obligations = { ...draft.obligations, [obligationId]: { obligationId, claimId, kind: "PROVE", statement: exactStatement, status: "OPEN", priority: 100, createdAt: now, updatedAt: now } };
		})).state;
	}

	/** Explicit operator/API action; model Directors and automatic predicates cannot satisfy MANUAL_REOPEN. */
	async reopenRouteAsOperator(projectId: string, routeId: string, reason: string): Promise<ResearchProjectState> {
		const before = await this.options.store.read(projectId), route = before.routes[routeId]; if (route === undefined) throw new Error(`Route not found: ${routeId}`);
		const satisfied = evaluateRouteReopenPredicate(before, route, "OPERATOR"); if (!satisfied.satisfied) throw new Error(`Route is not operator-reopenable: ${routeId}`);
		return (await this.options.store.transaction(projectId, (draft) => { const current = draft.routes[routeId]; if (current === undefined) throw new Error(`Route not found: ${routeId}`); const mutable = draft as MutableState, now = new Date().toISOString(), eventId = stableId("event", projectId, routeId, "operator-reopen", String(draft.events.length)); mutable.routes = { ...draft.routes, [routeId]: { ...current, status: "ACTIVE", reopenedBecause: `OPERATOR_MANUAL_REOPEN: ${reason}`, updatedAt: now } }; mutable.cyclesSinceStructuralProgress = 0; mutable.events = [...draft.events, { eventId, type: "research/route_reopened", projectId, timestamp: now, detail: { routeId, actor: "OPERATOR", predicate: current.reopenPredicate, reason } }]; })).state;
	}

	async run(projectId: string, requestedCycles?: number, signal?: AbortSignal): Promise<ResearchProjectState> {
		try { await this.options.archiveSink?.reconcile(projectId); } catch { /* External corpus recovery is independent of research execution. */ }
		await this.reclaimOrphanedExecution(projectId); let state = await this.options.store.read(projectId); const projectMaximum = effectiveResearchNumber(state, "maxCycles", this.maxCycles), cycles = Math.min(Math.max(1, requestedCycles ?? projectMaximum), projectMaximum);
		for (let count = 0; count < cycles && state.status !== "PROVED"; count += 1) { if (signal?.aborted) { await this.recordOperationalStop(projectId, "CANCELLED", "Research run cancelled"); break; } if (this.budgetExceeded(state)) { await this.recordOperationalStop(projectId, "BUDGET_EXHAUSTED", "Configured research budget exhausted"); state = await this.createCheckpoint(projectId); break; } state = await this.runCycle(projectId, signal); if (state.status === "PARTIAL" || state.status === "BLOCKED" || state.status === "EXHAUSTED") break; }
		if (state.status === "RUNNING") state = (await this.options.store.transaction(projectId, (draft) => { (draft as MutableState).status = "PARTIAL"; })).state; return state;
	}

	async runCycle(projectId: string, signal?: AbortSignal): Promise<ResearchProjectState> {
		let state = await this.ensureCycle(projectId); const stallThreshold = effectiveResearchNumber(state, "stallThreshold", this.stallThreshold), structuralProbeBudget = effectiveResearchNumber(state, "structuralProbeBudget", this.structuralProbeBudget, 0), checkpointInterval = effectiveResearchNumber(state, "checkpointInterval", this.checkpointInterval); const decision = await this.director.decide(state, stallThreshold, signal); const directive = tacticalDirective(state, decision);
		if (decision.action === "RUN_STRUCTURAL_PROBE" && state.decisions.filter((item) => item.action === "RUN_STRUCTURAL_PROBE").length >= structuralProbeBudget) throw new Error("PROTOCOL_ERROR: structural probe budget exhausted; Director must make a concrete strategic turn");
		state = (await this.options.store.transaction(projectId, (draft) => { const mutable = draft as MutableState; if (!draft.decisions.some((item) => item.decisionId === decision.decisionId)) mutable.decisions = [...draft.decisions, decision]; mutable.status = "RUNNING"; mutable.events = appendEvent(draft, "research/decision", decision.decisionId, { action: decision.action, direction: decision.direction, targetObligationId: decision.targetObligationId, reason: decision.reason, protocolError: decision.protocolError, configRevision: draft.configRevision }); if (draft.cyclesSinceStructuralProgress >= stallThreshold) mutable.events = appendEvent({ ...draft, events: mutable.events }, "research/strategic_review", decision.decisionId, { action: decision.action, reason: decision.reason, configRevision: draft.configRevision }); })).state;
		this.inject("after_director");
		if (decision.action === "STOP_PROJECT") { await this.createCheckpoint(projectId); const stopped = (await this.options.store.transaction(projectId, (draft) => { const mutable = draft as MutableState; mutable.status = "PARTIAL"; mutable.events = appendEvent(draft, "research/project_stopped", decision.decisionId, { reason: decision.reason, direction: decision.direction }); })).state; return this.finishCycle(stopped); }
		if (decision.action === "CREATE_CHECKPOINT") return this.finishCycle(await this.createCheckpoint(projectId));
		if (decision.action === "TRIGGER_SYNTHESIS") { if (this.options.synthesisRunner === undefined) return this.finishCycle(await this.createCheckpoint(projectId)); const synthesized = await this.options.synthesisRunner(projectId, signal); return this.finishCycle(synthesized); }
		const strategic = await this.applyStrategicDecision(projectId, decision); if (strategic.terminal) return this.finishCycle(strategic.state); state = strategic.state;
		const obligation = decision.targetObligationId === undefined ? undefined : state.obligations[decision.targetObligationId]; if (obligation === undefined) return this.finishCycle(await this.createCheckpoint(projectId));
		const cycleId = decision.cycleId, logicalJobId = stableId("job", projectId, cycleId, obligation.obligationId); state = await this.ensureJob(projectId, cycleId, logicalJobId, obligation, directive);
		const completed = Object.values(state.attempts).filter((item) => item.logicalJobId === logicalJobId && item.status === "COMPLETED" && item.artifactRefs.length > 0).sort((a, b) => b.ordinal - a.ordinal)[0]; let attempt: Attempt, tactical: TacticalResearchResult;
		if (completed !== undefined) { attempt = completed; tactical = await this.readTactical(projectId, completed.artifactRefs[0] as ArtifactRef); } else { attempt = await this.startOrResumeAttempt(projectId, logicalJobId); const manifest = await this.buildContextManifest(projectId, logicalJobId, obligation); await this.markExecutionTask(projectId, logicalJobId, attempt.attemptId, "PLANNER", "tactical-runtime", "RUNNING"); const runner = decision.action === "REQUEST_LITERATURE" && this.options.literatureRunner !== undefined ? this.options.literatureRunner : this.options.proofRunner; tactical = await runner({ projectId, cycleId, logicalJobId, attemptId: attempt.attemptId, obligation, targetClaimId: obligation.claimId, decision, directive, contextManifest: manifest, scratchDirectory: attempt.scratchPath }, signal); await this.markExecutionTask(projectId, logicalJobId, attempt.attemptId, "PLANNER", "tactical-runtime", "COMPLETED"); this.inject("mid_workers"); tactical = await this.attachSecondaryAudit(projectId, obligation, tactical, signal); const resultArtifact = await this.options.store.putArtifact(projectId, { artifactType: "TACTICAL_RESULT", body: `${JSON.stringify(tactical, null, 2)}\n`, provenance: "ProofRuntime-to-ResearchRuntime-protocol", creationAttemptId: attempt.attemptId, references: tacticalReferences(tactical), metadata: { directiveId: directive.directiveId, directorDecisionId: decision.decisionId } }); state = (await this.options.store.transaction(projectId, (draft) => { const mutable = draft as MutableState; mutable.attempts = { ...draft.attempts, [attempt.attemptId]: { ...draft.attempts[attempt.attemptId] as Attempt, status: "COMPLETED", artifactRefs: [resultArtifact], completedAt: new Date().toISOString() } }; })).state; attempt = state.attempts[attempt.attemptId] as Attempt; await this.markExecutionTask(projectId, logicalJobId, attempt.attemptId, "RESULT_CONVERSION", "tactical-result", "COMPLETED", resultArtifact); }
		this.inject("after_verifier"); await this.reducer.applyTactical({ projectId, cycleId, logicalJobId, obligationId: obligation.obligationId, targetClaimId: obligation.claimId, result: tactical });
		if (decision.action === "RUN_STRUCTURAL_PROBE" && tactical.contributions.length === 0) { const observation = await this.options.store.putArtifact(projectId, { artifactType: "STRUCTURAL_PROBE", body: tactical.feedback, provenance: "bounded-structural-probe", creationAttemptId: attempt.attemptId, references: tacticalReferences(tactical) }); await this.reducer.apply({ projectId, cycleId, logicalJobId, effectSlot: "probe-observation", outcome: { type: "STRUCTURAL_DISCOVERY", observation, statement: tactical.feedback } }); }
		try { await this.options.archiveSink?.reconcile(projectId); } catch { /* Git failure must not fail or roll back the cycle. */ }
		this.inject("after_effect"); state = (await this.options.store.transaction(projectId, (draft) => { const mutable = draft as MutableState, job = draft.jobs[logicalJobId] as LogicalJob; mutable.jobs = { ...draft.jobs, [logicalJobId]: { ...job, status: "COMPLETED" } }; })).state;
		if (state.cycle % checkpointInterval === 0 || state.cyclesSinceStructuralProgress >= stallThreshold) state = await this.createCheckpoint(projectId); return this.finishCycle(state);
	}

	async createCheckpoint(projectId: string): Promise<ResearchProjectState> { const state = await this.options.store.read(projectId), frontier = researchFrontier(state), authorityRevocations = state.events.filter((item) => item.type === "research/authority_revoked").slice(-20).map((item) => ({ claimId: String(item.detail.claimId ?? "unknown"), reason: String(item.detail.reason ?? "authority revoked"), eventId: item.eventId })); const checkpoint: ResearchCheckpoint = { checkpointId: stableId("checkpoint", projectId, String(state.cycle), String(state.events.length)), projectId, createdAt: new Date().toISOString(), frontier: frontier.map((item) => item.obligationId), provedClaims: Object.entries(state.claims).filter(([claimId, revisions]) => { const claim = revisions.at(-1); return claim?.status === "PROVED" && activeAuthorityForClaim(state, claimId, claim.revision) !== undefined; }).map(([id]) => id), blockedObligations: Object.values(state.obligations).filter((item) => item.status === "BLOCKED").map((item) => item.obligationId), activeRoutes: Object.values(state.routes).filter((item) => item.status === "ACTIVE").map((item) => item.routeId), cyclesSinceStructuralProgress: state.cyclesSinceStructuralProgress, recommendedNextTargets: frontier.slice(0, 5).map((item) => item.obligationId), authorityRevocations, ...(state.currentFinalProofAuthority === undefined ? {} : { currentFinalProofAuthority: state.currentFinalProofAuthority }) }; const artifact = await this.options.store.putArtifact(projectId, { artifactType: "CHECKPOINT", body: `${JSON.stringify(checkpoint, null, 2)}\n`, provenance: "ResearchRuntime" }); return (await this.options.store.transaction(projectId, (draft) => { const mutable = draft as MutableState; if (!draft.checkpoints.some((item) => item.checkpointId === checkpoint.checkpointId)) mutable.checkpoints = [...draft.checkpoints, checkpoint]; mutable.events = appendEvent(draft, "research/checkpoint_created", checkpoint.checkpointId, { artifactId: artifact.artifactId }); })).state; }

	private async attachSecondaryAudit(projectId: string, obligation: ResearchObligation, tactical: TacticalResearchResult, signal?: AbortSignal): Promise<TacticalResearchResult> { const submission = tactical.targetSubmission; if (tactical.targetStatus !== "TARGET_PROVED" || submission === undefined) return tactical; const state = await this.options.store.read(projectId), claim = state.claims[obligation.claimId]?.at(-1); if (state.rootClaimId !== obligation.claimId || claim === undefined) return tactical; if (this.options.secondaryAuditor === undefined) return { ...tactical, targetStatus: "TARGET_UNRESOLVED", targetSubmission: undefined, feedback: `${tactical.feedback}; root target lacks a configured fresh secondary auditor` }; const reliedOn = submission.primaryReceipt.workerDeclaredEvidence ?? submission.primaryReceipt.workerReadEvidence ?? []; const audit = await this.options.secondaryAuditor({ projectId, claim, candidate: submission.candidate, availableEvidence: state.contextManifests[Object.keys(state.contextManifests).at(-1) ?? ""]?.artifactRefs ?? [], workerReadEvidence: reliedOn }, signal); const receipt: TrustReceipt = { receiptId: stableId("receipt", submission.candidate.artifactId, "secondary", audit.profile), claimId: obligation.claimId, candidate: submission.candidate, verifierProfile: audit.profile, evidenceInspected: audit.evidenceInspected ?? [], verifierReadEvidence: audit.evidenceInspected ?? [], toolReceiptIds: audit.toolReceiptIds ?? [], verdict: audit.verdict, independentContext: true, stale: false, createdAt: new Date().toISOString() }; if (receipt.verdict !== "CORRECT" || !covers(reliedOn, receipt.evidenceInspected)) return { ...tactical, targetStatus: "TARGET_UNRESOLVED", targetSubmission: undefined, feedback: `${tactical.feedback}; secondary audit rejected target or did not inspect every relied-on artifact: ${audit.feedback}` }; return { ...tactical, targetSubmission: { ...submission, secondaryReceipt: receipt } }; }

	private async ensureCycle(projectId: string): Promise<ResearchProjectState> { return (await this.options.store.transaction(projectId, (draft) => { if (draft.activeCycleId !== undefined) return; const mutable = draft as MutableState; mutable.cycle = draft.cycle + 1; mutable.budget = { ...draft.budget, cycles: draft.budget.cycles + 1 }; mutable.activeCycleId = stableId("cycle", projectId, String(mutable.cycle)); mutable.events = appendEvent(draft, "research/cycle_started", mutable.activeCycleId, { cycle: mutable.cycle }); })).state; }
	private async finishCycle(state: ResearchProjectState): Promise<ResearchProjectState> { return (await this.options.store.transaction(state.projectId, (draft) => { (draft as MutableState).activeCycleId = undefined; })).state; }
	private async ensureJob(projectId: string, cycleId: string, logicalJobId: string, obligation: ResearchObligation, directive: TacticalDirective): Promise<ResearchProjectState> { return (await this.options.store.transaction(projectId, (draft) => { if (draft.jobs[logicalJobId] !== undefined) return; const job: LogicalJob = { logicalJobId, projectId, cycleId, obligationId: obligation.obligationId, status: "PENDING", directive, createdAt: new Date().toISOString() }; (draft as MutableState).jobs = { ...draft.jobs, [logicalJobId]: job }; })).state; }
	private async startOrResumeAttempt(projectId: string, logicalJobId: string): Promise<Attempt> { const state = await this.options.store.read(projectId), running = Object.values(state.attempts).find((item) => item.logicalJobId === logicalJobId && item.status === "RUNNING"); if (running !== undefined) { const now = new Date().toISOString(), owned = { ...running, executorInstanceId: this.executorInstanceId, processInstanceId: process.pid, acquiredAt: running.acquiredAt ?? now, heartbeatAt: now }; await this.options.store.transaction(projectId, (draft) => { (draft as MutableState).attempts = { ...draft.attempts, [running.attemptId]: owned }; }); return owned; } const ordinal = Object.values(state.attempts).filter((item) => item.logicalJobId === logicalJobId).length + 1, attemptId = stableId("attempt", logicalJobId, String(ordinal)), scratchPath = await this.options.store.createScratch(projectId, attemptId), now = new Date().toISOString(), attempt: Attempt = { attemptId, logicalJobId, ordinal, scratchPath, status: "RUNNING", artifactRefs: [], startedAt: now, executorInstanceId: this.executorInstanceId, processInstanceId: process.pid, acquiredAt: now, heartbeatAt: now }; await this.options.store.transaction(projectId, (draft) => { (draft as MutableState).attempts = { ...draft.attempts, [attemptId]: attempt }; }); return attempt; }
	private async buildContextManifest(projectId: string, logicalJobId: string, obligation: ResearchObligation): Promise<ContextManifest> { const state = await this.options.store.read(projectId), selected = await this.contextBuilder.select(state, obligation, 12), manifest: ContextManifest = { manifestId: stableId("context", projectId, logicalJobId, obligation.obligationId, ...selected.artifactRefs.map((ref) => ref.contentHash)), projectId, logicalJobId, obligationId: obligation.obligationId, claimIds: selected.claimIds, artifactRefs: selected.artifactRefs, routeIds: selected.routeIds, createdAt: new Date().toISOString() }; await this.options.store.putArtifact(projectId, { artifactType: "CONTEXT_MANIFEST", body: `${JSON.stringify(manifest, null, 2)}\n`, provenance: "ResearchContextBuilder", references: selected.artifactRefs }); await this.options.store.transaction(projectId, (draft) => { (draft as MutableState).contextManifests = { ...draft.contextManifests, [manifest.manifestId]: manifest }; }); return manifest; }
	private async readTactical(projectId: string, ref: ArtifactRef): Promise<TacticalResearchResult> { const value: unknown = JSON.parse((await this.options.store.resolveArtifact(projectId, ref)).body); assertTacticalResult(value); return value; }
	private async markExecutionTask(projectId: string, logicalJobId: string, attemptId: string, kind: ExecutionTask["kind"], logicalTaskId: string, status: ExecutionTask["status"], resultArtifact?: ArtifactRef): Promise<void> { const executionTaskId = stableId("execution-task", logicalJobId, kind, logicalTaskId), now = new Date().toISOString(); await this.options.store.transaction(projectId, (draft) => { const previous = draft.executionTasks[executionTaskId], task: ExecutionTask = { executionTaskId, logicalJobId, attemptId, kind, logicalTaskId, status, inputHash: stableId("input", logicalJobId, kind, logicalTaskId), ...(resultArtifact === undefined ? {} : { resultArtifact }), startedAt: previous?.startedAt ?? now, executorInstanceId: this.executorInstanceId, processInstanceId: process.pid, acquiredAt: previous?.acquiredAt ?? now, heartbeatAt: now, ...(status === "COMPLETED" ? { completedAt: now } : {}) }; (draft as MutableState).executionTasks = { ...draft.executionTasks, [executionTaskId]: task }; }); }
	private async reclaimOrphanedExecution(projectId: string): Promise<void> {
		await this.options.store.transaction(projectId, (draft) => { const mutable = draft as MutableState, now = new Date().toISOString(), tasks = { ...draft.executionTasks }, attempts = { ...draft.attempts }, plans = { ...draft.executionPlans }; let reclaimed = 0, changed = false;
			for (const [id, task] of Object.entries(tasks)) if (task.status === "RUNNING" && task.executorInstanceId !== this.executorInstanceId) { tasks[id] = { ...task, status: "FAILED_RETRYABLE", error: `Executor ${task.executorInstanceId ?? "legacy-unknown"} is not live after runtime restart`, heartbeatAt: now }; reclaimed += 1; changed = true; }
			for (const [id, attempt] of Object.entries(attempts)) if (attempt.status === "RUNNING" && attempt.executorInstanceId !== this.executorInstanceId) { attempts[id] = { ...attempt, executorInstanceId: this.executorInstanceId, processInstanceId: process.pid, acquiredAt: now, heartbeatAt: now }; changed = true; }
			for (const [id, plan] of Object.entries(plans)) if (plan.status === "RUNNING" && plan.actionExecutions.some((action) => action.status === "RUNNING")) { plans[id] = { ...plan, actionExecutions: plan.actionExecutions.map((action) => action.status === "RUNNING" ? { ...action, status: "INTERRUPTED", error: "Orphaned RUNNING action reclaimed after runtime restart" } : action) }; changed = true; }
			if (!changed) return; mutable.executionTasks = tasks; mutable.attempts = attempts; mutable.executionPlans = plans; mutable.events = appendEvent(draft, "research/orphan_execution_reclaimed", stableId("orphan-reclaim", projectId, this.executorInstanceId), { executorInstanceId: this.executorInstanceId, reclaimedTasks: reclaimed });
		});
	}
	private async applyStrategicDecision(projectId: string, decision: DecisionBasis): Promise<{ readonly state: ResearchProjectState; readonly terminal: boolean }> { if (decision.action === "CREATE_AUXILIARY_OBLIGATION" && decision.auxiliaryStatement !== undefined) { const before = await this.options.store.read(projectId), maxActiveObligations = effectiveResearchNumber(before, "maxActiveObligations", this.maxActiveObligations); if (researchFrontier(before).length >= maxActiveObligations) return { state: await this.createCheckpoint(projectId), terminal: true }; const claimId = stableId("claim", projectId, "director-aux", decision.decisionId, decision.auxiliaryStatement), obligationId = stableId("obligation", projectId, claimId, "director-aux"), now = new Date().toISOString(); const state = (await this.options.store.transaction(projectId, (draft) => { const mutable = draft as MutableState; mutable.claims = { ...draft.claims, [claimId]: draft.claims[claimId] ?? [{ claimId, revision: 1, statement: decision.auxiliaryStatement as string, role: "CONJECTURE", status: "OPEN", dependencies: [], evidenceRefs: [], auditRefs: [], assumptions: [], provenance: `director-strategy:${decision.direction}`, createdAt: now }] }; mutable.obligations = { ...draft.obligations, [obligationId]: draft.obligations[obligationId] ?? { obligationId, claimId, kind: "PROVE", statement: decision.auxiliaryStatement as string, status: "OPEN", priority: 85, createdAt: now, updatedAt: now, causalReason: decision.reason } }; mutable.cyclesSinceStructuralProgress = 0; mutable.events = appendEvent(draft, "research/auxiliary_obligation_created", decision.decisionId, { claimId, obligationId, strategicReason: decision.reason, configRevision: draft.configRevision }); })).state; return { state, terminal: true }; }
		if (decision.action === "CHANGE_ROUTE" && decision.targetObligationId !== undefined) { const now = new Date().toISOString(), family = decision.routeFamily ?? `strategic-${decision.cycleId}`, routeId = decision.routeId ?? stableId("route", projectId, decision.targetObligationId, family, decision.decisionId); const state = (await this.options.store.transaction(projectId, (draft) => { const mutable = draft as MutableState, previous = draft.routes[routeId], target = draft.claims[draft.obligations[decision.targetObligationId as string]?.claimId ?? ""]?.at(-1); mutable.routes = { ...draft.routes, [routeId]: { routeId, targetObligationId: decision.targetObligationId as string, family, mechanism: family, strategyDescription: decision.reason, assumptions: target?.assumptions ?? [], dependencySnapshot: target?.dependencies ?? [], artifactRefs: [], status: "ACTIVE", attemptIds: previous?.attemptIds ?? [], createdAt: previous?.createdAt ?? now, updatedAt: now, ...(previous?.failureMechanism === undefined ? {} : { failureMechanism: previous.failureMechanism }) } }; mutable.cyclesSinceStructuralProgress = 0; mutable.events = appendEvent(draft, "research/route_changed", decision.decisionId, { routeId, family, reason: decision.reason }); })).state; return { state, terminal: false }; }
		if (decision.action === "REOPEN_ROUTE" && decision.routeId !== undefined) { const before = await this.options.store.read(projectId), route = before.routes[decision.routeId]; if (route === undefined) throw new Error("Director referenced a missing route"); const satisfied = evaluateRouteReopenPredicate(before, route, "MODEL_DIRECTOR"); if (!satisfied.satisfied) throw new Error(`PROTOCOL_ERROR: route reopen predicate is not satisfied: ${route.routeId}`); const state = (await this.options.store.transaction(projectId, (draft) => { const current = draft.routes[decision.routeId as string]; if (current === undefined) return; const mutable = draft as MutableState; mutable.routes = { ...draft.routes, [current.routeId]: { ...current, status: "ACTIVE", reopenedBecause: `${satisfied.reason ?? decision.reason}${satisfied.evidence === undefined ? "" : ` via ${satisfied.evidence}`}`, updatedAt: new Date().toISOString() } }; mutable.cyclesSinceStructuralProgress = 0; mutable.events = appendEvent(draft, "research/route_reopened", decision.decisionId, { routeId: current.routeId, actor: "MODEL_DIRECTOR", predicate: current.reopenPredicate, evidence: satisfied.evidence, reason: satisfied.reason }); })).state; return { state, terminal: false }; }
		if ((decision.action === "SUSPEND_ROUTE" || decision.action === "MARK_ROUTE_EXHAUSTED") && decision.routeId !== undefined) { const state = (await this.options.store.transaction(projectId, (draft) => { const route = draft.routes[decision.routeId as string]; if (route === undefined) return; (draft as MutableState).routes = { ...draft.routes, [route.routeId]: { ...route, status: decision.action === "SUSPEND_ROUTE" ? "SUSPENDED" : "EXHAUSTED", updatedAt: new Date().toISOString() } }; })).state; return { state, terminal: true }; }
		if (decision.action === "RESTRUCTURE_RESEARCH_MAP") return { state: await this.createCheckpoint(projectId), terminal: true };
		return { state: await this.options.store.read(projectId), terminal: false }; }
	private budgetExceeded(state: ResearchProjectState): boolean { const limits = effectiveBudgetLimits(state, this.options.budgetLimits); if (limits === undefined) return false; if (limits.plannerCalls !== undefined && state.budget.plannerCalls >= limits.plannerCalls) return true; if (limits.workerCalls !== undefined && state.budget.workerCalls >= limits.workerCalls) return true; if (limits.verifierCalls !== undefined && state.budget.verifierCalls >= limits.verifierCalls) return true; if (limits.secondaryAuditorCalls !== undefined && state.budget.secondaryAuditorCalls >= limits.secondaryAuditorCalls) return true; if (limits.literatureCalls !== undefined && state.budget.literatureCalls >= limits.literatureCalls) return true; if (limits.toolCalls !== undefined && state.budget.toolCalls >= limits.toolCalls) return true; return limits.wallTimeSeconds !== undefined && Date.now() - state.budget.startedAt >= limits.wallTimeSeconds * 1000; }
	private async recordOperationalStop(projectId: string, kind: "CANCELLED" | "BUDGET_EXHAUSTED", reason: string): Promise<void> { await this.options.store.transaction(projectId, (draft) => { const mutable = draft as MutableState; mutable.status = kind === "BUDGET_EXHAUSTED" ? "EXHAUSTED" : "PARTIAL"; mutable.lastError = `${kind}: ${reason}`; mutable.events = appendEvent(draft, "research/operational_stop", stableId("stop", projectId, kind, String(draft.cycle)), { kind, reason }); }); }
	private inject(point: FaultPoint): void { if (this.options.faultPoint === point) throw new Error(`Injected research fault: ${point}`); }
}

function compactSnapshot(state: ResearchProjectState): DirectorProjectSnapshot { const readiness = rootSynthesisReadiness(state); return { projectId: state.projectId, configRevision: state.configRevision, rootObjective: state.rootObjective, rootClaimId: state.rootClaimId, frontier: researchFrontier(state).slice(0, 20), rootBlockers: readiness.blockers, verifiedClaims: Object.entries(state.claims).filter(([claimId, revisions]) => { const claim = revisions.at(-1); return claim?.status === "PROVED" && activeAuthorityForClaim(state, claimId, claim.revision) !== undefined; }).slice(-30).map(([claimId, revisions]) => ({ claimId, statement: revisions.at(-1)?.statement ?? claimId })), recentClaims: Object.entries(state.claims).slice(-30).map(([claimId, revisions]) => ({ claimId, status: revisions.at(-1)?.status ?? "OPEN", statement: revisions.at(-1)?.statement ?? claimId })), blockedClaims: Object.values(state.obligations).filter((item) => item.status === "BLOCKED").map((item) => item.claimId), routes: Object.values(state.routes).slice(-40).map((route) => ({ routeId: route.routeId, targetObligationId: route.targetObligationId, family: route.family, mechanism: route.mechanism, status: route.status, ...(route.failureMechanism === undefined ? {} : { failureMechanism: route.failureMechanism }), ...(route.reopenPredicate === undefined ? {} : { reopenPredicate: route.reopenPredicate }) })), coverageGaps: Object.values(state.coverage).filter((item) => item.disposition !== "CLOSED").map((item) => item.coverageId), authorityRevocations: state.events.filter((item) => item.type === "research/authority_revoked" || item.type === "research/assumption_discharge_invalidated" || item.type === "research/final_proof_stale").slice(-12).map((item) => ({ type: item.type, detail: item.detail })), ...(state.currentFinalProofAuthority === undefined ? {} : { currentFinalProofAuthority: state.currentFinalProofAuthority }), stallCycles: state.cyclesSinceStructuralProgress, budget: state.budget }; }
function validateDirectorProposal(state: ResearchProjectState, proposal: DirectorProposal, frontier: readonly ResearchObligation[]): DirectorProposal { const allowed: DirectorAction[] = ["ATTACK_OBLIGATION", "CREATE_AUXILIARY_OBLIGATION", "SPLIT_OBLIGATION", "REQUEST_REDUCTION", "REQUEST_COUNTEREXAMPLE", "REQUEST_COMPUTATION", "REQUEST_LITERATURE", "RUN_STRUCTURAL_PROBE", "CHANGE_ROUTE", "REOPEN_ROUTE", "SUSPEND_ROUTE", "MARK_ROUTE_EXHAUSTED", "RESTRUCTURE_RESEARCH_MAP", "TRIGGER_SYNTHESIS", "CREATE_CHECKPOINT", "STOP_PROJECT"]; if (!allowed.includes(proposal.action)) throw new Error(`Unsupported Director action: ${String(proposal.action)}`); const targetActions: DirectorAction[] = ["ATTACK_OBLIGATION", "SPLIT_OBLIGATION", "REQUEST_REDUCTION", "REQUEST_COUNTEREXAMPLE", "REQUEST_COMPUTATION", "REQUEST_LITERATURE", "RUN_STRUCTURAL_PROBE", "CHANGE_ROUTE"]; if (targetActions.includes(proposal.action)) { if (proposal.targetObligationId === undefined || state.obligations[proposal.targetObligationId] === undefined) throw new Error("Director referenced a missing obligation"); if (!frontier.some((item) => item.obligationId === proposal.targetObligationId)) throw new Error("Director target is not on the active frontier"); } if (proposal.action === "CREATE_AUXILIARY_OBLIGATION" && (proposal.auxiliaryStatement?.trim().length ?? 0) < 4) throw new Error("Auxiliary obligation requires an exact statement"); let routeObligation: ResearchObligation | undefined; if (["REOPEN_ROUTE", "SUSPEND_ROUTE", "MARK_ROUTE_EXHAUSTED"].includes(proposal.action)) { if (proposal.routeId === undefined || state.routes[proposal.routeId] === undefined) throw new Error("Director referenced a missing route"); const route = state.routes[proposal.routeId]; if (proposal.action === "REOPEN_ROUTE") { if (route?.status === "ACTIVE") throw new Error("Active route cannot be reopened"); const result = route === undefined ? { satisfied: false } : evaluateRouteReopenPredicate(state, route, "MODEL_DIRECTOR"); if (!result.satisfied) throw new Error("Route reopen predicate is not satisfied"); } routeObligation = route === undefined ? undefined : state.obligations[route.targetObligationId]; } const obligation = proposal.targetObligationId === undefined ? routeObligation : state.obligations[proposal.targetObligationId]; return { ...proposal, ...(proposal.targetObligationId === undefined && obligation !== undefined ? { targetObligationId: obligation.obligationId } : {}), ...(proposal.targetClaimId === undefined && obligation !== undefined ? { targetClaimId: obligation.claimId } : {}) }; }
function fallbackDecision(state: ResearchProjectState, frontier: readonly ResearchObligation[], cycleId: string, stallThreshold: number, protocolError?: string): DecisionBasis { const failed = Object.values(state.routes).filter((route) => route.status === "FAILED" || route.status === "EXHAUSTED").map((route) => route.routeId); if (frontier.length === 0) { const readiness = rootSynthesisReadiness(state), action = readiness.ready ? "TRIGGER_SYNTHESIS" : "CREATE_CHECKPOINT"; return { decisionId: stableId("decision", cycleId), cycleId, action, direction: "FALLBACK_DIRECTED", frontier: [], relevantClaims: state.rootClaimId === undefined ? [] : [state.rootClaimId], failedRoutes: failed, reason: readiness.ready ? "Dependency and coverage closure reached" : `No attackable obligation: ${readiness.blockers.join("; ")}`, budgetAllocated: 0, ...(protocolError === undefined ? {} : { protocolError }) }; } const target = frontier[0] as ResearchObligation, stalled = state.cyclesSinceStructuralProgress >= stallThreshold; return { decisionId: stableId("decision", cycleId), cycleId, action: stalled ? "CHANGE_ROUTE" : "ATTACK_OBLIGATION", direction: "FALLBACK_DIRECTED", targetObligationId: target.obligationId, targetClaimId: target.claimId, ...(stalled ? { routeFamily: `fallback-alternative-${state.cycle}` } : {}), frontier: frontier.map((item) => item.obligationId), relevantClaims: [target.claimId], failedRoutes: failed, reason: stalled ? "Stall threshold reached; create and test a concretely distinct route" : "Highest-priority durable frontier obligation", budgetAllocated: 1, ...(protocolError === undefined ? {} : { protocolError }) }; }
function tacticalDirective(state: ResearchProjectState, decision: DecisionBasis): TacticalDirective { const relevantFailedRoutes = Object.values(state.routes).filter((route) => decision.failedRoutes.includes(route.routeId) || route.targetObligationId === decision.targetObligationId).map((route) => ({ routeId: route.routeId, family: route.family, mechanism: route.mechanism, status: route.status, ...(route.failureMechanism === undefined ? {} : { failureMechanism: route.failureMechanism }), ...(route.reopenPredicate === undefined ? {} : { reopenPredicate: route.reopenPredicate }) })); const desired = desiredContributionKind(decision.action); return { directiveId: stableId("tactical-directive", decision.decisionId), directorDecisionId: decision.decisionId, action: decision.action, ...(decision.targetObligationId === undefined ? {} : { targetObligationId: decision.targetObligationId }), ...(decision.targetClaimId === undefined ? {} : { targetClaimId: decision.targetClaimId }), ...(decision.routeId === undefined ? {} : { routeId: decision.routeId }), ...(decision.routeFamily === undefined ? {} : { routeFamily: decision.routeFamily, mechanism: decision.routeFamily }), ...(desired === undefined ? {} : { desiredContributionKind: desired }), reason: decision.reason, relevantFailedRoutes, ...(decision.action === "REQUEST_COMPUTATION" ? { computationIntent: decision.reason } : {}), ...(decision.action === "REQUEST_LITERATURE" ? { literatureIntent: decision.literatureQuery ?? decision.reason } : {}), ...(decision.action === "REQUEST_COUNTEREXAMPLE" ? { counterexampleIntent: decision.reason } : {}), ...(decision.action === "REQUEST_REDUCTION" ? { reductionIntent: decision.reason } : {}), ...(decision.action === "SPLIT_OBLIGATION" ? { caseSplitIntent: decision.reason } : {}), budgetAllocation: decision.budgetAllocated, createdAt: new Date().toISOString() }; }
function tacticalReferences(result: TacticalResearchResult): ArtifactRef[] { const refs = [...(result.targetSubmission === undefined ? [] : [result.targetSubmission.candidate]), ...result.contributions.flatMap((item) => [item.candidate, ...item.evidenceArtifacts]), ...result.routeObservations.flatMap((item) => item.evidence)]; const seen = new Set<string>(); return refs.filter((ref) => { const key = `${ref.artifactId}:${ref.contentHash}`; if (seen.has(key)) return false; seen.add(key); return true; }); }
function assertTacticalResult(value: unknown): asserts value is TacticalResearchResult { if (typeof value !== "object" || value === null || Array.isArray(value)) throw new Error("Malformed TacticalResearchResult"); const result = value as Partial<TacticalResearchResult>; if (typeof result.obligationId !== "string" || typeof result.targetClaimId !== "string" || !["TARGET_PROVED", "TARGET_REFUTED", "TARGET_UNRESOLVED", "EXECUTION_FAILED"].includes(result.targetStatus ?? "") || !Array.isArray(result.contributions) || !Array.isArray(result.routeObservations) || typeof result.executionReceipt !== "object" || typeof result.feedback !== "string") throw new Error("Malformed TacticalResearchResult schema"); if (result.targetStatus === "TARGET_PROVED" && result.targetSubmission?.scope !== "TARGET") throw new Error("TARGET_PROVED lacks a target-scoped submission"); }
function normalizeMath(value: string): string { return value.trim().replace(/\s+/gu, " "); }
function canonicalMathStrings(values: readonly string[]): string[] { const selected = new Map<string, string>(); for (const value of values) { const exact = value.trim(), normalized = normalizeMath(exact); if (normalized.length > 0 && !selected.has(normalized)) selected.set(normalized, exact); } return [...selected.values()]; }
function sameMathSet(left: readonly string[], right: readonly string[]): boolean { return left.map(normalizeMath).sort().join("\n") === right.map(normalizeMath).sort().join("\n"); }
function appendEvent(state: ResearchProjectState, type: string, stablePart: string, detail: Record<string, unknown>): ResearchProjectState["events"] { const eventId = stableId("event", state.projectId, type, stablePart); if (state.events.some((item) => item.eventId === eventId)) return state.events; return [...state.events, { eventId, type, projectId: state.projectId, timestamp: new Date().toISOString(), detail }]; }
function covers(required: readonly ArtifactRef[], inspected: readonly ArtifactRef[]): boolean { const keys = new Set(inspected.map((item) => `${item.artifactId}:${item.contentHash}`)); return required.every((item) => keys.has(`${item.artifactId}:${item.contentHash}`)); }
type MutableState = { -readonly [K in keyof ResearchProjectState]: ResearchProjectState[K] };

function effectiveResearchNumber(state: ResearchProjectState, key: "maxCycles" | "checkpointInterval" | "stallThreshold" | "structuralProbeBudget" | "maxActiveObligations", fallback: number, minimum = 1): number {
	const research = recordValue(state.effectiveConfig.research), value = research?.[key];
	return typeof value === "number" && Number.isFinite(value) ? Math.max(minimum, Math.floor(value)) : fallback;
}

function effectiveBudgetLimits(state: ResearchProjectState, fallback: ResearchRuntimeOptions["budgetLimits"]): ResearchRuntimeOptions["budgetLimits"] {
	const budget = recordValue(state.effectiveConfig.budgets); if (budget === undefined) return fallback;
	const number = (key: string): number | undefined => typeof budget[key] === "number" && Number.isFinite(budget[key]) ? Math.max(0, budget[key] as number) : undefined;
	return { plannerCalls: number("plannerCalls"), workerCalls: number("workerCalls"), verifierCalls: number("verifierCalls"), secondaryAuditorCalls: number("secondaryAuditorCalls"), literatureCalls: number("literatureSearches"), toolCalls: number("toolCalls"), wallTimeSeconds: number("wallTimeSeconds") };
}

function recordValue(value: unknown): Record<string, unknown> | undefined { return typeof value === "object" && value !== null && !Array.isArray(value) ? value as Record<string, unknown> : undefined; }
